### ISSUE TITLE
Missing search results with some typed in diacritics  

### ISSUE THREAD

**Issue by akohlbecker** [gbhl/bhl-europe#1]
Simple Search:
searching for 'Küsten' ( http://test111.ait.co.at/?q=advanced_search_view/{!lucene}K%C3%BCsten ) should return an item with title "Über die Ökologie und Verbreitung der Arthropoden der Triebsandgebiete an den Küsten Finnlands". This does not work when the term 'Küsten' is typed in, however it works when copy/pasting the term from the portal page  http://test111.ait.co.at/?q=node/21991

compare the following searches:

copy paste: http://test111.ait.co.at/?q=advanced_search_view/{!lucene}Ku%CC%88sten
typed in:  http://test111.ait.co.at/?q=advanced_search_view/{!lucene}K%C3%BCsten

**Comment by akohlbecker** [comment]
i don't know how to fix this - sorry

**Comment by leenamba** [comment]
fixed by doing adding this code, etc

**Comment by janahoffmann** [comment]
This issue refers to the CoR feature 1.1.5 I will add the feature with a proper description and add Andreas comments/ descriptions.

**Comment by akohlbecker** [comment]
new ticket #36
