### ISSUE TITLE
Search page - list of search results - UTF 8 problem (also in title homepage)

### ISSUE THREAD

**Issue by fwelter** [gbhl/bhl-europe#10]
Special charcters are not shown correctly in list of search results/query results.

Same query as in issue 9:

http://test111.ait.co.at/?q=advanced_search_view/%7B!lucene%7DKu%CC%88sten

Hit No. 2 (I copy the title with a # and space before as it comes when I paste it):
# Untersuchungen über die säkulare landhebung als pflanzengeograpischer faktor  Jämtlands... kärlväxtflora  Die varietäten von Carex salina wg ssp. cuspidata wg nebst ihren hybriden an den küsten des bottnischen busens, Finnland  Die taraxacum-flora Estlands  Über den antagonismus von wasserstoffionen und metallkationen bei micrasterias  Experimentelle untersuchungen über die euanemochore verbreitung der sporenpflanzen

Here I paste it without # and space:

Untersuchungen über die säkulare landhebung als pflanzengeograpischer faktor  Jämtlands... kärlväxtflora  Die varietäten von Carex salina wg ssp. cuspidata wg nebst ihren hybriden an den küsten des bottnischen busens, Finnland  Die taraxacum-flora Estlands  Über den antagonismus von wasserstoffionen und metallkationen bei micrasterias  Experimentelle untersuchungen über die euanemochore verbreitung der sporenpflanzen

The word " Über " should be spelled Über. The Ü is not displayed correctly in my browser, neither in the list of search results, nor here in the entry form. An incorrect encoding was used. In the edit mode it still looks like Ü (U with dots between the branches, instead of above them), but when the edited page is submitted to github, it will be shown like a somehow distorted ü. 
The word säkulare is correctly displayed.

http://test111.ait.co.at/?q=node/21993

Also in this page the word Über is incorrectly displayed.

**Comment by janahoffmann** [comment]
This issue is included in CoR feature 1.1.5. Your comment will be forwarded to the test manager.
@fwelter
@jirifrank

**Comment by janahoffmann** [comment]
@jirifrank Please include this in the test report for issue 1.1.5 - maybe the feature is not yet implemented...

**Comment by janahoffmann** [comment]
now issue #37
