### ISSUE TITLE
3.2.2 - Download item/content from content viewer

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#100]
Direct download of item from result list
Download from content viewer
Download from 'Download basket'

Precondition: Set up download basket

**Comment by lobajuluwa** [comment]
Update from Portal Review Session, The Hague: function created needs to be implemented by Chris.

**Comment by JiriFrank** [comment]
Will be closed and ready for testing after implementation.

**Comment by lobajuluwa** [comment]
@chris-sleep

**Comment by lobajuluwa** [comment]
Download from content viewer side - Closed & Ready for testing.

Download from Result list - ongoing discussions with developers regarding tagging options.

New Issue created for Result list-side. #278
