### ISSUE TITLE
3.2.3 - Download item in different qualities (Content download)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#101]
Download in different qualities: high, low , color/ bw

Precondition: 'quality' tic box

**Comment by lobajuluwa** [comment]
Update from Portal Review Workshop: function is created – Chris needs to implement it.

**Comment by JiriFrank** [comment]
Will be closed and ready for testing after implementation.

**Comment by lobajuluwa** [comment]
@chris-sleep
