### ISSUE TITLE
3.2.4 - Download item in different file formats (Content download)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#102]
Download items in different formats, e.g. pdf, jpg, OCR

Precondtion: 'format' tick box

**Comment by fwelter** [comment]
OCR: pay attention to consider eventually different character encodings. UTF-8 should be default, but users might eventually like to select other character encodings when downloading an OCR'd text.

**Comment by zhengl** [comment]
Done. The web services are integrated into Fedora Commons. And different formats can be downloaded after ingest.

**Comment by lobajuluwa** [comment]
Update from Portal Review Workshop: feature is already implemented.
