### ISSUE TITLE
Search page - list of search results - replace returns in title by full stop and space

### ISSUE THREAD

**Issue by fwelter** [gbhl/bhl-europe#11]
Once again the same hit in the list of search results/query results:

http://test111.ait.co.at/?q=advanced_search_view/%7B!lucene%7DKu%CC%88sten

4 hits, Hit number 2 when sorted by date:

The title is cited in this form:

Untersuchungen über die säkulare landhebung als pflanzengeograpischer faktor  Jämtlands... kärlväxtflora  Die varietäten von Carex salina wg ssp. cuspidata wg nebst ihren hybriden an den küsten des bottnischen busens, Finnland  Die taraxacum-flora Estlands  Über den antagonismus von wasserstoffionen und metallkationen bei micrasterias  Experimentelle untersuchungen über die euanemochore verbreitung der sporenpflanzen

In the original source the title contains returns:

http://test111.ait.co.at/?q=node/21993
I copy and paste the title here, in the edit mode the returns are inserted as two returns - I replace the two returns here by RETURN and one return:

Untersuchungen über die säkulare landhebung als pflanzengeograpischer faktor RETURN
Jämtlands kärlväxtflora RETURN
Die varietäten von Carex salina wg ssp. cuspidata wg nebst ihren hybriden an den küsten des bottnischen busens, Finnland RETURN
Die taraxacum-flora Estlands RETURN
Über den antagonismus von wasserstoffionen und metallkationen bei micrasterias RETURN
Experimentelle untersuchungen über die euanemochore verbreitung der sporenpflanzen RETURN

So this title has 6 blocks of text, separated by returns. 

Now the task: if the original title contains returns, these returns should be replaced in the list of search results page by:
a full stop (if the original contains no full stop or question mark at the end of the text block) and a space.

The result should look like that:

Untersuchungen über die säkulare landhebung als pflanzengeograpischer faktor. Jämtlands kärlväxtflora. Die varietäten von Carex salina wg ssp. cuspidata wg nebst ihren hybriden an den küsten des bottnischen busens, Finnland. Die taraxacum-flora Estlands. 

(but see issue No. 9, the number of characters in the title should either understand that the browser must not show more than 2 lines of text, or be restricted to 200 characters in the list of search results).

**Comment by janahoffmann** [comment]
This issue is related to CoR feature 1.4.1. Your comment will be forwarded to the test manager.
@fwelter
@jirifrank

**Comment by janahoffmann** [comment]
Jiri, please include this in the test report for #61.
