### ISSUE TITLE
4.1.9 - Link BHL-Europe record (URL) with personal webpage (Community portal)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#112]
Copy/paste link of BHL-Europe record/ content in URL bar to your personal website.

Precondition: 
stable URL/ ID
copyright clearance (notifyer)

**Comment by fwelter** [comment]
The current BHL-US URLs such as 

http://www.biodiversitylibrary.org/item/40475
or
http://www.biodiversitylibrary.org/bibliography/6205

should remain stable and also valid for the European portal.

This should be highest priority because many many biodiversity websites do currently provide "fix" links to those URLs. A large proportion of BHL users come in from such links. Users who follow these links in Europe should be directed to the BHL-Europe portal and not to the BHL-US portal.

**Comment by janahoffmann** [comment]
@chris-sleep
As soon as we can guarantee stable URL's and they are correctly displayed in URL bar we can close this issue.

**Comment by JiriFrank** [comment]
Is testable at the moment on int or test platform. The URL will change for the main domain on the public portal platform, but is stable.

**Comment by JiriFrank** [comment]
4.1.9 - Link BHL-Europe record (URL) with personal webpage (Community portal)

COR number: 4.1.9 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Whole portal

Description:

Copy/paste link of BHL-Europe record/ content in URL bar to your personal website.

The URL will change for the main domain on the public portal platform, but is stable.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
4.1.9 - Link BHL-Europe record (URL) with personal webpage (Community portal)

COR number: 4.1.9 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Whole portal

Description:

Copy/paste link of BHL-Europe record/ content in URL bar to your personal website.

The URL will change for the main domain on the public portal platform, but is stable.

---

@GregKenicer
@GeoffHarper
@KasiaGoral
@MartinaMetzger
@DanielFisher
@NeilWoodcock
@SaraPerzley
@SaraCarlton
@HannaKoivula
@PaiviLipsanen

**Comment by JiriFrank** [comment]
4.1.9 - Link BHL-Europe record (URL) with personal webpage (Community portal)

COR number: 4.1.9 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Whole portal

Description:

Copy/paste link of BHL-Europe record/ content in URL bar to your personal website.

The URL will change for the main domain on the public portal platform, but is stable.

---

@PaiviJaakkola
@SiniKarki
@TiinaOnttonen

**Comment by tiinaonttonen** [comment]
http://onttonen.sharepoint.com/

Works.

**Comment by HenningScholz** [comment]
I think that works.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Do 12.04.2012 19:07
An: Scholz, Henning
Betreff: Re: [bhle] 4.1.9 - Link BHL-Europe record (URL) with personal webpage (Community portal) (#112)

4.1.9 - Link BHL-Europe record (URL) with personal webpage (Community portal)

COR number: 4.1.9
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Whole portal

Description:

Copy/paste link of BHL-Europe record/ content in URL bar to your personal website.

The URL will change for the main domain on the public portal platform, but is stable.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by RalfH** [comment]
It works.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Donnerstag, 12. April 2012 19:08
An: Hand, Ralf
Betreff: Re: [bhle] 4.1.9 - Link BHL-Europe record (URL) with personal webpage (Community portal) (#112)

4.1.9 - Link BHL-Europe record (URL) with personal webpage (Community portal)

COR number: 4.1.9 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Whole portal

Description:

Copy/paste link of BHL-Europe record/ content in URL bar to your personal website.

The URL will change for the main domain on the public portal platform, but is stable.

---

@GregKenicer
@GeoffHarper
@KasiaGoral
@MartinaMetzger
@DanielFisher
@NeilWoodcock
@SaraPerzley
@SaraCarlton
@HannaKoivula
@PaiviLipsanen

---

**Comment by JiriFrank** [comment]
Works. Ready to be closed.
