### ISSUE TITLE
4.1.10 - Receive BHL news via email (Community portal)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#113]
Provide subscription box for, e.g. newsletter, RSS feeds, etc. 

Precondition: 
Registration with email address

**Comment by JiriFrank** [comment]
Could we split this task to separate email option informing user about items in his basket which are ready for download. And also for RSS. The description of this feature need to be changed. 

@janahoffmann

**Comment by janahoffmann** [comment]
@jirifrank
Well, these are two very different things. This featur ehere only deals with subscription for the newsletter (see BHL-Europe homepage).
The other aspect: 
I don't know how the download from the batch download basket will work. The to be downloaded items won't be ready right away? Why do we need a notification for the user? I thought they can download items directly from the basket either providing their email address (if different from profile address) or using the email address that is provided for the profile. I thought usage of the basekts requires login. Please clarify.
