### ISSUE TITLE
4.1.13 - Batch download of articles: ‘batch download basket’ (Community portal)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#116]
shopping basket style
items added per drag&drop or by click (pull down menu)
Features: change download format, quality, etc., choose target folder

**Comment by janahoffmann** [comment]
Please assign task to developer.

**Comment by janahoffmann** [comment]
This issue is a duplicate of #68 and was deleted from the CoR.

**Comment by JiriFrank** [comment]
@janahoffmann
Template and user interface (UI) are two different things. Template is the overall design and the UI is more connected with the functionality and how it display to the user.
