### ISSUE TITLE
4.1.14 - Download compressed files/ folder

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#117]
Choose compression options in download basket

Precondition: Download basket

**Comment by lobajuluwa** [comment]
Update: all features grouped under "Portal Basket" to be reassigned temporarily to CS. Tasks  to be reassigned e.g. NMP/IT4Care.

**Comment by janahoffmann** [comment]
@lobajuluwa
This feature can be closed/deleted as it is a duplication/ included on issue #68.

**Comment by lobajuluwa** [comment]
Issue Closed/Deleted - Duplicate!
