### ISSUE TITLE
4.1.16 - Look & Feel (Community portal)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#119]
Applying web design to BHL-Europe Drupal theme.

**Comment by JiriFrank** [comment]
The new template will be instaled today 10th August between 2:30 - 3:30 pm.

**Comment by janahoffmann** [comment]
New template online and working. Web design work continues. 
Open for testing?

**Comment by janahoffmann** [comment]
@jirifrank
Is this the same as #104? or is this the application/ integration of the theme?
