### ISSUE TITLE
Search page - list of search results - restrict number of co-authors

### ISSUE THREAD

**Issue by fwelter** [gbhl/bhl-europe#12]
The list of co-authors should be restricted in the list of search results. If more than 3 co-authors are listed in the "creator" field, then only the first 3 co-authors should be listed, separated by comma and space, followed by the term   " et al. "

We take the same example as in issues 9, 10 and 11.

http://test111.ait.co.at/?q=advanced_search_view/%7B!lucene%7DKu%CC%88sten

Hit No. 2 when sorted by date.
The co-authors (authors, creators) are currently shown in this form in my browser:

Valovirta, E. J.; Lange, T. H.; Saxen,... Uno.; Marklund, Gunnar.; Waris, Harry.; Pettersson, Bror.

In the title page
http://test111.ait.co.at/?q=node/21993
Beitragende = co-authors in the sense I am using this term here:

Valovirta, E. J.
Lange, T. H.
Saxen, Uno.
Marklund, Gunnar.
Waris, Harry.
Pettersson, Bror.

It is usual standard in bioscientific contexts to cite authors only with last name and initials of first names.

So this should look like that:

Valovirta, E. J., Lange, T. H., Saxen, U. et al. 

Compare with issue #8, the date should be shown after the author.

Sorry, I just realised that the title shown here:
http://test111.ait.co.at/?q=node/21993
is absolute nonsense from another point of view. 
It might serve as an example for the present issue, but the title itself contains obviously are much more serious bug: it seems to list accidentally all the titles and authors of an entire serial run, issued between 1937 and 1940. I will write a separate issue about this bug.

**Comment by janahoffmann** [comment]
This issue relates to CoR feature 1.4.1. Your report will be forwarded to the test manager.
@fwelter
@jirifrank

**Comment by janahoffmann** [comment]
Jiri please include this as bug for issue #61 or others?
