### ISSUE TITLE
4.2.5 - Change individual setting for batch download (‘basket’)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#128]
Define target-folder, formats, styles, etc. (only registered users)
Precondition: Download basket

**Comment by janahoffmann** [comment]
Please distribute tasks

**Comment by lobajuluwa** [comment]
Update from The Hague workshop: assigned to Lee Namba already implemented on the NHM test server, not integrated into the portal – ready for testing.
Also see (#116)

**Comment by chris-sleep** [comment]
dependency on content tagging
