### ISSUE TITLE
Search page - list of search results - inadequate results shown for Austrian journals

### ISSUE THREAD

**Issue by fwelter** [gbhl/bhl-europe#13]
The results given for Austrian contant seems to have serious bugs and displays mixed information. The display of the results and the contents of the tables as such is problematic.

http://test111.ait.co.at/?q=advanced_search_view/%7B%21lucene%7Dsuecica

Gives 3 hits. 

Hit No. 1: 

Zeitschrift der Wiener Entomologischen Gesellschaft 34
Anonymus , Beier Max Walter Peter, Boursin Charles, Bretschneider Richard, Burmann Karl, Feichtenberger... 
Oberösterreichisches Landesmuseum 

This is a journal volume. The authors are not the authors of the journal volume, but of separate articles contained in this journal. They must not be displayed in the list of search results. Simply remove the authors. A journal volume has no author.

But a journal volume must have a year, and this year should be displayed in the list of search results. 
So it should look like that:

Zeitschrift der Wiener Entomologischen Gesellschaft 34 (1985)
Oberösterreichisches Landesmuseum 

Not more. 
See also issue #7: the information that we are dealing with a journal should be contained in the icon.

(I have not checked if 1985 was true, the year does not even show up anywhere on the title page:
http://test111.ait.co.at/?q=node/13976
When I tried to open the pdf
http://www.biologiezentrum.at/pdf_frei_baende/27009.pdf
my computer crashed down.
It is necessary to open the results in a viewer, and not directly in the Acrobat Reader (that will usually not be compatible with the file format used by the contributor).

In hits 2 and 3 (sorted by date) something goes wrong. Here all the authors and articles are listed, absolute nonsense. It makes sense to display articles and authors of articles, but not in this form.

**Comment by janahoffmann** [comment]
This issue is already included in CoR feature 1.4.1 and 1.43 (in part). Your comment will be forwarded to the test manager. Howver, I think the bug is more related to the mapping and pre-ingest rather than the portal display function.
@fwelter
@jirifrank

**Comment by janahoffmann** [comment]
Jiri please add this as reported bug in the test report.
