### ISSUE TITLE
4.3.3 - Change login details

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#132]
Change login details e.g. user name, password, email address

**Comment by fwelter** [comment]
Should be made clear who is expected to login and why. A page would be needed that explains which additional rights login users have, and that all important core tasks/services are accessible without login.
Counts would also be useful (for us: to see the proportions how many users are logged in and how many not).

In the BHL User Survey several participants said that they do not like services where you have to login. So we should pay attention to restrict user registration only to marginal tasks.

**Comment by janahoffmann** [comment]
I think the core functionalities will be accessible without login. However some functionalities including additional services (user profile, customization of search and download) will require a login.

**Comment by bendao** [comment]
Once logged in you find the "My account" Link at the top of the page. This allows you change all the your user settings. 

Drupal will ask you to log in whenever you access a page you do not have the right credentials for. These rights can be modifies by any site administrator.

**Comment by lobajuluwa** [comment]
@JiriFrank
Hi Jiri, can you pls confirm whether this Issue is still a feature requirement or not i.e is it Closed for testing or to be "deleted". If ready for testing.....should it be scheduled for the Nov Release? Thanks, Lola.

**Comment by JiriFrank** [comment]
@lobajuluwa
Hi Lola, this feature is part of the My account administration and it was functional during the first testing process. We need to test it together with the new UI on the stabile testing platform now. I will open it for the future testing. It will be part of the November release of course.

**Comment by lobajuluwa** [comment]
Done!

**Comment by JiriFrank** [comment]
4.3.3 - Change login details

COR number: 4.3.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: My account

Description:

Change login details e.g. user name, password, email address

You need to first create a new account.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
JiriFrank commented 1 day ago
4.3.3 - Change login details

COR number: 4.3.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: My account

Description:

Change login details e.g. user name, password, email address

You need to first create a new account.

@AntonioGVH
@fwelter
@LarissaS

**Comment by RalfH** [comment]
It works. No problems.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 16:48
An: Hand, Ralf
Betreff: Re: [bhle] 4.3.3 - Change login details (#132)

4.3.3 - Change login details

COR number: 4.3.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: My account

Description:

Change login details e.g. user name, password, email address

You need to first create a new account.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
This works, with one slight issue.  When I changed the password, a pop up box appeared asking me to confirm which user I wanted to change the password for, and the options were my user name (Graham Hardy) and my e-mail address.  The default was the e-mail address which I selected.  I then logged out and logged in using the changed password and it seems to be okay.

**Comment by HenningScholz** [comment]
I don't see where to change the user name. I can change everything else, but not the name. Missed anything?

---

Dr. Henning Scholz 
Museum für Naturkunde | Leibniz Institute for Research on Evolution and Biodiversity at the Humboldt University Berlin
Invalidenstraße 43 | D-10115 Berlin | Germany 
Tel.: +49-30-2093-8864 | Fax: +49-30-2093-8868 
Email: henning.scholz@mfn-berlin.de
http://www.naturkundemuseum-berlin.de/ / http://www.bivalve.de 
http://www.bhl-europe.eu / http://www.biodiversitylibrary.org/
BHL-Europe in Europeana:  bit.ly/BHLE-Europeana

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 16:48
An: Scholz, Henning
Betreff: Re: [bhle] 4.3.3 - Change login details (#132)

4.3.3 - Change login details

COR number: 4.3.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: My account

Description:

Change login details e.g. user name, password, email address

You need to first create a new account.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by HenningScholz** [comment]
Francisco brought up an interesting aspect: I also tried the change of language between search and advanced search, like Francisco described, language switched back from German to English, even on IE. Then I checked the language set up under my account and I realise that it does not work at home under IE9, but it worked under IE8 at work. I don't know if this has to do with the fact that the multilinguality feature is not fully implemented...

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 16:47
An: Scholz, Henning
Betreff: Re: [bhle] 4.3.3 - Change login details (#132)

4.3.3 - Change login details

COR number: 4.3.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: My account

Description:

Change login details e.g. user name, password, email address

You need to first create a new account.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AntonioGVH** [comment]
This function seem sto have problems.
I created a new account but didn't get a password. But still recognizes my name and email (Antonio Garcia; torrenticola@hotmail.com), but when I requested a password, then does not identify the email as given (in the previous window).

Quoting JiriFrank:

**Comment by JiriFrank** [comment]
@HenningScholz 
It works for me in IE9 and Chrome. But the browser compatiblity is not done yet. It will be done when we will have main part of functionalities on portal and also integrated the content viewer. Multilingual is fully implemented.

Francisco had different problem. He changed the languages without login in. In that case the portal using the language of your browser on all pages if you do not change that. So it was the reason, why the language was always changed to German in new window.

It is standard Drupal account where is not possible to change your login name, because it is strictly bound with your account. But we can set up login by account name or contact email. For this new module will be install. 

@AntonioGVH 
I am sorry Antonio. Your email was probably misinterpret by Chris as attack. Chris will check it. Maybe control your spam filter if the email with password is not there.

Request Issue #293
Suitable module for user account could be http://drupal.org/node/34309.
Ready for close. Other task are related to settings the account which will be discuss.
