### ISSUE TITLE
4.3.4 - Set up user profile

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#133]
Set up user profile with personal information, picture, etc. (registered user)

**Comment by JiriFrank** [comment]
Testing of feature 4.3.4 - Set up user profile

Feature description from the Catalogue of user requirements:

Set up user profile with personal information, picture, etc. (registered user)

Testers:
@janahoffmann
@JFTester
@JiriFrank

**Comment by JiriFrank** [comment]
This function is working properly.

**Comment by chris-sleep** [comment]
No further need for Personal Info; Picture etc.

User Profile for users to enable features for saved searches, tagging only
