### ISSUE TITLE
4.4.2 - Add/ edit tags

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#135]
Add/edit tags or flag status of item, e.g. provenance, disciplines, taxa

Crowd sourcing? - registered user (e.g. scientists, librarians)

**Comment by lobajuluwa** [comment]
Lee: Need to confirm if this refers to Book level or page level? If book level then more of a Portal Issue. Also, depends on if we use Islandora - as they might even have something that does this request.
