### ISSUE TITLE
4.4.7 - Edit OCR text

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#140]
Make changes/ corrections in OCR text (only registered user) - Crowd sourcing, Wiksource?
Display changes/ improvement in portal

Precondition: editorial team for approavl of changes (CP's?)

**Comment by sprogerb** [comment]
Portal Feature not provided by AIT, Also pre-conditions not in place.

**Comment by JiriFrank** [comment]
Thi is not assigned feature yet.

**Comment by lobajuluwa** [comment]
Move to "Wish List"
