### ISSUE TITLE
4.4.8 - User survey

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#141]
New description:
'check box' for willingness to participate in the user survey when set up an account
provide email contact information

Old description covered by 4.3.4

Small user survey when login for the first time: assessment of user identity, user role, institution, etc.

Precondition: rights clearance (storage and use of personal data)

**Comment by janahoffmann** [comment]
link to use case page or feedback page (use case page or general feedback page (guestbook) not yet defined as feature, but might be important) - What do you think @jirifrank

**Comment by JiriFrank** [comment]
Yes, it might be important, good aditional feedback and inspiration for users. But I am not sure, that it will be the August release. We could labeled by November label? @janahoffmann

**Comment by chris-sleep** [comment]
Usage and rights to be discussed with JK; 

not a first logon survey, after logon send email with a survey link

need definition of survey from JK before will progress

**Comment by chris-sleep** [comment]
Target March 2012

**Comment by janahoffmann** [comment]
@jirifrank
provide design/ concept for user survey

**Comment by HenningScholz** [comment]
After having it today in the CWG, we don't think it makes sense to keep the feature. Making a survey after the hardlaunch would set expectations we are not able to fulfill. We better do the user survey with a grou we select and fulfill the user survey requirement.
