### ISSUE TITLE
Implement Pre-Ingest Tool

### ISSUE THREAD

**Issue by lobajuluwa** [gbhl/bhl-europe#144]
DoW task:- 3.1.5

Tasks to be completed:-

Provide access to content providers for the Pre-ingest Tool for testing
Provide Pre-ingest description for content providers and BPG
Feedback from selected CPs [Content Providers]
Take feedback into account
Provide final Pre-inget tool & access to all content providers

**Comment by sprogerb** [comment]
Tool ready for testing

**Comment by lobajuluwa** [comment]
@melitabirthaelmer
@bgol

**Comment by sprogerb** [comment]
sprogerb out of duty
