### ISSUE TITLE
Multilingual Vocabularies (planned to be released) on Portal

### ISSUE THREAD

**Issue by lobajuluwa** [gbhl/bhl-europe#152]
DoW: 3.4.3

**Comment by sprogerb** [comment]
Dedicated to NHMW

**Comment by janahoffmann** [comment]
This issue cannot be close if it is not done.

**Comment by lobajuluwa** [comment]
Hi Wolfgang, I've reopened this Issue as per above comments. This project task was transferred over from the Scrum backlog. Hence, if it's already being covered under several features already assigned to NHMW then we don't need to duplicate effort. 
@wkollernhm

**Comment by lobajuluwa** [comment]
This Project task Issue can be closed since it's already being covered under NHMW tasks grouped under Web Services.
