### ISSUE TITLE
Enrichment of Metadata (OCR Improvement Taxon Finder)

### ISSUE THREAD

**Issue by lobajuluwa** [gbhl/bhl-europe#153]
DoW: 3.1.5

**Comment by sprogerb** [comment]
That's done and implemented in Pre-Ingest using tesseract 3 and taxon-finder with taxon finder webservice.

**Comment by janahoffmann** [comment]
We cannot test this feature and thus it cannot be closed.

**Comment by lobajuluwa** [comment]
This issue can now be closed as it's related to Pre-Ingest. (now being managed by NHMW).
