### ISSUE TITLE
Portal – Interface for downloading realtime derivatives: PDF

### ISSUE THREAD

**Issue by audreyhzhang** [gbhl/bhl-europe#16]
Download one page in PDF format 
Download a book in PDF format

**Comment by fwelter** [comment]
On the portal shall be shown the file size of the book in MB, so that users ca see what they have to expect. 
Or maybe make a separate issue for this feature? I don't know.

**Comment by leenamba** [comment]
depends on how realtime the download is.  If we generate on the fly then showing the file size will be hard.  If we generate and save to an ftp site for download then we can do this.  Otherwise an algorithm for estimating could be used but would not be accurate.  TBD

**Comment by fwelter** [comment]
PDFs of books should not take too much memory space, but I cannot judge this. 3 alternative solutions:

1 - Create PDFs of all books and save them in our archive, ready for download.
2 - Create "low resolution PDFs" of all books and save them in our archive, ready for download. Then provide 2 buttons: PDF (low resolution, bitonal black and white, equipped with file size), PDF (high resolution, brown on tan).
3 - The pdf file is saved to our internal archive the first time when a user downloaded a pdf, and the file size is recorded and from this moment onwards the true file size can be displayed. If the title has not yet been downloaded by anyone, an estimated value can be displayed, equipped with the note "estimated value".

Version 3 would make sure that only of important works PDFs are stored in the archive.
Versions 2 and 3 could be combined.

I cannot judge if creating low-resolution PDFs under (2) would allow to estimate or calculate relatively reliably the high res file size under (1).

In SUB Göttingen they are using estimated values and create PDFs on the fly, but the experience is that nonsense is displayed in these values. Such a solution should be avoided.

**Comment by janahoffmann** [comment]
The original issue relates to CoR feature 3.2.4 and 3.2.5. Franciscos comment refers to CoR feature 1.5.4. Your comments will be added to the respective features once I have set them up with a proper description.

**Comment by janahoffmann** [comment]
Franciscos comment now issue #73

**Comment by janahoffmann** [comment]
now issue #99
