### ISSUE TITLE
BHL-E Portal needs update of Drupal core to current drupal 7.x

### ISSUE THREAD

**Issue by akohlbecker** [gbhl/bhl-europe#164]
The current version of Drupal core is 7.0, an update to version 7.4 is highly recommended not only for security reasons.

**Comment by akohlbecker** [comment]
Update of all module and drupal core with drush worked well on my local machine, however since the portal is not jet fully working (see #165) I will not commit and push these changes.
Drush command:

```
 drush up
```

**Comment by akohlbecker** [comment]
Drupal has been updated  to version 7.8 by @jhquentin  Thanks!

**Comment by jhquentin** [comment]
Version 7.9 is out?
We should update it.

**Comment by JiriFrank** [comment]
7.10? :-)
