### ISSUE TITLE
Installation instructions for Portal incomplete

### ISSUE THREAD

**Issue by akohlbecker** [gbhl/bhl-europe#165]
The "AIT" portal (https://github.com/bhle/bhle/tree/master/portal/drupal-ait) is not running out of the box after walking through the instructions on https://bhl.wikispaces.com/github

The following components need to be installed in addition:
- lucene server

Developers might be blocked by this, completion of the instructions is urgently needed!

**Comment by lobajuluwa** [comment]
Hi Lee,
Andreas raised this issue a couple of weeks ago but he's currently on hols and since it wasn't assigned to anyone, against any milestone it hasn't been picked up since then.
Is this still an issue for developers or has it been resolved? Thanks.

**Comment by leenamba** [comment]
I reassigned to AIT.  Should go to Odo who is in charge of portal development

**Comment by akohlbecker** [comment]
The missing instructions have been made available at https://bhl.wikispaces.com/PortalDevelopementSetup
