### ISSUE TITLE
1.2.3 - Search by range of years of publication

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#170]
This feature is not working correctly.
If you select the metadata field 'date' and indicate a range e.g. 1901-1905 it also displays results with 1905 in the "title" metadata field.
It should only display result with the years 1901-1905 in the "date" of publication metadata field.
The search is only performed for the start and end point e.g. if you search for 1857 to 1859 the search is only performed for "1857" and "1859", but it should also search for 1858. 

Brackets are needed for search for ranges mentioned in Advance search3: [start TO end], but it reports an error. mentioned bug #179

feature #46

**Comment by bendao** [comment]
The portal now accepts ranges in the form of e.g. 1917-1988 in search fields.

**Comment by JiriFrank** [comment]
On the testing server for search by range of years of publication is necessary chose the field date and the range for example [1872 TO 1890]. In this case the search by range of years of publication is working properly.
