### ISSUE TITLE
1.1.1 – Search results should always be ordered by relevance

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#173]
Search results should always be ordered by relevance (see  #274)

Old title and description (before 12.12.2011):
 Search results should always be ordered by title (Simple Search)
 Search results should always be ordered by title ( decided in UI workshop 1 - 3)

old description:
- best matches shall be displayed first, e.g. Denisia Bartsch; the actual item that matches Denisia (title) and Bartsch (author) is listed at 5th place and less good hits with just one of the two keywords are listed before.

For more details see comments Issue #33

**Comment by akohlbecker** [comment]
This ticket not up to date with latest decisions, changing description

**Comment by akohlbecker** [comment]
This is fixed

**Comment by JiriFrank** [comment]
Bug - 1.1.1 – Search results should always be ordered by relevance

COR number: it is bug related to feature 1.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Bug description:

Search results should always be ordered by relevance

The result list should always be sorted by relevance (decision from Portal review meeting in Brussles)

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
Bug - 1.1.1 – Search results should always be ordered by relevance

COR number: it is bug related to feature 1.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Bug description:

Search results should always be ordered by relevance

The result list should always be sorted by relevance (decision from Portal review meeting in Brussles)

@AntonioGVH
@fwelter
@LarissaS

**Comment by LarissaS** [comment]
It works as far as I can estimate the relevance

-----Original Message-----

**Comment by RalfH** [comment]
A bit difficult to be judged without a catalogue of criteria and background informations (which I do not find at the moment in other documents).

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 16:13
An: Hand, Ralf
Betreff: Re: [bhle] 1.1.1 - Search results should always be ordered by relevance (#173)

Bug - 1.1.1 - Search results should always be ordered by relevance

COR number: it is bug related to feature 1.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Bug description:

Search results should always be ordered by relevance

The result list should always be sorted by relevance (decision from Portal review meeting in Brussles)

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
Think number of sample books too small to test this adequately

**Comment by HenningScholz** [comment]
Difficult to test, what are the relevance criteria?

---

Dr. Henning Scholz 
Museum für Naturkunde | Leibniz Institute for Research on Evolution and Biodiversity at the Humboldt University Berlin
Invalidenstraße 43 | D-10115 Berlin | Germany 
Tel.: +49-30-2093-8864 | Fax: +49-30-2093-8868 
Email: henning.scholz@mfn-berlin.de
http://www.naturkundemuseum-berlin.de/ / http://www.bivalve.de 
http://www.bhl-europe.eu / http://www.biodiversitylibrary.org/
BHL-Europe in Europeana:  bit.ly/BHLE-Europeana

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 16:13
An: Scholz, Henning
Betreff: Re: [bhle] 1.1.1 - Search results should always be ordered by relevance (#173)

Bug - 1.1.1 - Search results should always be ordered by relevance

COR number: it is bug related to feature 1.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Bug description:

Search results should always be ordered by relevance

The result list should always be sorted by relevance (decision from Portal review meeting in Brussles)

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AntonioGVH** [comment]
Using 'Flora' as search string I get several records. 
I don't know what could be 'relevance' in this case. 
I find the result reasonable, because it is a short list of books. To sort it by 'relevance' may be it would be necessary to use more than one search criteria (e.g. 'Flora ' + language 'eng' + date range '1930 - 1950' etc)

Quoting JiriFrank:

**Comment by JiriFrank** [comment]
This feature is hard to test without more content. Good question is what are the criteria. First term in first field?

I do not know now how to effectively test this feature now.
@akohlbecker 

Will be tested again with more content.
