### ISSUE TITLE
1.1.1 – Search with unordered keywords results (Simple Search)

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#174]
Search with unordered keywords with terms which are not included together in a book. The list of books (search result) is ordered chaotically and groups of books with the same searching terms are spread out over the list.

For more details see comments Issue #33

**Comment by akohlbecker** [comment]
this ticket is unclear, please see https://github.com/bhle/bhle/issues/33#issuecomment-2848698

**Comment by akohlbecker** [comment]
closing since #33 is also closed

**Comment by JiriFrank** [comment]
solved by sorting the result list by relevance and setting the defalut Boolean operator AND between the terms.
