### ISSUE TITLE
1.1.6 - Search with diacritics (now Advanced Search 1.2.12 - Search with excat phrases only)

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#177]
Search with special words is working but in the results are also these words without diacritic or just part of that word with complete different meaning. In that case the result is not what the user expected.

Is there an option search the exact word, for example “Král“(King)? In this case I have 10 books in result, but none of them includes “Král“, but just "Kral" with different meaning. If there are no books with "Král", I will get 0 results.

It seems, that the search with exact words have a tolerance in diacritic etc. - connection with exact phrase search using bolean operators.

Feature #55

**Comment by akohlbecker** [comment]
The exact search is by now implemented by just applying the according Solr QuerySyntax to the query string entered in the  field "with exact phrase":

```
Král ==> "Král"
```

however the field being used during this search is the same as for all other searches, the tokens in this field are "expanded" by the SnowballPorterFilterFactory. Exact search should use a field with an special field type which is not using the SnowballPorterFilterFactory

**Comment by akohlbecker** [comment]
fixed by 53ea228

The the exact search option is implemented by introducing a new copyField "all_exact".  The functionality has been made available by example in the portal implementing a new search page called "Exact Search". It is available from the Navigation menu.

**Comment by akohlbecker** [comment]
In order to test the "Exact Search" you have to drop the selenium core2 and re-index.
