### ISSUE TITLE
1.1.7 - Search with truncated terms (now Advanced search 1.2.15)

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#178]
Bug: Searching with truncated terms at the end works just in specific length of searched word.

Bug: Searching with truncated terms at the beginning doesn’t work.

This is a case of two bugs under one feature in which I am not sure if is it wise to separate them or report together. If the solution for these bugs will be very different, we can split them in to two issues.

For more details see comments in Issue #39

**Comment by lobajuluwa** [comment]
needs inversion filter solr - moved to Jan 2012 release

**Comment by akohlbecker** [comment]
We have to use the ReversedWildcardFilterFactory

Here is an article on this issue: http://lucidworks.lucidimagination.com/display/lweug/Wildcard+Queries#WildcardQueries-WildcardsatStartofTerms

**Comment by akohlbecker** [comment]
#191 is unresolved special case which is related to this issue!
