### ISSUE TITLE
1.1.9 - Search with incomplete words using wildcard options (now Advanced Search 1.2.16)

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#179]
Bug: using [] reporting an error. Brackets are needed for search for ranges mentioned in Advance search3: [start TO end]

For more details see comments in Issue #39

**Comment by akohlbecker** [comment]
@JiriFrank  This issue has become invalid. Using [] is not permitted neither in simple nor in advanced search
therefore I think we need a new ticket: 

"Strip any disallowed characters from solr queries"

**Comment by akohlbecker** [comment]
new issue created: #247 and closing this one as invalid
