### ISSUE TITLE
1.2.10 - Search for publishing language

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#180]
Search for language works fine in general but only if you use:
e.g. "deutsch", it doesn't work for "German" - predefined search terms required (generally understood), pull down menus would be very helpful for the user here (existed in German prototype)

In facet list inconsistent use of language description...sometimes 'eng' and sometimes 'english' or 'ger' and 'German'

There is not defined search for Russian and Spanish
Matches for: dc_language:Russian have 0 results.
The same for Matches for: dc_language:Español or Matches for: dc_language:Spanish
The same for Matches for: dc_language:French or Matches for: dc_language:Français
for French works fra
Books written by these languages are on portal.

search for publishing country not established - what would be the correct metadata field for search?

It seems that several Collections don't have the language in metadata, for example NBN and LANDOE.

For more details see last comments in Issue #237, #53

**Comment by janahoffmann** [comment]
@melitabirthaelmer
@wkollernhm
How many CP's provide the language field? and is there another way to "tag" the language and origin (place) of publication?

**Comment by lobajuluwa** [comment]
Requirement - Translation services for language names needed. 

Wolfgang has suggested that this should be split into 2 separate issues i.e. 
1) document language (Nov 2011 Release and dependent on services) &
2)Search for publishing country.(March 2012). 

Jana to discuss further with Wolfgang before feature in CoR is revised and updates made in GitHub.

@wkollernhm
@janahoffmann

**Comment by janahoffmann** [comment]
@lobajuluwa Discussed and done!

**Comment by wkollernhm** [comment]
As discussed yesterday during the tech call I will close this issue.

**Comment by JiriFrank** [comment]
Under process of testing.

**Comment by JiriFrank** [comment]
Related Issue #237
