### ISSUE TITLE
1.3.1 - Browse by Author

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#182]
The results are not sorted alphabetically. Manual alphabetical sorting option sorts the results just by the first author.

Feature #57

**Comment by lobajuluwa** [comment]
The following bugs should also come under feature 1.3.1 i.e. no need to treat them as separate issues.
#183  Browse by Year
#181 Browse by Title

**Comment by JiriFrank** [comment]
Hi Lola, it is nota a feature but reported bug =-)
@lobajuluwa

same as Browse by Title and Year

assigned person is solving the bug

**Comment by lobajuluwa** [comment]
Ooops! Yep, you're right these are all being grouped as bugs!
@JiriFrank

**Comment by JiriFrank** [comment]
The sorting by relevance is not fixing the bug. We tested with Chris.

Is really @jhquentin responsible to this bug or it needs to be fixed by somebody else? @chris-sleep

**Comment by JiriFrank** [comment]
1.3.1 - Browse by Author

COR number: 1.3.1 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Browse

Description:

Use Browse option for browse by author.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
1.3.1 - Browse by Author

COR number: 1.3.1 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Browse

Description:

Use Browse option for browse by author.

---

@GregKenicer
@GeoffHarper
@KasiaGoral
@MartinaMetzger
@DanielFisher
@NeilWoodcock
@SaraPerzley
@SaraCarlton
@HannaKoivula
@PaiviLipsanen

**Comment by JiriFrank** [comment]
1.3.1 - Browse by Author

COR number: 1.3.1 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Browse

Description:

Use Browse option for browse by author.

---

@PaiviJaakkola
@SiniKarki
@TiinaOnttonen

**Comment by LarissaS** [comment]
Browse does not give good result. I always get no results or 6 same results for all my attempts (by title, author or year of publication)!

-----Original Message-----

**Comment by HenningScholz** [comment]
This is not working. I have compared with the integration site, where it is working, so seems to be that you find the problem.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Do 12.04.2012 19:15
An: Scholz, Henning
Betreff: Re: [bhle] 1.3.1 - Browse by Author (#182)

1.3.1 - Browse by Author

COR number: 1.3.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Browse

Description:

Use Browse option for browse by author.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by RalfH** [comment]
Possibly, I am doing the wrong thing. 
Well, browsing for authors clicking on certain letters produces correct results but there is no differentiation between family and fore names. 

Anyway, in a much more populated data base you will receive endless lists. What is the intention of that feature?

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Donnerstag, 12. April 2012 19:15
An: Hand, Ralf
Betreff: Re: [bhle] 1.3.1 - Browse by Author (#182)

1.3.1 - Browse by Author

COR number: 1.3.1 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Browse

Description:

Use Browse option for browse by author.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamtestrbge** [comment]
Agree that the retrieved results seem to be drawing in all parts of the Author name field, beginning with the upper case form of the letter browsed, eg, Aigret, Amedee for A and Follmann and Friedrich for F.   Would be better if it only retrieved surname.

Browsing on Title also retrieves all occurrences of words in the title beginning with the browse letter selected.

**Comment by KasiaGoral** [comment]
When browsing by letter 'C' I got 7 results, some of them did not
correspond with the browsing letter, e.g. Barreiro, Agustín Jesús.,
Hernández-Pacheco y Esteban, Eduardo.

**Comment by AntonioGVH** [comment]
It seems that doesn't work in my computer.

I clicked by 'title' and letter 'L' (screen shot First) and I got a list of titles not all beginning by 'L' (screen shot Second).

Then I changed to 'author' and clicked on letter 'E' (screen shot Third) and I got the same list of books as in the previous query (Screen shot Fourth).

The family name of the authors obtained in the second query  do not begin by 'E'

Antonio

-----Mensaje original-----
De: JiriFrank [mailto:reply@reply.github.com] 
Enviado el: jueves, 12 de abril de 2012 19:15
Para: AntonioGVH
Asunto: Re: [bhle] 1.3.1 - Browse by Author (#182)

1.3.1 - Browse by Author

COR number: 1.3.1 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Browse

Description:

Use Browse option for browse by author.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
The Browse by author function is using first letter of all words in title field, because there is not consistency in position between the first, middle or last name. The result is highlighted in result list to explain to the user why this content were chosen. 

Ready to be closed.
