### ISSUE TITLE
Integration of  webservices for names_lookup module

### ISSUE THREAD

**Issue by lobajuluwa** [gbhl/bhl-europe#187]
NHMW have since pushed the names_lookup module over to github which provides the functionality to search for scientific names using a common names. 
It uses both the Catalogue of Life and the PESI webservices for its lookup.

The integration of this service into the actual search process needs to take place. (feature cannot be closed for testing until module has been integrated into search process.

Refer to Issue (#74) Search for Content by Colloquial names for Issue history

**Comment by wkollernhm** [comment]
Closing this issue since I re-opened issue #74 -> more specific task.

**Comment by JiriFrank** [comment]
Under process of testing

**Comment by JiriFrank** [comment]
Web-services are implemented but need to be tested with more content and content from PI.
