### ISSUE TITLE
1.4.1. Numeration in result list (Result list)

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#190]
Amount of searching items in the search result which Matches for: x y terms.
Number the items in search result list.

For more details see comments in Issue #33 

Related feature: #61

**Comment by bendao** [comment]
This is an additional feature of the search function.
It requires the portal to break the search into pieces and query the indexer for hit counts.

**Comment by lobajuluwa** [comment]
Jana hi, not sure if you've had a chance to look at this feature request? Can you pls confirm if it's valid/agreed so that we can label it as a feature etc and assign accordingly to the right developer. Thanks.
@JanaHoffmann

**Comment by janahoffmann** [comment]
I assigned it to the feature #61. It is not a single feature unless you want it to be, it is more a requirement. Let me know what you want and I can change it. 
@lobajuluwa

**Comment by lobajuluwa** [comment]
Absolutely fine the way it is listed as one of the requirements for feature #61. Thanks.
@janahoffmann
