### ISSUE TITLE
1.4.x Duplication in content

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#193]
Several records are duplicated, for example “Mollusca: Varia II” from RMCA.
Metadata fields are the same and also the book. Change is in Identification and Holding Information field. The duplication is mainly in the content from RMCA collections.

One book has 

Identification 
2bd5163e-6cce-4096-96b4-c2d3ceed8443
007582589
Holding Information 
Royal Museum for Central Africa
http://bhl.ait.co.at/index.php?form=display&oaiid=RMCA/2BD5163E6CCE409696B4C2D3CEED8443

---

the second book has 

Identification 
007582589
2bd5163e-6cce-4096-96b4-c2d3ceed8443
Holding Information 
Royal Museum for Central Africa
http://bhl.ait.co.at/index.php?form=display&oaiid=RMCA/000007582589

Connection with the exact feature need to be defined.

**Comment by janahoffmann** [comment]
@melitabirthaelmer FYI

**Comment by melitabirthaelmer** [comment]
This links are refering to the portal on AIT server and not to the portal on the NHM server. Is this correct?

**Comment by JiriFrank** [comment]
These links are included in the metadata on the NHM server.
Here is the link to the book anotation with metadata:
http://bhl-portal-dev.nhm.ac.uk/?q=node/20180 

and the second one

http://bhl-portal-dev.nhm.ac.uk/?q=node/20208

**Comment by bendao** [comment]
fixed on http://bhl-ait-dev.nhm.ac.uk and http://bhl.ait.co.at

**Comment by lobajuluwa** [comment]
Jiri pls confirm if this Issue still needs to go into the Test Core Release Milestone or not i.e it's presently Closed under the Development Core Release for August?
@JiriFrank

**Comment by JiriFrank** [comment]
@lobajuluwa
It cannot be tested right now, hopefully it is fixed. Will be reopen if not.

**Comment by lobajuluwa** [comment]
Okay that's fine. I've updated the milestone for the Nov Release so that it will be picked up once the testing process kicks off.
@JiriFrank
