### ISSUE TITLE
1.4.x Facet list (left column information) data and metadata fields

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#194]
Left column (facet list) in result provides incomplete data. This function is probably dependent on the schema and metadata fields. 

For example from searching with exact phrase “Von Martens” we will get 7 results. In left column are these categories:

Date – just one record 1866, even the books are form different years. This bug is related with the date bug  #171 and #183 
Type – 7 records for “Text”, I don’t know what means text, but in the results are 4 monographs (books), 2 articles and 1 whole volume. All these books have in metadata Type: text.

Language – 4 records for ger (German probably). Remaining 3 items in result list don’t have Language field in their metadata. Two of them are in English and one in German.

Data Provider – 7 records from three content providers working properly.

Rights – 7 records – 4 from europena portal, 2 from creativecommons licenses and 1 from europeana rights which seems ok.

Only 5 items could be shown under the category, how can I reach the others, when the results list if for example from 6 Data providers?

Connection with the exact feature need to be defined.

**Comment by janahoffmann** [comment]
I think we have to decide first how we want things to be diplayed before we report this as a bug. I don't think we will stick to this facet list anyway, especially as it is not based on the OLEF but ESE schema right now

**Comment by lobajuluwa** [comment]
Hi Jiri! Pls confirm if this bug fixed by AIT still needs to move to the Test Core Release process or not.

@JiriFrank

**Comment by janahoffmann** [comment]
@lobajuluwa
Mhhh. We cannot see whether this bug is fixed or not due to the lack of a testing platform. 
However, I want to draw your attention to my comment above. Now, all the requirements are defined (last UI Workshop minutes) and included in #62. 
So, if we keep this it can be a bug for #62, but closing it makes also sense (still adding it to the #62 description though).

**Comment by lobajuluwa** [comment]
As per above comments - bug is ytbc as fixed and hence I've Closed the issue and assigned it the Nov Release ready to be tested. Bug related to Issue #62

**Comment by JiriFrank** [comment]
The facet list will be rebuilt with additional functionalities. This bug could be closed; it is not related to the new facet list.
