### ISSUE TITLE
1.4.x Data Provider in Facet list

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#195]
In several cases in results shows data provider specific number of records according to result list. After clicking on this data provider in Data provider category, the number of results is different.

For example:
Simple search for – poisson afrique – have 46 items in result lists. The “Data Provider” in facet list shoving 3 content providers together with 46 records, which is right. But when you click for example on RMCA data provider which has 17 records, the new search result gives you just 7 records. 

NCB Naturalis which have 22 records give you after click on them just 12.

LANDOE which have 7 records give you after click just 5.

Sorting the results from facet list via category “Data Provider” will give you just 24 results from original 46.

Connection with the exact feature need to be defined.

**Comment by janahoffmann** [comment]
@jirifrank
See comment 1.4x Facet list... #194
However, the developers should explore this problem as it will also be present in the "new" facet list style.
