### ISSUE TITLE
1.4.x Right in Facet list

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#196]
The links in category “Rights” doesn’t work and reporting error.

Connection with the exact feature need to be defined.

**Comment by janahoffmann** [comment]
@jirifrank
see comment issue #194
but it should be fixed as it will be the same problem in the "new" facet list style

**Comment by bendao** [comment]
fixed: Special characters in any facet are handled properly.
http://bhl-ait-dev.nhm.ac.uk/
