### ISSUE TITLE
1.4.2 – Sort categories (Result list)

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#199]
The main search and also sort categories are: title, author, year and journal title (journal/monograph: information not yet available) – please change the categories. 

Please rename all the buttons and the names in the pull down menu. We need have a consistent set of metadata field names based on the OLEF schema. We can contribute. 

and lateron: taxon (as soon as services are implemented)

Related feature #62

**Comment by janahoffmann** [comment]
@lobajuluwa
I think we can close this bug as it does not refer to anything we will have in the portal anymore... The facet list categories are defined in #62.

**Comment by lobajuluwa** [comment]
Good! I'll close the bug. Milestone also removed
@janahoffmann
