### ISSUE TITLE
Portal – Download item in different qualities (high, low resolution, colour)

### ISSUE THREAD

**Issue by audreyhzhang** [gbhl/bhl-europe#20]
Download item in IMAGE format with different quality or resolution (high, low resolution, colour)

**Comment by leenamba** [comment]
Subtasks: #14, #15, #16

**Comment by janahoffmann** [comment]
This issue is included in CoR feature 3.2.3 and 3.2.4. I will set up the feature with a clear description soon.

**Comment by janahoffmann** [comment]
now issue #101
