### ISSUE TITLE
BHL-Europe book viewer used for Europeana does not display pages

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#200]
Problems with the display of content within the currently used BHL-Europe book viewer for Europeana has been noticed.

Here is a detailed error description with an example from our content provider RBGE:
- Content example: Notes from the Royal Botanic Garden Edinburgh, Volume XX, Number XCVI
- You can find the notes in Europeana here:
  http://www.europeana.eu/portal/record/08705/FEF2E25035C1A6EAA243535B5FF697A1BDFA0ED3.html?start=1&pageId=brd&query=Notes+from+the+Royal+Botanic+Garden+Edinburgh%2C+Volume+XX%2C+Number+XCVI&view=table&startPage=1#
- Using the link “view in original context” you reach this site:
  http://bhl.ait.co.at/index.php?form=display&oaiid=RBGE/947E92FFF61342EDA9EE6215E408D4B6
- To view the content you click now on the link to the book viewer after “Is shown by”: 
  http://bhle-dev-1.nhm.ac.uk/aip-preview/bookreader/index.php?var=../uk-rbge/NRBGEv1-23/Volume20/NRBGE_0020/NRBGE_0020_1939_0096#page/1/mode/1up
- Have a look at the pages. Pages are displayed fine until here:
  http://bhle-dev-1.nhm.ac.uk/aip-preview/bookreader/index.php?var=../uk-rbge/NRBGEv1-23/Volume20/NRBGE_0020/NRBGE_0020_1939_0096#page/60/mode/1up

From page 61 (book page numbering = page 43) the images are not displayed anymore until the end of the book:
http://bhle-dev-1.nhm.ac.uk/aip-preview/bookreader/index.php?var=../uk-rbge/NRBGEv1-23/Volume20/NRBGE_0020/NRBGE_0020_1939_0096#page/61/mode/1up
- The images are available on the NHM server, can be opened and displayed. The corresponding folder on the NHM server for this example is : 
  http://bhl-celsus.nhm.ac.uk/uploads/RBGE/NRBGEv1-23/Volume20/NRBGE_0020/NRBGE_0020_1939_0096/

This error occurs not only for this example. Here are some more examples:
- Notes from the Royal Botanic Garden Edinburgh, Volume XX – all parts
- Europeana: http://www.europeana.eu/portal/search.html?query=Notes+from+the+Royal+Botanic+Garden+Edinburgh%2C+Volume+XX%2C
- Notes from the Royal Botanic Garden Edinburgh: Vol. XXX, Number 2 (part number) - RBGE
- Europeana: http://www.europeana.eu/portal/record/08705/FCBF4C6B9B4A048DA7EFFCE69BC4378FC66511FB.html?start=1&pageId=brd&query=Notes+from+the+Royal+Botanic+Garden+Edinburgh%2C+Volume+XXX%2C+Number+2&view=table&startPage=1#
- BHL-Europe: http://bhl.ait.co.at/index.php?form=display&oaiid=RBGE/D137C39E1F0B448FA3832E374A1ECF1F
- BHL-Europe book viewer: http://bhle-dev-1.nhm.ac.uk/aip-preview/bookreader/index.php?var=../uk-rbge/NRBGEv24-46/Volume30/NRBGE_0030/NRBGE_0030_1970_0002#page/1/mode/1up
- First error page: http://bhle-dev-1.nhm.ac.uk/aip-preview/bookreader/index.php?var=../uk-rbge/NRBGEv24-46/Volume30/NRBGE_0030/NRBGE_0030_1970_0002#page/6/mode/1up

Impactos, vulnerabilidad y adaptación al cambio climático de la biodiversidad española, 2 (part number) , Flora y vegetación (part name) - CSIC
- Europeana: http://www.europeana.eu/portal/record/08704/E97CA96910DD7D0C8CCE512A3380AB172167624F.html?start=4&pageId=brd&query=csic&qf=PROVIDER:BHL%20Europe&view=table&startPage=1
- BHL-Europe : http://bhl.ait.co.at/index.php?form=display&oaiid=CSIC/0000000000000
- BHL-Europe book viewer- error page: http://bhle-dev-1.nhm.ac.uk/aip-preview/bookreader/index.php?var=../es-csic/CSIC001366637#page/99/mode/1up

<b>Please have a look at this issue with the highest priority as soon as possible, as this is already through Europeana online visible content displayed with errors. Our content providers are worried about the display of their own content through Europeana and the errors that occur with our currently used book viewer. </b>

**Comment by melitabirthaelmer** [comment]
Do we have any updates on the book viewer?

@grahamhrbge1670

**Comment by chris-sleep** [comment]
I've put a short term fix in place  - a couple of edits to the aip-preview bookviewer php and kicked the permission on the aip-preview data, however this is not a long term solution as the URL presented is on a development host which is due to shut down.

Issue should currently be resolved, but we will need to ensure that once the live AS and access components are in place with data ingested, that Europeana reharvests to pick up the changed content location once ready.
