### ISSUE TITLE
Preingest Tool does not generate clean METS files

### ISSUE THREAD

**Issue by zhengl** [gbhl/bhl-europe#201]
Bugs as followed:
1. LABEL in mets tag: dirty HTML from GUID generator;
2. OBJID in mets tag: dirty too;
3. The indice of IMAGE, JHOVE and TAXA start from 0, 1 or 2, but we need a fix value (1 would be the best).

**Comment by bendao** [comment]
Thanks, I'll drop you a note when its fixed (It seems my schedule will allow it 
by next week.)

best, 
odo

On Friday 02 September 2011 15:56:19 you wrote:

> Bugs as followed:
> 1. LABEL in mets tag: dirty HTML from GUID generator;
> 2. OBJID in mets tag: dirty too;
> 3. The indice of IMAGE, JHOVE and TAXA start from 0, 1 or 2, but we need a
> fix value (1 would be the best).

## 

---

| Odo Benda
| AIT Forschungsgesellschaft mbH
| Klosterwiesgasse 32/I | A-8010 Graz | AUSTRIA

## | Tel.: +43 316 835359-76 | Fax.: +43 316 835359-75

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
