### ISSUE TITLE
Preingest Tool Test: Submission doesn't work 

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#202]
<i><b>Test content: </i></b>
RMCA /Monographs/Anderson_Zoology of Egypt_vol_1_Reptilia
RMCA /Monographs/Anderson_Zoology of Egypt_vol_2_Mammalia

<i><b>Description:</i></b>
RMCA tried to submit the test content (Monday,05.09.2011). Two folders have been chosen ( see test content), but after pushing the button "submit selection for processing" nothing happened.
"Queue" was empty.
"Monitor" displayed other files from superuser, but not the own files.

Tried to submit several other files (Monographs & Journals e.g. Annals_RMCA_Zoology) but nothing happened here again.

@LarissaS

**Comment by bgol** [comment]
Both test contents worked on our machine submitted one after the other or together.
It may take awhile until the submissions will be shown if there are several of them.

<table>
<tr>
<th>Issue
<th>Test Content
<th>File amount
<th>Size
<th>Time
<th>Queue
<th>Monitor
<th>.aip
</tr>
<tr>
<td>PreIngest Tool Test: Submission doesn't work
<td>RMCA/Monographs/Anderson_Zoology of Egypt_vol_1_Reptilia
<td>572
<td>6 GB
<td>90 min
<td>Ok
<td>Ok
<td>Ok
</tr>
<tr>
<td>PreIngest Tool Test: Submission doesn't work
<td>RMCA/Monographs/Anderson_Zoology of Egypt_vol_2_Mammalia
<td>552
<td>6 GB
<td>93 min
<td>Ok
<td>Ok
<td>Ok
</tr>
<tr>
<td>PreIngest Tool Test: Submission doesn't work
<td>RMCA/Monographs/Anderson_Zoology of Egypt_vol_1_Reptilia AND RMCA/Monographs/Anderson_Zoology of Egypt_vol_2_Mammalia
<td>1124
<td>12 GB
<td>174 min
<td>Ok
<td>Ok
<td>Ok
</tr>
</table>

**Comment by melitabirthaelmer** [comment]
Second test on 15.09.2011:

<b><i>Test content: </b></i>
RMCA /Monographs/Anderson_Zoology of Egypt_vol_1_Reptilia
RMCA /Monographs/Anderson_Zoology of Egypt_vol_2_Mammalia
Monographs/Eberstaller_Stirnhirn/

<b><i>Description:  </b></i>
Resubmission of RMCA test content from first test and one new monograph. This time it was displayed in Queue and Monitor. AIP folder has been created.

**Comment by melitabirthaelmer** [comment]
Third test on 16.09.2011

<b><i>Test content:</b></i>
Annals_RMCA_Zoology/serie_1_fishes_reptiles_amphibians/vol_1/Boulenger_Poissons nouveaux
Monographs/Barns_An African Eldorado
Monographs/Burdo_Les Belges

<b><i>Description:</b></i>
Submission of new test content. However, submitted content during third test was not displayed neither in Queue nor in Monitor. Queue displayed 7 records of LANDOE. Monitor displayed parts of test content from second test on 15.09.2011 (RMCA /Monographs/Anderson_Zoology of Egypt_vol_2_Mammalia). No AIPs have been created for content submitted during third test.

See also screenshots: <i>RMCA-Test content 3-Queue.pdf</i> & <i>RMCA-Test content2-3-Monitor.pdf </i>at https://bhl.wikispaces.com/Preingest+Test

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
