### ISSUE TITLE
Preingest Tool - Footer

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#203]
There is following copyright information stated in the footer of the pre-ingest tool:

Copyright © ait.co.at - BHL-Europe PreIngest Tool

**Comment by melitabirthaelmer** [comment]
@parmelia-michaela

**Comment by bgol** [comment]
Standard license text (URL) for all BHL-E components requested.

**Comment by chris-sleep** [comment]
The copyright in the footer is correct, the full licence including conditions of use is found in the embedded licence file in the source, which can be seen at http://code.google.com/p/bhl-bits/source/browse/trunk/bhl-e/pre-ingest/PreIngest/LICENSE
