### ISSUE TITLE
Preingest Tool Test: Monitor - Feedback to user is missing [Usability]

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#204]
<b><i>Test content:</b></i>
RBGE/VOC

<b><i>Description:</b></i>
User logged in to the Pre-Ingest tool and followed the instructions (BHL-E-PREINGEST_ FOR CP.pdf at https://bhl.wikispaces.com/Preingest+Test) using the Test content (RBGE/VOC), selecting eng for OCR.
After submitting, user checked the "Monitor" section of the Pre-ingest tool. 
See screenshot : Pre-Ingest_RBGE_Monitor1.pdf  at https://bhl.wikispaces.com/Preingest+Test

User is not sure what he/she should be looking out for to alert him/her for any problems.

<b><i>Problem: </b></i>
No concrete and understandable feedback is given to the user, if there are any problems with the submitted content or if it the pre-ingest was successful.

<b><i>Impact: </b></i> User is confused. This is a critical issue as it may lead to canceling the action of submitting further content

@grahamhrbge1670

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
