### ISSUE TITLE
Preingest Tool Test: Submission - inconsistency  tool vs. instruction

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#205]
<b><i>Related Issue: </b></i>#204

<b><i>Test content:</b></i>RBGE/VOC

<b><i>Description:</b></i>
User submitted test content. After #204 user switched to "Submissions" and find out that an aip file had been created attached to the VOC file.

See screenshot:  PreIngest_RBGE_Submissions_aip1.pdf  at https://bhl.wikispaces.com/Preingest+Test

Checking through this against what the aip folder should contain (BHL-E-PREINGEST_ FOR CP.pdf page 13 at https://bhl.wikispaces.com/Preingest+Test), user noted that the following files are not included:

xml.smt.xml
tif.txt
tif.taxa.xml
tif.jhove.xml

This files are included, but not mentioned in the document given out:
mdb.jhove.xml
mrc.jhove.xml

<b><i>Comment/Question mentioned by the user:</b></i>
"Should I expect these files to have been created?"

<b><i>Impact: </b></i>User is confused and does not know what exactly should be created or not and if everything has been processed.

@grahamhrbge1670

**Comment by grahamhrbge1670** [comment]
On testing further with RBGE content I think that one reason these files were missing was my misubnderstanding of the workflow.  I had not ticked the tiff boxes for the content and so naturally no
tif.txt
tif.taxa.xml
tif.jhove.xml  

files appeared.  However I'm still not sure what is happing to xml.smt.xml file, as I re-run the ingest with different content this morning and this file is still not appearing.

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
