### ISSUE TITLE
Preingest Tool Test: View created files within aip folder

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#206]
<b><i>Related Issue: </b></i>#204 , #205

<b><i>Test content:</b></i> RBGE/VOC

<b><i>Description:</b></i>
User submitted test content.
Detailed description see #204, #205
User tried to open files within created .aip folder (under register "Submissions") e.g. VOC.mets.xml to check how the metadata looks after the processing.

See also screenshot: PreIngest_RBGE_Submissions_aip1.pdf  at https://bhl.wikispaces.com/Preingest+Test

<b><i>Impact: </b></i>User confused. 

@grahamhrbge1670

**Comment by grahamhrbge1670** [comment]
Not sure if I was following the workflow correctly, but I was trying to see if I could open files that would show data as it is presented in  Figure 3-11 and Figure 3-12 in the Content Ingesting Process Technical Note.

**Comment by grahamhrbge1670** [comment]
Apologies, closed in error.

**Comment by melitabirthaelmer** [comment]
<b><i>Question:</b></i>
Is this functionality disabled? According to the documentation it should be possible p.15  BHL-E-PREINGEST_ FOR CP.pdf at https://bhl.wikispaces.com/Preingest+Test

<b><i>Suggestion:</b></i>
Provide a possibility for the user to check the mapped metadata after the content has been processed by the pre-ingest tool.

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
