### ISSUE TITLE
Pre-Ingest Testing: OCR-Language selection

### ISSUE THREAD

**Issue by grahamhrbge1670** [gbhl/bhl-europe#207]
How are the entries, lang and language in the OCR-Language selector, to be used.  I cannot match them to anything in the LC MARC Code List for Languages, but am sure they must be there for a reason, are they defaults for unspecified languages ?

**Comment by bendao** [comment]
They are indeed defaults, but they should not show up in the list. That's a glitch that will be fixed.

**Comment by melitabirthaelmer** [comment]
<b><i>Description:</b></i>
Material from a content provider is in several languages. For instance, one book from UH-VIIKKI may be written in three different languages. Typically there are in German, Swedish and Finnish.

What should be chosen here from the drop-down list? Is there a possibility to choose multiple languages?

@LarissaS
@parmelia-michaela
@tiinaonttonen

**Comment by bendao** [comment]
Multiple languages in the same book are not supported. It would require the information about begin and end of each language. This however is not available.

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
