### ISSUE TITLE
Preingest Tool Test: Selection of content

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#210]
<b><i>Description:</b></i>
Currently content can only be selected by selecting each available folder. 
For content providers providing a huge amount of content (e.g. LANDOE, HNHM) this is very time consuming and not manageable. For instance LANDOE would need to select over 3000 folders manually to be able to submit all their content  at the moment.

<b><i>Suggestion:</b></i> 
Provide a possibility to select the available content in one step for those CPs who would like or need to use such a functionality. 

@parmelia-michaela

**Comment by melitabirthaelmer** [comment]
During the test we realized that even for a content provider with a smaller amount of content it is not possible to invest a lot of time only for the process of submission.
Therefore this way of submission is not doable:
"It is important to choose the folder in which the files are stored, not the parent directories."  <i>p.8  BHL-E-PREINGEST_+FOR+CP.pdf </i> at https://bhl.wikispaces.com/Preingest+Test

<b><i>Suggestion:</b></i>
Provide a possibility to select also only the parent directory in addition to the suggestion above.

@grahamhrbge1670

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
