### ISSUE TITLE
Preingest Tool Test: Display of available content slow

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#211]
<b><i>Description</b></i>: Clicking on submission it takes for content providers with a huge amount of content a long time to display all their content.
See also screenshot:  Submit-Loading slow.pdf at https://bhl.wikispaces.com/Preingest+Test

<b><i>Possible explanation: </b></i>
According to @chris-sleep a reason might be that the Pre-ingest tool for testing is deployed on a shared development machine. For the future production and testing environments the pre-ingest tool will be deployed on machines solely for pre-ingest. 

<b>Please keep this as an open issue until we see how it runs on machines solely for the preingest.</b>

@parmelia-michaela

**Comment by parmelia-michaela** [comment]
well I do not know if it was said that the machine will be solely for the PreIngest tool but in future this should be faster right?

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
