### ISSUE TITLE
gsearch installation

### ISSUE THREAD

**Issue by leenamba** [gbhl/bhl-europe#212]
- Re-install gsearch and integrate with fedora on bhl-int1.nhm.ac.uk
- Commit gsearch scripts to github

References:
- https://wiki.duraspace.org/display/FCSVCS/Generic+Search+Service+2.2

**Comment by zhengl** [comment]
Done, please find the XSLT scripts used by Gsearch in data-management folder.

**Comment by leenamba** [comment]
@akohlbecker
need to test to see if compatible with solr 3.3

**Comment by akohlbecker** [comment]
see http://groups.google.com/group/islandora/browse_thread/thread/b23008bb780d40f8?pli=1 for possible problems

**Comment by akohlbecker** [comment]
in the following I am using a ssh tunnel at port 58080 to connect to the tomcat instance on bhl-int1.nhm.ac.uk:8080:

at http://127.0.0.1:58080/fedoragsearch/rest?operation=browseIndex I get the following error message: 

Wed Sep 28 15:31:18 BST 2011 Connection error (is Solr running at http://localhost:8983/solr/core3/update ?): java.net.ConnectException: Connection refused

**Comment by audreyhzhang** [comment]
Solr Core3 for GSearch is running on port 8983 correctly now. 

If the same error message occurs, it can be solved by doing this:
---@bhl-int1:~/dev/apache-solr-3.3.0/example$ java -jar start.jar

**Comment by wkollernhm** [comment]
I re-opened the issue in order to be able to track the outcome of this.

**Comment by akohlbecker** [comment]
relying on the admin to always manually start solr is not an option, we need to have a start-up script in /etc/init.d/.
there is already such script on mandible.I think it makes sense to share init-script between the multiple servers
@chris-sleep , @leenamba:
so i suggest having a folder /mnt/nfs-demeter/dev/init-scripts  which will hold all init-scripts. The /etc/init.d/ will contain symlinks to the scripts in /mnt/nfs-demeter/dev/init-scripts. the same for testing and production.

**Comment by akohlbecker** [comment]
Currently we are running:

  "Fedora Generic Search Service Version 2.3 (September 2011) !!! PRERELEASE !!!"

the welcome page http://127.0.0.1:58080/fedoragsearch/ states gesearch 2.3 to be compatible with:
- Lucene 3.3 
- Solr 3.3

**Comment by akohlbecker** [comment]
test performed so far:
1. Browsing the indedex **OK**
2. Updating the index (http://127.0.0.1:58080/fedoragsearch/rest?operation=updateIndex) **NO ERROR** but also no documents are being indexed - to me it looks like no no documents are found in Fedora

**Comment by leenamba** [comment]
need to test with new solr+jetty

**Comment by chris-sleep** [comment]
need to update solr from 3.3
