### ISSUE TITLE
Preingest Tool Test: "Monitor" displays all submitted content - confusing

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#213]
<b><i>Description:</b></i>
The "Monitor" displays submitted content from all content providers. In the "Submission" a user can select only his/her own content to be submitted, which is desired in that way. However after submitting his/her own content, switching over to the registers "Queue" and "Monitor" the user is able to see the last 100 activities (processing one image file = 1 activity !) from all users. 
This list confuses the user, especially if he/she submitted content but content from another user is displayed in the Monitor view. From the point of view of a CP and usability, this is a critical bug.

See also screenshot: bug monitor view.pdf at https://bhl.wikispaces.com/Preingest+Test

<b><i>Suggestion:</b></i>
Display in the "Queue" and "Monitor" view only the activities of the user logged in. For a content provider it is only important to see if the own content is processed or not.

Save the current "Monitor" as a detailed list with all submitted content in a log file which is only visible to the admin of the tool or to the technical team, but not to content providers.

@parmelia-michaela
@LarissaS
@grahamhrbge1670

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
