### ISSUE TITLE
Preingest Tool Test: Content submitted - AIPs empty

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#214]
<b><i>Related Issues:</b></i> #202, #213
<b><i>Test content:</b></i> diverse content from LANDOE
<b><i> Note: </b></i> Metadata harvesting over OAI-PMH

<b><i>Description:</b></i>
- <b><i>Test on 06.09.2011 </b></i>

Content submitted at the same time: 1, 10, 100, 101, 102, 11, 114
Content visible in the "Queue" and "Monitor" as "SUBMITTED", but not as "DISPOSED".
One day later on the 07.9.2011 nothing changed, still the same is displayed.

Note: Content has been submitted on 06.09.2011 at the same time. Anyhow, somehow content from another user (RBGE) appeared in between the submitted content from LANDOE. Is this the way it should be?
- <b><i>Test on 07.09.2011:</b></i>

Further content submitted:107, 108, 109, 111, 113, 125, 26837, 26838, 26839, 26840, 26841, 26842, 26843, 26844, 26845, 26846, 26847, 26848, 26849, 30513, 30514, 30515, 30516, 30518, 30519, 30520, 30521, 30523, 30524, 30525, 30526, 30530, 30576, 9, 9036
Note: OCR language has not been selected because LANDOE delivers own OCR within their pdfs.

After submitting these new folders, the content from RBGE in the "Monitor" was gone and own content was diplayed as "SUBMITTED".
After 10 minutes, still the same display.
After 15 minutes, still the same display.
After 25 minutes, still the same display.

There is no "DISPOSED" mentioned in the "Monitor". User assumes selected files have not successfully passed the Preingest.
- <b><i>Test on 08.09.2011:</b></i>

"Monitor" displays again only "SUBMITTED"  and no "DISPOSED" in front of the content.

Having a look at all files submitted in the "Submission" tab, an AIP subfolder has been created for each submitted folder expect folder 9. However, all these AIP subfolders are empty.
- <b><i>Test on 12.09.2011:</b></i>

All folders dissapeared from the "Queue" and "Monitor". AIP subfolders still empty.

<b><i>Conclusion: </b></i> Tool operates in unreasonable ways and is very confusing. User has no feedback if content has been successfully preingested or not.

@parmelia-michaela

**Comment by melitabirthaelmer** [comment]
<b><i>Test content: </b></i> FI-Hb/FI-Hb_301519_Memoranda_Societatis (UH-Viikki),
all volumes

<b><i>Description:</b></i>
Same issue as LANDOE. AIP folders created, but empty.

<b><i>Note:</b></i>
Difference:Metadata is uploaded to the NHM server and is not provided by OAI-PMH for UH-Viikki.

@tiinaonttonen

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
