### ISSUE TITLE
Preingest Tool Test: Documentation Feedback - Content upload

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#215]
Add more explanations to chapter 3.1.
- Those users who don't use WebDav as their FTP client might be confused. Add an explanation that WebDav is only a suggestion and we made good experiences with it, but of course other FTP clients might work as well, such as ...
- User might ask if his/her FTP client needs to run while using the Preingest tool.
  Mention that the FTP client on the user side is not directly connected to the Preingest and the Preingest tool can be used independently.

@parmelia-michaela
@grahamhrbge1670
@LarissaS

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
