### ISSUE TITLE
Preingest Tool Test: Monitor view - too many details

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#216]
<b><i>Related Issues:</b></i> #204, #213

<b><i>Description:</b></i>

Submission is on folder level, Monitor is on file level. The Monitor view is too detailed. Currently user needs to check if there is a "DISPOSED" in front of each file (= e. g. 1 page) within a submitted folder. Imagine you have a monograph with more than 700 pages or you submit all your available content. This is very time consuming and not practicable. The current view might be good for a preingest admin or a technical team, but very confusing for a content provider. 

<b><i>Suggestion:</b></i>
Give positive or negative feedback for the submitted content on submitted folder.

@parmelia-michaela

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
