### ISSUE TITLE
Preingest Tool Test: Monitor/Queue view - "date"/"displaydate" unclear

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#217]
<b><i>Description:</b></i>

User wondered what "date" in Queue and "displaydate" in Monitor means. After some time user concluded that this might be the time when he/she pressed the button "Submit selection for processing"

<b><i>Suggestion:</b></i>
Use a more meaningful word for "date" &"displaydate". If it is really the date when a user submits the content, then you could use "date of submission" or "submission date"...

@parmelia-michaela

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
