### ISSUE TITLE
Preingest Tool Test: Change register term "Submission"

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#219]
<b><i>Related issue: #218</b></i>

<b><i>Description:</b></i>
In #218 there is the suggestion to create an additional tab called "Submitted Content". 
The name of the first register "Submission" could be misleading. We show the available content that can be submitted which is the content of an user. However "Submissions" could also mean, the already submitted content.

<b><i>Suggestion:</b></i>
Change "Submission" to "My Content"

@LarissaS
@parmelia-michaela
@tiinaonttonen
@grahamhrbge1670

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
