### ISSUE TITLE
Preingest Tool Test: Submission of content with OCR

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#220]
<b><i>Related issue: #207, #214</b></i>

<b><i>Question:</b></i>
What should be chosen for content that already has OCR?

Is the user expected to choose the language of the already available OCR within the drop-down list? Or should it be left empty? Or should the user choose the language, but just deactivate the checkbox "detect"?

@LarissaS
@parmelia-michaela
@tiinaonttonen
@grahamhrbge1670

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
