### ISSUE TITLE
Preingest Tool Test: "Submit selection for processing" button

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#222]
<b><i>Description:</b></i>
Two "Submit..." buttons confuses the user. Why is there one beneath the OCR selector and one at the foot of the screen?

@grahamhrbge1670
@LarissaS
@parmelia-michaela
@tiinaonttonen

**Comment by bgol** [comment]
The two buttons do have the same functionality. It's just for user convenience. If a folder with lots of files is opened, the bottom button will scroll out of the window. We added the top button so the user doesn't have to scroll down.

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
