### ISSUE TITLE
Preingest Tool Test: Re-submitting content & Feedback

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#223]
<b><i>Question:</b></i>
How can content be re-submitted?  
For instance: 
a) a content provider improves/corrects the metadata of a already submitted material and would like to re-submit it
b) issues with image files occured  (e.g missing pages, corrupted files, ) and content provider re-uploads the content to the BHL-Europe server. 

What happens to the aip folders for already submitted content?

<b><i>Additional suggestion:</b></i> 
User expects feedback from system,e. g. something like "Folder XXX has already been submitted on YY.XX.ZZ. Are you sure you want to re-submit it?" 

@grahamhrbge1670
@parmelia-michaela
@tiinaonttonen
@LarissaS

**Comment by bgol** [comment]
To re-submit a content you just have to submit it again after you uploaded the new/changed files into the same folder. Everything will be done again **except** the NOID and OCR for allready processed image-files. If you want to re-OCR an image file you have to delete the corresponding .txt file in the aip folder before re-submitting. If you delete the whole aip folder everything will be done again including a new ID.

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
