### ISSUE TITLE
Preingest Tool Test: Content is not processed in strict numerical sequence order

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#224]
<b><i>Description:</b></i>
When looking at the files as they were being processed for OCR, user noticed that the image files were not being taken in strict numerical sequence order. 
See also screenshot: Monitor-mixed order.pdf at https://bhl.wikispaces.com/Preingest+Test

Does this influences the OCR result or is this just an internal workflow of Tesseract or the pre-ingest tool?

However, user is confused about that. 

<b><i>Suggestion:</b></i>
If there is a reason for that, mention it in the documentation for the tool and let the reader know that it is the internal workflow, but does not influences the results...

@grahamhrbge1670
@LarissaS
@parmelia-michaela
@tiinaonttonen

**Comment by bgol** [comment]
It's just the internal workflow. The preingest can handle more than one OCR at a time. If one is finished the next one will be processed, eg: we have 4 queues: 1, 2, 3, 4 -> 3 is finished -> 1, 2, 5, 4 -> 1 is finished -> 6, 2, 5, 4, and so on.

**Comment by lobajuluwa** [comment]
Issue relates to previous PI tool. New build now in progress
