### ISSUE TITLE
specify UI for simple and advance search

### ISSUE THREAD

**Issue by akohlbecker** [gbhl/bhl-europe#225]
Specify the User interface for simple and advance search:

Suggestion for **simple search**:

simple search is without Boolean operators. This is restricted to advanced search. 
- text field for **query string**, will not understand solr query syntax (http://wiki.apache.org/solr/SolrQuerySyntax)
- check-box **exact**, will search for the exact terms
- check-box **phrase**,  will search for the full phrase of all given terms

Suggestion for **advanced search**:
- ???

**Minutes from UI Workshop calls:**
-  [1st UI-Workshop Sept 29 2011](https://bhl.wikispaces.com/Septermber+29%2C+2011+1st+UI-Workshop+Call)
-  [2dn UI-Workshop Oct 07 2011](https://bhl.wikispaces.com/October+7th%2C+2011+2nd+Portal+UI-Workshop+Call)
-  [3rd UI-Workshop Oct 27 2011](https://bhl.wikispaces.com/October+27%2C+2011+3rd+Portal+UI-Workshop+Call)

**Comment by akohlbecker** [comment]
@JiriFrank @lobajuluwa @janahoffmann : By now am assigning this task to Jiri, please feel free to further distribute and to share it with others.

**Comment by akohlbecker** [comment]
see http://design.mydev.cz/BHLE/

**Comment by JiriFrank** [comment]
The definition will be in agenda for the Tuesday workshop.

**Comment by akohlbecker** [comment]
@JiriFrank i think it would be good to put the outcome of the last two workshops to here, what do you think?

**Comment by lobajuluwa** [comment]
Hi Jiri! Can you pls confirm whether this is a new feature request.
@JiriFrank
@JanaHoffmann

**Comment by JiriFrank** [comment]
I will put the minutes from the UI workshops on the Wiki and I will put here the link. Done, see the desctiption.
