### ISSUE TITLE
Vocabulary

### ISSUE THREAD

**Issue by fwelter** [gbhl/bhl-europe#23]
I would need some basic information on the "controlled" vocabulary we should use here. Perhaps we can open up a page on the wiki where certain basic things can be equipped with names that are understood by all members of the team. It is important to make sure that we are talking about the same things.

From my experience in AnimalBase programming I am currently using the following terms:

Portal = the web interface for the database

Terms used for portal stuff

Portal pages = static pages provided by the portal

Search page = the entry page/query page/front page of the portal with the search function: www.biodiversitylibrary.org

Query = query submitted to the search page

Title homepage = the page with the detailed information on the title (in AnimalBase = reference homepage): http://test111.ait.co.at/?q=node/12941&language=en

Item page = BHL-US current portal's item pages: http://www.biodiversitylibrary.org/item/47632

Bibliography page = BHL-US current portal's item pages: http://www.biodiversitylibrary.org/bibliography/13288

Journal homepage =  a summary page for an entire serial run of a periodical, listing (1) the names of the journal, (2) the year, (3) the volume number: http://www.landesmuseum.at/biophp/de/annalen.php

Terms used for bibliographic stuff

Author = creator, the person(s) who was/were made responsible for writing the content of a publication

Title = the title of a monograph or a journal article

Year = the bibliographically relevant date/year of publication of the monograph, journal article or journal volume

Journal = periodical, designed/thought as subsequently issued volumes with usually several articles by various authors, the articles themselves do not form a closed single entity (example: Journal of Applied Biology, issued by Elsevier Science); not a series of monographs 

Multivolume work = a series of monographs with its content forming a single entity, usually by one author, usually with the same title (example British zoology, volumes 1-4, by Thomas Pennant); not a journal

Journal title = the title of a journal

Serial run = all volumes from the first to the last issued volume of a journal or a multivolume work

**Comment by janahoffmann** [comment]
This should be also included in the BPG. I think there is a glossary for used terms in BHL-Europe already (more focussed on technical terms): https://bhl.wikispaces.com/BHL+Europe+glossar 
Who is the right person to be assigned to this task?

**Comment by akohlbecker** [comment]
after many months of using this system we all are having a good idea on the meaning of all important terms used herein.
So I will close this issue.
