### ISSUE TITLE
File Submission Guidelines: Are Umlaute e. g. ä permitted?

### ISSUE THREAD

**Issue by melitabirthaelmer** [gbhl/bhl-europe#234]
Can a folder or filename contain Umlaute e. g. ä ?

<i><b>Example: </i></b> Folder name "Luonnon ystävä"

Should it be changed to "Luonnon ystava"?

@tiinaonttonen
@wkollernhm
@mehrrath

**Comment by mindcatch-com** [comment]
for now i dont know with which native language support the file servers 
drives are mounted but i would always strongly recommend NOT to
use use "Umlaute" even if the servers are mounted with e.g. utf-8 
charsets which would support that ...

the only thing what would be problematic is when the file or folder names
become part of the final content what i can not 100% preclude but not 
assume.

@wkollernhm

**Comment by mmalicky** [comment]
please change to:

<i><b>Example:</i></b>  Folder name "Luonnon yst&auml;v&auml;"

(HTMLENCODING)

Am 13.10.2011 11:53, schrieb melitabirthaelmer:

> Can a folder or filename contain Umlaute e. g. ä ?
> 
> <i><b>Example:</i></b>  Folder name "Luonnon ystävä"
> 
> Should it be changed to "Luonnon ystava"?
> 
> @tiinaonttonen
> @wkollernhm
> @mehrrath

## 

Dipl.-Ing. Michael Malicky
Biologiezentrum/Oberösterreichische Landesmuseen
Johann-Wilhelm-Klein Str. 73
4040 Linz
Mobil: +43 (0)664 6007252333

## 

Das Sonnentor - Bolivien und seine Schaetze
Schlossmuseum Linz
17. Okt. 2011 bis 18. Maerz 2012
Eroeffnung: So. 16. Oktober 2011, 11.30 Uhr
www.schlossmuseum.at

**Comment by mindcatch-com** [comment]
you can try: http://www.htmlescape.net/htmlescape_tool.html

@mmalicky

we should think of a change that requirement in future?
it is not suitable that end users have to encode all their filenames manually
to a html encoded string containing the operators & and ;

is there a client side ingest preparation tool planed which could solve this 
issue?

**Comment by mmalicky** [comment]
of course this should not be done manually, but it should be done on the 
data provider side, there are simple functions in programming languages 
for this task, e.g. htmlspecialchars in php

Am 13.10.2011 15:06, schrieb mehrrath:

> you can try: http://www.htmlescape.net/htmlescape_tool.html
> 
> @mmalicky
> 
> we should think of a change that requirement in future?
> it is not suitable that end users have to encode all their filenames manually
> to a html encoded string containing the operators&  and ;
> 
> is there a client side ingest preparation tool planed which could solve this
> issue?

## 

Dipl.-Ing. Michael Malicky
Biologiezentrum/Oberösterreichische Landesmuseen
Johann-Wilhelm-Klein Str. 73
4040 Linz
Mobil: +43 (0)664 6007252333

## 

Das Sonnentor - Bolivien und seine Schaetze
Schlossmuseum Linz
17. Okt. 2011 bis 18. Maerz 2012
Eroeffnung: So. 16. Oktober 2011, 11.30 Uhr
www.schlossmuseum.at

**Comment by mindcatch-com** [comment]
that is clear but i think we speak about the time of the file upload itself

i thought melitabirthaelmer wants to know if he/she can upload files from local 
with umlaute and you answered no he/she should convert them instantly when/before
uploading....

besides when the server files system mount is not of an extendet charset type
you can forget the umlaute and we will hardly be able to recover them in 
postprocessings on the data provider side.

**Comment by melitabirthaelmer** [comment]
However, we should keep in mind that content providers are in the majority of cases non-technicians and have no programming skills. 

We should provide them with a tool  or a script that is able to do this automatically. Would it be possible to have this function implemented in the pre-ingest tool?

**Comment by mmalicky** [comment]
suggestion:

Step 1: When doing pressing the ingest button: ERROR: Your metadata 
contains non standard charcters, please:
Step 2: Use tool XY for converting your data to correct format (see FAQ)
Step 3: Still no idea ;-) contact your local IT Helpdesk
Step 4: Your local Helpdesk is offline, please contact BHL Helpdesk, 
ingest management

Am 13.10.2011 16:55, schrieb melitabirthaelmer:

> However, we should keep in mind that content providers are in the majority of cases non-technicians and have no programming skills.
> 
> We should provide them with a tool  or a script that is able to do this automatically. Would it be possible to have this function implemented in the pre-ingest tool?

## 

Dipl.-Ing. Michael Malicky
Biologiezentrum/Oberösterreichische Landesmuseen
Johann-Wilhelm-Klein Str. 73
4040 Linz
Mobil: +43 (0)664 6007252333

## 

Das Sonnentor - Bolivien und seine Schaetze
Schlossmuseum Linz
17. Okt. 2011 bis 18. Maerz 2012
Eroeffnung: So. 16. Oktober 2011, 11.30 Uhr
www.schlossmuseum.at

**Comment by wkollernhm** [comment]
We cannot provide a tool at the PI-stage in order to do the conversions because we are mainly aiming at problems during the upload (e.g. if  the file-system doesn't support the characters within the folder names).

Spaces & Non-ASCII characters should be avoided (this is also documented in the file submission guidelines). If the upload works and the directory/file-names do show up correctly on the server the user will be able to process the  data.
