### ISSUE TITLE
1.4.1b - Indicate content type (Result list)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#239]
Content type should be indicated by icons
Defined content types: monograph, article, journal (Volume) 

Precondition:
Icons for content type have to be designed. 
Annotation of content type.

Connected issues: #61

**Comment by janahoffmann** [comment]
@lobajuluwa
Please assign to a WP5 person and a developer.

**Comment by lobajuluwa** [comment]
@JiriFrank

Hi Jiri can I assign this issue to Jan/IT4Care?

**Comment by parmelia-michaela** [comment]
Be aware that there may be literature which cannot be asigend to monograph, article, journal (Volume) . E.g. Newsletters,...perhaps an additional button is needed for literature being in any other format than monograph, article, journal (Volume)

**Comment by janahoffmann** [comment]
Good call Michaela. What do you think about naming the third icon 'Serial' meaning all sequential publications under a common title like journals and newsletters...Ich would like to avoid to many icons. Another solution would be to invent an 'others' icon for the content that cannot be put in any of the categories listed above. 
@parmelia-michaela

**Comment by parmelia-michaela** [comment]
Didn't we talk in The Hague about an "others" icon? I would prefer to make an "others" icon because if you have any other kinds of publications you can put them in there and like newsletters, posters, they do not necessarily have to be a sequential publication.
@janahoffmann

**Comment by janahoffmann** [comment]
@parmelia-michaela
That is right, but was related to the facet list. This was related to the information declared as  'unkown' in general.
@jirifrank
Jiri, can you ask Pavel to also design the unkown icon for the content type?

**Comment by JiriFrank** [comment]
@parmelia-michaela
@janahoffmann
The Icons for Monograph, Article and Journal/Volume are done and will be implemented tomorrow. There is no problem to have fourth icon corresponding to unknown content (Others) – something with question marks, but I am wondering how many of these type of content we have? The newsletter is for me the same as a journal or serial, because it has volumes and even articles. We have posters in the content? The requirement for the fourth icon was sent to Pavel.

**Comment by parmelia-michaela** [comment]
@janahoffmann
@JiriFrank
this was just a suggestion
nevertheless I think that the categories should be consistent in the Portal

**Comment by JiriFrank** [comment]
@parmelia-michaela
@janahoffmann
Michaela it was a good point. It will be ok to have the fourth (actually fifth) type of content according to the content type in facet list.

Journal/Serial
Volume
Article
Monograph
Unknown (group of all others)

The icon for unknown content will be done till the end of this week.

**Comment by parmelia-michaela** [comment]
:-)

**Comment by JiriFrank** [comment]
Design of content type icons is done and integrated.

**Comment by chris-sleep** [comment]
Implemented, but needs other content types in test data to test.

**Comment by parmelia-michaela** [comment]
working on test data...

**Comment by JiriFrank** [comment]
1.4.1b - Indicate content type (Result list)

COR number: 1.4.1b
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Description:

Content type should be indicated by icons
Defined content types: monograph, article, journal (Volume)

There is on the testing platform only the content type monograph right now.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment]
If the icon "green books" on the left is the special icon for books (and the non-existing will differ), then it works.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 16:46
An: Hand, Ralf
Betreff: Re: [bhle] 1.4.1b - Indicate content type (Result list) (#239)

1.4.1b - Indicate content type (Result list)

COR number: 1.4.1b
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Description:

Content type should be indicated by icons
Defined content types: monograph, article, journal (Volume)

There is on the testing platform only the content type monograph right now.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
1.4.1b - Indicate content type (Result list)

COR number: 1.4.1b
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Description:

Content type should be indicated by icons
Defined content types: monograph, article, journal (Volume)

There is on the testing platform only the content type monograph right now.

@AntonioGVH
@fwelter
@LarissaS

**Comment by HenningScholz** [comment]
So I assume we can not test this, without having different types.

---

Dr. Henning Scholz 
Museum für Naturkunde | Leibniz Institute for Research on Evolution and Biodiversity at the Humboldt University Berlin
Invalidenstraße 43 | D-10115 Berlin | Germany 
Tel.: +49-30-2093-8864 | Fax: +49-30-2093-8868 
Email: henning.scholz@mfn-berlin.de
http://www.naturkundemuseum-berlin.de/ / http://www.bivalve.de 
http://www.bhl-europe.eu / http://www.biodiversitylibrary.org/
BHL-Europe in Europeana:  bit.ly/BHLE-Europeana

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 16:46
An: Scholz, Henning
Betreff: Re: [bhle] 1.4.1b - Indicate content type (Result list) (#239)

1.4.1b - Indicate content type (Result list)

COR number: 1.4.1b
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Description:

Content type should be indicated by icons
Defined content types: monograph, article, journal (Volume)

There is on the testing platform only the content type monograph right now.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AntonioGVH** [comment]
There is a lot of information on the result list, very useful and with good display.
But I do not find the 'content type.'

Quoting JiriFrank:

**Comment by JiriFrank** [comment]
Is working. There is for now just one content type monograph/book which is represented properly by monograph icon.

Other icon are in place, but cannot be tested without more content type. Will be tested again with more content.

@AntonioGVH 
@HenningScholz 
@RalfH 

Content type icon needs to be slightly modified according to copyright. AI Me.
