### ISSUE TITLE
Portal requirement: must work in old browsers

### ISSUE THREAD

**Issue by fwelter** [gbhl/bhl-europe#24]
The portal website should be displayed in a high number of different browsers without bugs or distorted positions of text and images. It should be displayed correctly in old browsers, more than usually acknowledged, because many users working in the field of biodiversity research are poor institutions with minimum budgets and poor people with a below-average income and work with old systems (not only in 3rd-world countries where universities recycle computers that are not used any more in the rich countries). 
I belong myself to such a group of persons/institutions, we have 5 computers here; one from 1997 (updated 2000), one from 2001 (updated 2003), two from 2004 and the youngest from 2007. I can test various different browsers.

Use the OCLC web portal formats if it is allowed to use them.
Examples:
http://gso.gbv.de
http://opac.sub.uni-goettingen.de
http://swb.bsz-bw.de
http://grib.gbv.de

These very successful web portals are correctly displayed in all the browsers I know, including the oldest browser Inter Explorer 5.0 from 1997.
It seems that these successful systems were designed for exactly the purposes eplained above. It is well known that most public libraries and biodiversity research institutions in most countries do not have the budget to update their computer systems every 3 years!

The present site
http://test111.ait.co.at
is absolutely distorted on the older browsers, not a single word is shown.

The present BHL-US website
http://www.biodiversitylibrary.org
is displayed with all text and image content in the IE Expl 5.0 (1997), more or less correctly. Only the viewer for the digitised content does not work (pages remain blank, probably because JPG2000 is used).

**Comment by janahoffmann** [comment]
This is not a feature but a suggested requirement for the BHL-Europe portal. It will be forwarded to the WP3 management group to be discussed in a next TechCall. 
 @fwelter

**Comment by janahoffmann** [comment]
Please discuss and assign this issue/ requirement to the appropriate person. It is not a 'real' feature to my understanding.
@chris-sleep
