### ISSUE TITLE
Strip or escape any disallowed characters from solr queries

### ISSUE THREAD

**Issue by akohlbecker** [gbhl/bhl-europe#247]
Using the solr query syntax is not permitted neither in simple nor in advanced search, thus these should be stripped or escaped from the solr queries in drupal.

**Comment by wkollernhm** [comment]
Why is this not permitted? I included a function which escapes those special characters according to: http://lucene.apache.org/java/2_9_1/queryparsersyntax.html#Escaping%20Special%20Characters

I guess this should be sufficient?

**Comment by akohlbecker** [comment]
Escaping them is perfect, so we should no ,longer get any errors due to characters reserved by the query syntax. 
I guess we can close this issue then.

**Comment by akohlbecker** [comment]
The original issue description was not well chosen, since escaping these characters also solved the problem in #197.
So  I am correcting this.

**Comment by wkollernhm** [comment]
okay so this issue is already fixed and I will close it.
