### ISSUE TITLE
Portal - creating a journal homepage

### ISSUE THREAD

**Issue by fwelter** [gbhl/bhl-europe#25]
A journal homepage is needed, equivalent to the bibliography page in BHL-US. Journal homepage should only be provided for journals (see issue #23, vocabulary).

= a summary page for an entire serial run of a periodical, listing 

(1) the names of the journal (some journals have different names in different years)
(2) the year, 
(3) the volume number (with link to the corresponding title homepage for the journal volume)
(4) a link to the digitised version of the journal volume

Example: 
http://www.landesmuseum.at/biophp/de/annalen.php
(this example contains no direct links to digitised versions (4), only a link to a good example for a title homepage for the journal volume (3))

**Comment by janahoffmann** [comment]
This issue is included in CoR feature 1.2.6 and 1.4.3. The comment will be forwarded to the test manager Jiri Frank.
@fwelter
@jiriFrank

**Comment by janahoffmann** [comment]
now issue #63
