### ISSUE TITLE
advanced search: space as search term leads to solr error

### ISSUE THREAD

**Issue by akohlbecker** [gbhl/bhl-europe#253]
entering only a space character in an advanced search field leads to an error in the solr query syntax:

for example space as term in title:

```
org.apache.lucene.queryParser.ParseException: Encountered " ")" ") "" at line 1, column 13.
....
webapp=/solr path=/select params={json.nl=map&wt=json&q=mods_title:(+)} status=400 QTime=11 
```

So fields only containing whitespace, that is fields which can be trimmed empty should be neglected.

**Comment by wkollernhm** [comment]
Solved
