### ISSUE TITLE
search always falls back to advanced search

### ISSUE THREAD

**Issue by akohlbecker** [gbhl/bhl-europe#257]
The bhle_search module always falls back to advanced search:
1. go to advanced search
2. select the _title_ field and enter _darwin_
3. execute search
4. go to **home** = simple search 
5. enter _thomas_  as search term
6. execute search (now you get all books with _thomas_)
7. reload the page (now you have again executed the advanced search)

**Comment by wkollernhm** [comment]
The type of search is now set in the validation handler instead of during rendering, this should fix this issue (and make it more clean anyway).
