### ISSUE TITLE
Search page - default search functions

### ISSUE THREAD

**Issue by fwelter** [gbhl/bhl-europe#26]
default search functions for the search page:

features to be implemented, based on the results of Question 6 of the BHL User Survey 2010
documented here: http://www.planetposter.de/bhl/wien2010.htm
- Terms submitted to the default search function should be queried in the author, the year,  the monograph title and the journal title. 
- If 2 words are inserted, the search function should only return results that contain BOTH words.
- If two words are put in " quotes, then only results with the two words in that combination should be returned.
- Wildcard options with \* as the wildcard should be possible.
- Boolean terms seach (and, or etc.) should NOT be included in the default search function. The default search function should be able to understand the word "and" as a word belonging to the title.
- No tolerant search in the default search function. Only exact sequences of letters should be queried. If no or few results are returned, it is an option to show a line "did you mean ...?" But the set of search results should not contain results that had not exactly been queried.
- Taxonomic names should also be understood, and queried in other fields. But this is another topic and should be solved only after the basic search for the titles were implemented and have been tested.

Any additional features should be offered only in the advanced search modes. This contains Boolean terms, tolerant search, automatic corrections etc.
The term "Google-like search" is problematic because it contains a variety of different features of default search functions, functions that also change every few weeks. This is why I tend to avoid this term. In the BHL User Survey 2010 we defined one function of it as "Perform simple "Google-like" keyword searches that return a long list of search results ranked by relevancy". But the term "Google-like search " includes much more (tolerant searches of any kind, country-driven result filters, excluding results from websites hosted in other coutries, the system being able to remember what the querying IP address has queried in the past, intelligent ranking...).

**Comment by janahoffmann** [comment]
This issue is included in CoR 1.1 and 1.2 (Simple and advanced search and split up into a number of features). The comment will be forwarded to the test manager Jiri Frank. The Google like search is now renamed into 'automated search'.
@fwelter
@jirifrank
