### ISSUE TITLE
Search page - create two search boxes to allow "relle des mo" query

### ISSUE THREAD

**Issue by fwelter** [gbhl/bhl-europe#27]
Search page: Enable query mode for "relle des mo" search. 

This feature is based on the results of Question 6 of the BHL User Survey 2010
documented here: http://www.planetposter.de/bhl/wien2010.htm
"The current BHL default should be maintained as a possible option "exact letter combination in title", so that "relle des mo" could be inserted and return only extremely few results (of a title "Histoire naturelle des mollusques"). "

This issue is related to the discussion in Tervuren, 9 June 2011. In Tervuren we saw that there was no standard term used for this kind of search, and that previously used terms were misunderstood. I will adopt the term "relle des mo search" for it here.
The "relle des mo search" is the current BHL default search function and obtained a very good response in the BHL User Survey 2010, especially by frequent users, because it allows extremely efficient and quick queries. It is one of the best ways to verify in shortest time that a title is NOT contained in the dabase queried.

In Tervuren the reasonable argument arised (brought forward by AIT) that the relle des mo search function could not work parallel to other search functions in the same search box. There was a clearly pronounced "either or".

A good solution for the problem would be to offer two search boxes parallel on the same page. Something that comes close to this idea is currently shown (by coincidence, probably not deliberately) on the BHL-US search page:
http://www.biodiversitylibrary.org/
In the centre is a "long" search box, and in the upper right side there is a "short" search box (both seach boxes have exactly the same function and the same mode of search).

In OCLC designed search pages like 
http://grib.gbv.de/
(which I would recommend to use, or a portal design that comes very close to this design, see issue #24)
we have only one "long" search box, only.

BHL-Europe could provide two search boxes:
- A  "long" search box at the left-side position (of the OCLC-like designed search page) with the regular default search mode (issue #25).
- A second "short search box" at the upper right side (the same position where the search box is located in the BHL-US search page) with the "relle des mo search" mode. Currently the BHL-US search page has written "Search " next to that box. This could be replaced by "Exact letter search", to show that this box offers a different mode for queries. The "short" box can be as short as in the BHL-US search page (50 % of the length of the "long" search box). More length is not needed here because the relle des mo search queries are usually shorter.

I am absolutely convinced that users would highly appreciate having two different modes of query offered at the same page. I predict that many users would use both search modes (and both modes every day), depending on the nature of their query at the time. If it would be possible to make this true, the BHL-Europe portal would provide the most efficient mode of search of all biodiversity related portals I have seen until now.

**Comment by janahoffmann** [comment]
This issue is included in CoR feature 1.2.13. The test report will be forwarded to the test manager Jiri Frank.
@fwelter
@jiriFrank

**Comment by janahoffmann** [comment]
now issue #56
