### ISSUE TITLE
Download metadata from result list/tagging basket

### ISSUE THREAD

**Issue by lobajuluwa** [gbhl/bhl-europe#278]
Direct download of item from result list using tagging option

Connected Issue #100

Download item/content viewer side - implemented and ready for testing.

**Comment by lobajuluwa** [comment]
@chris-sleep

**Comment by JiriFrank** [comment]
the function is done and testable,

we are doing the styling now of the metadata icons, will be added till the end of this week.

We are calling it as tagging basket

**Comment by JiriFrank** [comment]
Works. Ready to be closed.
