### ISSUE TITLE
Closed Issues for Nov Release - ready for testing

### ISSUE THREAD

**Issue by lobajuluwa** [gbhl/bhl-europe#279]
@JiriFrank

Jiri hi, we now have 51 Closed Issues ready for testing against the Nov Release milestone.
All issues previously planned for the Nov Sub Release which are not yet ready for testing have  been moved to the next milestone - Jan 2012. I have created this project issue so that you can move the Closed Issues planned for the Nov Release to the Test Release Milestone. 
Hope all makes sense. ;-)

**Comment by lobajuluwa** [comment]
Hi Jiri!
Just to remind you that there are 51 Closed Issues from the Nov Release that need to be opened up in the test release milestone ahead of Monday's proposed testing kick-off
Thanks.
@JiriFrank

**Comment by JiriFrank** [comment]
@lobajuluwa 
Hi Lola,

thank you for reminder, I know :-) I have plan to go through all of them tomorrow. 
Cheers!
Jiri
