### ISSUE TITLE
Search page - list of search results - exclude single journal volumes from list

### ISSUE THREAD

**Issue by fwelter** [gbhl/bhl-europe#28]
Search page, default search function: if the results for a query return the name of a journal, only the journal title shall appear in the list of search results.

Example:
http://test111.ait.co.at
query:
annalen naturhistorischen museums wien

(current result set: 1588 hits)

this query shall basically return only the journal homepage for the journal "Annalen des Naturhistorischen Museums in Wien", like for example in the same query at
http://grib.gbv.de
where currently only 5 results are returned (results 1-3 and 5 refer to the same journal, this is not perfect, but more or less acceptable)

The query shall NOT return every single journal volume in the results set.

Bad example:
http://test111.ait.co.at
query:
annalen

In this query every single journal volume is listed. This is nonsense. Only the result that links to the journal homepage (bibliography page) should show up.

Good example:
http://www.biodiversitylibrary.org
query:
annalen des naturhistorischen museums

Only one result is shown here, it is exactly what we need here.

**Comment by janahoffmann** [comment]
test

**Comment by janahoffmann** [comment]
This issue is included in CoR feature 1.2.6, 1.4.3. The test report will be forwarded to the test manager Jiri Frank. 
@fwelter
@jiriFrank

**Comment by janahoffmann** [comment]
now issue #49
