### ISSUE TITLE
bad links in 'Top menu' block and in other blocks

### ISSUE THREAD

**Issue by akohlbecker** [gbhl/bhl-europe#284]
The 'Top menu' which shows up in the 'Content top' region of the advanced search is using absolute url paths. This leads to problems everywhere where the portal is not installed at the server root. A 'Top menu' menu already exists (http://bhl-int.nhm.ac.uk/portal/admin/structure/menu/manage/menu-top-menu). This menu, which has correct links, could replace the block. However menus might not support anchors and query parameters as needed for the tutorial link. Another option is to use the `l()` (http://api.drupal.org/api/drupal/includes--common.inc/function/l/7) function of drupal in the block:

suggested new php code for the top menu block: 

``` php
<ul class="top-menu-list">
    <li class="top-search">
    <?php
        $title = t('Search');
        $attributes =  array('class' => array('search-top-link'), 'title' => $title);
        print( l($title, 'search/bhle', array('attributes' => $attributes)) );
    ?>
    </li>
    <li class="top-browse">
    <?php
        $title = t('Browse');
        $attributes =  array('class' => array('browse-top-link'), 'title' => $title);
        print( l($title, 'browse', array('attributes' => $attributes)) );
    ?>
    </li>
    <li class="top-tutorial">
    <?php
        $title = t('Tutorial');
        $attributes =  array('class' => array('tutorial-top-link', 'colorbox-inline'), 'title' => $title);
        print( l($title, current_path(), array('attributes' => $attributes, 'query' => array('width' => '960', 'height' => '500', 'inline' => 'true') ,'fragment'=>'tutorial-inline-content')) );
    ?>
    </li>
</ul>
```

@chris-sleep @JiriFrank

**Comment by JiriFrank** [comment]
Is that fixed or not?
@chris-sleep
@jhquentin

**Comment by akohlbecker** [comment]
seems fixed, since I could not find any broken links. 
@chris-sleep
