### ISSUE TITLE
View BHL news in Portal

### ISSUE THREAD

**Issue by akohlbecker** [gbhl/bhl-europe#29]
RSS feeds issued from twitter, facebook etc are to be displayed on the portal front page in a "news" box.
This can be accomplished by making use of the Drupal aggregator module.
The news box will be placed initially in the left side bar.

List of potential feeds to be included:
- http://twitter.com/BHLEurope
- http://www.facebook.com/pages/BHL-Europe/151086001600041
- http://bhleurope.blogspot.com/
  A compilation of different feed sources is http://www.netvibes.com/bhl-europe#Projects

Further reading:
- http://support.twitter.com/groups/31-twitter-basics/topics/111-features/articles/15361-how-to-find-your-rss-feed

**Comment by janahoffmann** [comment]
This issue is included in CoR feature 4.1.7. I will include your comment and assignment as soon as the feature is set up properly.
@akohlbecker

**Comment by akohlbecker** [comment]
@janahoffmann : I cannot find the new ticket on CoR feature 4.1.7., shouldn't we keep this ticket open until the new ticket has been created and until the comments have moved?  Otherwise we might lose information.

**Comment by janahoffmann** [comment]
@akohlbecker: I copied all of the comments, so nothing gets lost. I am in the process adding all the features, as you can imagine not a very exciting job. I will continue adding the features today, so everything will be up an running soon. Another problem is that some of the previous issues relate to several features, so they might be replaced by more than one feature. In future we will track back all changes, etc., however this time is more about setting up a starting point. So, I will take care of your comments :-) no worries

**Comment by janahoffmann** [comment]
now issue #110
