### ISSUE TITLE
test feature

### ISSUE THREAD

**Issue by leenamba** [gbhl/bhl-europe#30]
Description of feature to test

@janahoffmann
@jirifrank
@lobajuluwa

**Comment by leenamba** [comment]
test of mentions
@leenamba

**Comment by janahoffmann** [comment]
Hello you guys..

Museum für Naturkunde
Leibniz Institute for Research on Evolution and Biodiversity at the Humboldt University Berlin

Jana Hoffmann 
BHL-Europe - project assistant  

http://www.bhl-europe.eu/
Invalidenstraße 43 
10115 Berlin 
Germany 

phone: +49 (0)30 2093-8650
fax: +49 (0)30 2093-8565 
email: jana.hoffmann@mfn-berlin.de 
website: http://www.naturkundemuseum-berlin.de 

-----Ursprüngliche Nachricht-----
Von: leenamba [mailto:reply@reply.github.com] 
Gesendet: Mittwoch, 22. Juni 2011 11:33
An: Hoffmann, Jana
Betreff: Re: [bhle] test feature (#30)

test of mentions
@leenamba

##
