### ISSUE TITLE
OLEF content not written to METS file

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#305]
The content of the olef.xml is not correctly transferred to the METS file.

Example:
login to pre-ingest tool using nbgb user (using our standard password). The second item on the list (NBGB019667DEMO1854TRAITEDE00) is ready for ingest but inside the main mets-xml file the OLEF data is truncated.

Please fix immediately as this is blocking.

@lobajuluwa 
@chris-sleep

**Comment by wkollernhm** [comment]
Sample:

Source:
`<mods:subject xmlns:mods="http://www.loc.gov/mods/v3">
<mods:topic>BEL Belgium &amp; GDL</mods:topic>
</mods:subject>`

Destination:
`<mods:subject xmlns:mods="http://www.loc.gov/mods/v3">
<mods:topic>BEL Belgium </olef></METS:xmlData></METS:mdWrap>`

**Comment by mindcatch-com** [comment]
fixed - please confirm & close

**Comment by wkollernhm** [comment]
This now works.
