### ISSUE TITLE
Automatic refresh causes browser warning

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#306]
When using firefox the automatic refresh causes the browser to warn about resending-information.

Please fix as this causes the browser to prompt the user every 120seconds.

@lobajuluwa 
@chris-sleep

**Comment by akohlbecker** [comment]
which pages are refreshed automatically, could you please give an example?

**Comment by akohlbecker** [comment]
Ah ok, this ticket is labeled with "preingest and Olef" i assumed it is on the portal, so forget about my last comment.

**Comment by wkollernhm** [comment]
Fix confirmed as of 2012-02-23
