### ISSUE TITLE
Change GUID minter to use noid service

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#307]
Pre-Ingest tool should use the pre-installed noid service for fetching GUIDs.

See https://bhl.wikispaces.com/GUID_Server for details on how to access the noid service.

@lobajuluwa 
@chris-sleep

**Comment by mindcatch-com** [comment]
the PI now uses this webservice, if not available it mints own guids (local development requirment)

**Comment by wkollernhm** [comment]
Tested & works
