### ISSUE TITLE
Install and setup activeMQ on Mandible

### ISSUE THREAD

**Issue by leenamba** [gbhl/bhl-europe#308]
Document on wiki following existing documentation standards of project.

To reassign to Zhaoyu

**Comment by leenamba** [comment]
And install and enable stomp connector for PHP access and JMS for Java access

**Comment by ZhaoyuLI** [comment]
The documentation for this issue: https://bhl.wikispaces.com/ActiveMQ%26Stomp

**Comment by zhengl** [comment]
Configure ActiveMQ for serving dev, test and prod in parallel.
Opiton 1) Receive message only from specific IP
          2) Define different topic/queue name for different machine
          3) other ideas?

**Comment by ZhaoyuLI** [comment]
There are three instances of activemq running on mandible providing service to : integration, test, production. The port information already updated in wiki page: https://bhl.wikispaces.com/ActiveMQ%26Stomp
