### ISSUE TITLE
Replace PI notification text file to ActiveMQ message

### ISSUE THREAD

**Issue by leenamba** [gbhl/bhl-europe#309]
Maybe using Stomp

**Comment by wkollernhm** [comment]
@ZhengLIAtos 

What information should the message from the PI tool include?

**Comment by zhengl** [comment]
@wkollernhm 

A key-value pair in the form of 'URL : file///mnt/....' indicating the location of .aip folder should be enough.
Please keep both notification mechanism until messaging is fully tested.

**Comment by wkollernhm** [comment]
I think we should add the GUID to the message as well, as we need to notify pre-ingest once the ingest was successfull (and we should use the GUID for that).

**Comment by zhengl** [comment]
Yes, you are right.

2012/2/22 wkollernhm <
reply@reply.github.com

**Comment by wkollernhm** [comment]
Please implement in PI tool

See Issue #322 for the prepared class.

@mehrrath

**Comment by mindcatch-com** [comment]
ongoing but no tests possible due lasting server errors i reported +7 times now
besides, i will keep the control files in paralell to be able to renotify via message broker later

if changes were made to the php class i now added to the preingest tool structure
i need a clear notification via github or an push to the preingest ./stomp-client git directory !

@wkollernhm 
@heimor 
@ZhengLIAtos

**Comment by mindcatch-com** [comment]
the stomp client class is not working!

@wkollernhm 
@heimor 
@ZhengLIAtos 

i got no information from the queue with the predefined functions.
tested on int with original class and example provided.

**Comment by mindcatch-com** [comment]
test url: http://bhl-int.nhm.ac.uk/preingest/index.php?menu_nav=test_mb
test script:  inc/message_broker.php

@ZhengLIAtos

**Comment by wkollernhm** [comment]
@mehrrath can you please be more specific on what the exact problem is? Are you sending messages but not receiving any?

@ZhengLIAtos please review the class and verify that everything is working.

**Comment by mindcatch-com** [comment]
i can not be more specific than providing an exact example everyone can view and test on the server.
with the link and url i provided.

i receive nothing when generating the entry and even not when asking the queue 
as you may see when you execute.

**Comment by mindcatch-com** [comment]
https://github.com/bhle/bhle/blob/master/pre-ingest/ingest/inc/message_broker.php

**Comment by wkollernhm** [comment]
Thanks for clarifying, it wasn't clear to me that both functions do not seem to work.

@ZhengLIAtos please review the example of Andreas and check if everything is working as expected.

**Comment by mindcatch-com** [comment]
when i go further i can fix these problems myself an you can start to assign this to mee ;o)))) 

an example error of wrong include in the code

Warning: require_once(Stomp/Message.php) [function.require-once]: failed to open stream: No such file or directory in G:\dev\nhm\ingest\htdocs\stomp-client\Stomp\Message\Map.php on line 21

br

**Comment by wkollernhm** [comment]
Quite obviously the Stomp-Framework is missing. If you can fix this yourself go ahead.

**Comment by mindcatch-com** [comment]
no there is obviously nothing missing!
as you can see in git clearly the RELATIVE PATHS in the includes are wrong (e.g. map.php line 21)
the framework is included in original structure untouched but has wrong references in itself

**Comment by wkollernhm** [comment]
Thanks for pointing out. As you already found the problem please fix it so that you can continue on the ActiveMQ integration.

**Comment by mindcatch-com** [comment]
this is only one problem. i want zheng to check the code and comment it. 
i think there are some small things missing!
i wrote zheng last week and got no answer so i choose this way.

**Comment by wkollernhm** [comment]
I've re-opened Issue #322 to address these issues.

Problems should always be addressed using the github issue tracker, not directly by email.

**Comment by mindcatch-com** [comment]
the time i sent an email was before real integration.

i solved the problems in stomp-client now myself and continue testing !

@wkollernhm 
@heimor 
@ZhengLIAtos 

stomp-client in preingest now is different to original.

**Comment by mindcatch-com** [comment]
@ZhengLIAtos 

current error now is: "Failed to receive a message"
please investigate and give me feedback, thanks.

NOW TESTING MB.

Failed to receive a message

END TESTING MB. 

again the references:

https://github.com/bhle/bhle/blob/master/pre-ingest/ingest/inc/message_broker.php

test url: http://bhl-int.nhm.ac.uk/preingest/index.php?menu_nav=test_mb

@wkollernhm 
@heimor

**Comment by wkollernhm** [comment]
@mehrrath Thanks for putting effort into this.

@ZhengLIAtos please investigate on this issue with priority 1 -> we need a solution by tomorrow.

**Comment by zhengl** [comment]
Sorry for my late reply!

Actually, there is no bug. The reason is that we are using a ActiveMQ queue but not a topic. Now Ingest Tool is subscribing to '/queue/preingest', and once this testcase generates a message to '/queue/preingest', this message is swallowed by Ingest Tool immediately, therefore the testcase reports 'Failed to receive a message'.

The solution can be changing '/queue/preingest' to '/topic/preingest' to allow multiple consumers. A client becomes a durable subscriber once it has a clientID (defined as 'preingest' in MessageHelper.php, https://github.com/bhle/bhle/blob/master/pre-ingest/ingest/stomp-client/MessageHelper.php). No matter what a durable client does except acknowledging the server that it has already received the message, when it re-subscribes to the topic/queue, it can receive its copy.

Please wait for my correction...

**Comment by wkollernhm** [comment]
@ZhengLIAtos the question is, if it is necessary to use a topic? The PI-tool does not have to receive own messages - if everything is working as expected we can continue with the current solution.

**Comment by zhengl** [comment]
Sure, I can easily change it back to queue.
Basically, they are the same in our scenario (queue for multiple workers, topic for multiple subscribers, we have only one producer and one consumer). But using queue would be not so testable for Preingest (although we can check it in ActiveMQ Admin http://bhl-int.nhm.ac.uk/admin and Ingest side).

Please give me a "GO" if you have thought it over.

**Comment by wkollernhm** [comment]
If you have already changed it to a topic, please leave it as it is now. The most important fact is, that it is working. And therefor we keep the current solution.

Thanks for your input.

**Comment by mindcatch-com** [comment]
can you clearly say what you have decided, what pi should change or use?

pi currently using 

protected $_queue = "/queue/preingest";

and not receiving any messages from this queue due errors you see above.

do you still write the ingest_done.txt to my aip folders ?
(i must have an indicator for "ingest finished")!

do pi generated messages reach active mq correctly?

...
@ZhengLIAtos
@wkollernhm

**Comment by zhengl** [comment]
Please take a look at https://github.com/bhle/bhle/blob/master/pre-ingest/ingest/inc/message_broker.php

In short, PI sends messages to Ingest via /queue/preingest, and receives messages from Ingest via /topic/ingest.

@mehrrath

**Comment by mindcatch-com** [comment]
i see you updated the code with a new gathering func. 
thanks zheng that says more than 100 words. what i 
miss for future is a method for gathering a particular state of
a guid ...

besides:
please never ever use php predefined names like  echo() for your own ones ...

**Comment by mindcatch-com** [comment]
codes merged, new release comes soon....

**Comment by mindcatch-com** [comment]
@ZhengLIAtos 
have you tested the ready for ingest messages preingest is generating since last week?

@wkollernhm 
if they are ok please close

**Comment by zhengl** [comment]
@mehrrath 
Unfortunately, Preingest Tool is not sending messages when I trigger the last step of an item in the list. You can always monitor whether a message is sent or not by monitoring the 'preingest' on http://bhl-int.nhm.ac.uk/admin/queues.jsp. Let me know if I can provide any help.

**Comment by mindcatch-com** [comment]
i use your framework and get no error back

define ("_MB_ABS",                   _ABS."stomp-client/");
define ("_MB_URL",                   "tcp://bhl-mandible.nhm.ac.uk:61613");
....
$messageHelper = new MessageHelper(_MB_URL);
return $messageHelper->informIngest($content_guid, "file://".$content_aip);

what else is neccessary?

@ZhengLIAtos

**Comment by mindcatch-com** [comment]
http://bhl-int.nhm.ac.uk/admin/queues.jsp.

shows 24 enqueued messages ....

please solve this issue, problems can only be inside your stomp client i am calling each time the last step was successfull.

thanks andy

@ZhengLIAtos

**Comment by mindcatch-com** [comment]
as you know you can see everything at:

https://github.com/bhle/bhle/tree/master/pre-ingest/ingest/stomp-client

https://github.com/bhle/bhle/blob/master/pre-ingest/ingest/inc/message_broker.php

**Comment by zhengl** [comment]
@mehrrath 

I have completely re-factored the MessageHelper class (add a thread as a subscriber) and I am sure it can more easily adapt to the business process of Preingest Tool.

Please take a look at ~/dev/stomp-client/MessageHelp.php.
and run receive.php and send.php in sequence for testing.

**Comment by wkollernhm** [comment]
Please post the messagehelper class directly to github, so that Andreas can get it from there (post it into the pi-tool stomp-client directory).

**Comment by zhengl** [comment]
https://github.com/bhle/bhle/commit/131fe8ab066251915c4ea7c2ab2196027f4d963f

**Comment by mindcatch-com** [comment]
i will add this release to preingest 1.70
is it tested and do you now want bhle: prefix in guid or not when notify?

regards, andi

**Comment by mindcatch-com** [comment]
@ZhengLIAtos

please answer my previous question thanks.
can you start testing this again on e.g. sunday?

**Comment by wkollernhm** [comment]
@ZhengLIAtos 
Are notification messages working for you now?

What part is missing from your end to fully automate ingesting content?

**Comment by zhengl** [comment]
I can see the automatic ingest is functioning now, so please be careful when generating some AIP for testing other than ingesting. You can always check http://bhl-int.nhm.ac.uk/ingest/jobs/batchIngestJob for the status of each job.

**Comment by wkollernhm** [comment]
great, so I can actually close this issue.

Are there any plans to setup a own fedora/access component for test?

@chris-sleep
