### ISSUE TITLE
Create controlled vocabulary for Licences (IPR Handling in Pre-Ingest)

### ISSUE THREAD

**Issue by lobajuluwa** [gbhl/bhl-europe#311]
Task description:-

If licence doesn't match notify - CP and allow default selection in settings with Question mark (?)

**Comment by wkollernhm** [comment]
Change IPR Input field to drop down containing the following options:

http://creativecommons.org/publicdomain/mark/1.0/
http://creativecommons.org/publicdomain/zero/1.0/
http://creativecommons.org/licenses/by/3.0/
http://creativecommons.org/licenses/by-sa/3.0/
http://creativecommons.org/licenses/by-nc/3.0
http://creativecommons.org/licenses/by-nc-sa/3.0/
http://creativecommons.org/licenses/by-nd/3.0/
http://creativecommons.org/licenses/by-nc-nd/3.0/
http://www.europeana.eu/rights/rr-f/
http://www.europeana.eu/rights/rr-p/
http://www.europeana.eu/rights/rr-r/
http://www.europeana.eu/rights/unknown/

Drop-down should be accessible if either the pre-filled in value of the content provider does not match one of those or if the field is empty. (`<accessCondition>`)

@mehrrath

**Comment by mindcatch-com** [comment]
allow default selection in settings with Question mark ????? what do you mean?

**Comment by mindcatch-com** [comment]
do you mean cp settings or config.php for all

**Comment by wkollernhm** [comment]
This should be set in the CP settings (so on a per CP basis).

"allow default selection in settings with Question mark" means that if the tool can't identify a pre-filled value it sets the value to a default selection. (configured in the CP settings).

**Comment by mindcatch-com** [comment]
implemented see history.txt

**Comment by wkollernhm** [comment]
Selecting IPR from a controlled vocabulary is now possible.
