### ISSUE TITLE
setup OpenLDAP

### ISSUE THREAD

**Issue by akohlbecker** [gbhl/bhl-europe#32]
- setup OpenLDAP on the bhle server (mandible)
- document all steps in the wiki

this ticket is prerequisite for #143

**Comment by DZielke** [comment]
OpenLDAP is setting up on the BHL-E Server, see also:
http://bhl-mandible.nhm.ac.uk/mint?n=2

documentation is found under Wiki, see here:
https://bhl.wikispaces.com/Installation+of+LDAP+server
(work in progress)
