### ISSUE TITLE
PHP ActiveMQ Class (for PI)

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#322]
PreIngest needs to dispatch a message to Ingest using ActiveMQ.

In order to maintain communication in an easy way a PHP-class for wrapping the communication should be coded.

Requirements:
- Connect to ActiveMQ
- Send message to Ingest notifying it of items ready for ingest (pass required information as parameters to function call)
- Receive messages from Ingest confirming the successfull ingest (by returning the GUID)

See issue #309 for reference!

@ZhengLIAtos: Please implement such a class in PHP so that Andreas can easily integrate it into the PI-application.

@lobajuluwa 
@chris-sleep 
@mehrrath

**Comment by zhengl** [comment]
Here is a stomp-client from stomp,
http://stomp.fusesource.org/release/php/1.0/stomp-php-1.0.0.tar.gz, let's
define the message body and test it after the installation of ActiveMQ +
Stomp.

As discussed before, here is a list of details of messages from MQ:
1. Message is sent via queue, but not topic.
2. From Pre-ingest. Message contains file URI pointing to the location
   of AIP and GUID of the item to be ingested.
3. From Ingest. Message contains the status (SUCCESS, FAIL) and the
   tracestack of exception

2012/2/22 wkollernhm <
reply@reply.github.com

**Comment by wkollernhm** [comment]
Please wrap this functionality in a PHP class! Andreas should just need to call a simple PHP-Method for sending a new message to Ingest and call another function for receiving a message from Ingest!

**Comment by zhengl** [comment]
Done.

Please take a look at int1 dev/stomp-client/MessageClient.php
there are send.php and receive.php simulating messaging between Pre-ingest and Ingest.

**Comment by mindcatch-com** [comment]
ahhh finally i found these files myself. there is no directory on the server dev/stomp.....

these files are in /mnt/nfs-demeter/development/stomp-client/

is there any explanation how i should use these functions? at least (1) the message
format and content expected from pi and (2) the desc of the msgs. provided back from 
ingest (when / where / what) !!

all i know that we should use the guid....

@wkollernhm 
@ZhengLIAtos 
@heimor

**Comment by zhengl** [comment]
@mehrrath 

There are three new files based on stomp-client, which are
- MessageHelper.php: Wrapper class of stomp client, please see informIngest ($guid, $uri). The name of message queue is 'preingest'
- send.php: Example of sending messages
- receive.php : Example of receiving messages (without timeout of 60 seconds)

For more information of ActiveMQ, please refer to https://bhl.wikispaces.com/ActiveMQ%26Stomp

**Comment by mindcatch-com** [comment]
@ZhengLIAtos 

 please summarize and copy&paste all necessary information for me in one clear document i can
read and implement at once.

i must save time for this task i have no time to inspect all distributed information. also
explain how you use and generate when+which messages and their content for PI. 
i must know them and react.

now i must drive home i need some sleep. thanks a lot.

**Comment by wkollernhm** [comment]
This seems to be done, please see #309 and #310 for the actual implementation tasks.

**Comment by wkollernhm** [comment]
The class still has some issues, see #309

Please fix this.

**Comment by wkollernhm** [comment]
Works as expected (see issue #309)
