### ISSUE TITLE
1.1.3 - Autocomplete search (Simple Search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#35]
Updated description:
Autocomplete involves the program predicting a word or phrase that the user wants to type in without the user actually typing it in completely (taken from Wikipedia).
Autocomplete features shall be enabled by default (in simple search).

Note: Not to be used in advanced search

@jhquentin

Previous description:
Search by drop-down list with suggest terms.

Precondition: Full index of metadata including OCR (if part of metadata)

**Comment by heimor** [comment]
@lobajuluwa
just revising the open github issues assigned to NHMW

not clear why this issue 1.1.3 has been assigned to us - any ideas ?

**Comment by lobajuluwa** [comment]
Autocomplete search is a feature request that originated from the Core Feature "google-like search" - Search & Retrieval. 
If this is correct then the Autocomplete search functionality should be completed by AIT.
Jana if this is correct, I'll reassign it to AIT asap. Thanks Heimo.
@heimor
@janahoffmann

**Comment by janahoffmann** [comment]
@jhquentin: Jan, please tell me what the preconditions are for this feature, e.g. special index, full OCR indexing? I need this for the Catalogue of requirements.

**Comment by JiriFrank** [comment]
1.1.3 - Autocomplete search (Simple Search)

COR number: 1.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Description:

Autocomplete involves the program predicting a word or phrase that the user wants to type in without the user actually typing it in completely (taken from Wikipedia).

Autocomplete features shall be enabled by default (in simple search).

Note: Not to be used in advanced search

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment]
It works. Just two notes:

(1) autocompletion of author names is a bit viscous. If you search "Sturm" you need to type the complete name. In the case of Darwin you need "Darwi" before a selection is offered.

(2) It could be confusing that author names (which generally start with a capitalized letter) start with lowercase letters. If you search "Krogerus" autocompletion offers you "krogerus" - no dramatic problem but a bit confusing for users who like perfection (libraries etc.).

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:22
An: Hand, Ralf
Betreff: Re: [bhle] 1.1.3 - Autocomplete search (Simple Search) (#35)

1.1.3 - Autocomplete search (Simple Search)

COR number: 1.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Description:

Autocomplete involves the program predicting a word or phrase that the user wants to type in without the user actually typing it in completely (taken from Wikipedia).

Autocomplete features shall be enabled by default (in simple search).

Note: Not to be used in advanced search

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by HenningScholz** [comment]
This works fine, and if you type slow enough you can fully benefit from the autocomplete function. Much less annoying then in Google.

By the way: I'm testing with IE under Win XP or Win 7, depending if I work from home or from the office.

Henning

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 13:22
An: Scholz, Henning
Betreff: Re: [bhle] 1.1.3 - Autocomplete search (Simple Search) (#35)

1.1.3 - Autocomplete search (Simple Search)

COR number: 1.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Description:

Autocomplete involves the program predicting a word or phrase that the user wants to type in without the user actually typing it in completely (taken from Wikipedia).

Autocomplete features shall be enabled by default (in simple search).

Note: Not to be used in advanced search

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AnneSch** [comment]
Works fine!

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:22
An: Scholz, Annemarie
Betreff: Re: [bhle] 1.1.3 - Autocomplete search (Simple Search) (#35)

1.1.3 - Autocomplete search (Simple Search)

COR number: 1.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Description:

Autocomplete involves the program predicting a word or phrase that the user wants to type in without the user actually typing it in completely (taken from Wikipedia).

Autocomplete features shall be enabled by default (in simple search).

Note: Not to be used in advanced search

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
Like this function, works well, but then I'm a slow typist

Graham

**Comment by JiriFrank** [comment]
1.1.3 - Autocomplete search (Simple Search)

COR number: 1.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Description:

Autocomplete involves the program predicting a word or phrase that the user wants to type in without the user actually typing it in completely (taken from Wikipedia).

Autocomplete features shall be enabled by default (in simple search).

Note: Not to be used in advanced search

@AntonioGVH
@fwelter
@LarissaS

**Comment by AntonioGVH** [comment]
I tried all the alphabetic letters and seems to work properly.
Words beggining with letters with diacritic signs do not produce any answer (may be there are no words with them: ñ, wü, wö, etc.
However, aü produce some answer, so may be letters with diacritic signs do work!

Quoting JiriFrank:

**Comment by JiriFrank** [comment]
The functionality is on place and works.

This feature will be more beneficial with more content and we will see how it will behave with real data. Now it could be closed.
