### ISSUE TITLE
Do not URL encode PIDs

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#350]
Currently the PI tool does URL-encoding for PIDs. This should not happen (since hyphens are URL-encoded).

Disable URL-Encoding for PIDs.

See issue #327 & #323

**Comment by zhengl** [comment]
This has been corrected once before by Andy, and I think you can have the
up-to-date version in int1 /var/www/ingest.

2012/2/27 wkollernhm <
reply@reply.github.com

**Comment by wkollernhm** [comment]
Thanks for the info, but the version on bhl-test is the most recent one as I copied it from /var/www/ingest/ on bhl-int!

**Comment by wkollernhm** [comment]
@ZhengLIAtos: I've tested this with the latest version and OBJIDs are not URL encoded.
