### ISSUE TITLE
pageType contains wrong data

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#363]
The information in the pageType attribute of each page entry in the OLEF contains invalid data - namely the sequence number instead of the actual pageType of the filename.

Example:
Original filename: NBGB013726AIGR1889FLOREELE00_0001_FRONTCOVER.tif
Information in OLEF:
`<page pageType="0001">`

but it should be "frontcover"

@chris-sleep 
@lobajuluwa

**Comment by mindcatch-com** [comment]
this is fixed with function getPageType($file_name)

**Comment by wkollernhm** [comment]
Fix confirmed
