### ISSUE TITLE
names of pages not correct

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#364]
Names of pages are not correctly transfered to OLEF.

Currently the names of the pages seem to be a continuous number, however it should be the actual name as provided by the filename.

Example:
Original filename: NBGB013726AIGR1889FLOREELE00_0240_PAGE_236.tif
OLEF output: `<name>243</name>`

But it should be `<name>236</name>`

@chris-sleep 
@lobajuluwa

**Comment by mindcatch-com** [comment]
problem solved 

with extended support for up to 4 pages in one file, the numbers then are separated with comma in this tag value !

**Comment by wkollernhm** [comment]
Fix confirmed
