### ISSUE TITLE
OLEF Namespace for XML-Nodes

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#370]
Generated XML-Nodes do not contain the OLEF namespace prefix.

example: `<itemInformation>` should be `<olef:itemInformation>`

This applies to all generated OLEF elements.

@chris-sleep 
@lobajuluwa

**Comment by mindcatch-com** [comment]
this is an very new requrement.
do you mean that all nodes in the embedded olef in the master parent xml should have this prefix?
please remember that there is already the mods prefix in many of these nodes!

e.g. 

<olef>
<element>
<bibliographicInformation>
<mods:titleInfo xmlns:mods="http://www.loc.gov/mods/v3">
mods:titleAntwerpsche analytische flora inhoudende de beschyving van alle planten, welke in de provincie Antwerpen, in de vrye natuer, groeijen of er algemeen gekweekt worden. Eerste deel/mods:title
/mods:titleInfo
<mods:name xmlns:mods="http://www.loc.gov/mods/v3">
mods:namePartVan Heurck, Henri/mods:namePart
mods:namePart1838-1909/mods:namePart
/mods:name
<mods:name xmlns:mods="http://www.loc.gov/mods/v3">
mods:namePartDe Beucker, J.I./mods:namePart
/mods:name

**Comment by wkollernhm** [comment]
No, mods should stay mods (since these elements are defined within the mods namespace).

All elements defined within the OLEF namespace should carry the olef: prefix (as defined by the generated XML of the schema mapping  tool).

**Comment by mindcatch-com** [comment]
previous bugfix rolled back.
new solution: preingester adds olef ns to all elements written/added by preingest itself

**Comment by wkollernhm** [comment]
All nodes now carry the OLEF namespace prefix.
