### ISSUE TITLE
Pages without name contain invalid name

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#371]
Pages without a name get an invalid name assigned.

Example: NBGB013726AIGR1889FLOREELE00_0002_BLANK.tif

becomes: `<name>1</name>` 

pages without a name in the filename should omit the `<name>` tag in XML.

@lobajuluwa 
@chris-sleep

**Comment by mindcatch-com** [comment]
this is a new requirement no bug, i never assumed that in this case it is better to omit the name tag instead of
reconstructing it from the order.

**Comment by mindcatch-com** [comment]
i must change the filename tolerance handling routines

**Comment by wkollernhm** [comment]
The problem is, that all pages contain the page-number 1. So it isn't derived from the sequence but rather all of the entries contain the page-name 1.

In addition everything except ID and TYPE is optional for filenames, since some pages simply may not have a type nor a page-number.

**Comment by mindcatch-com** [comment]
bug fixed and in case they dont have an page number the name element is not written 

for multiple pagenumbers mutliple name elements are generated 

Please update FSG that one page file should contain ONLY ONE page otherwise prepare data first.
image data can not be transformed by areas only problems follow with that

**Comment by wkollernhm** [comment]
The file detection routine is still broke.

When the final METS output is generated I get the following message:

"Error: Filename convention broken! rename your page files according to File Submission Guidelines (FSG)."

In addition the output looks like this:

`<olef:file>`
`<olef:reference type="path">/mnt/nfs/upload/providers/be-nbgb/Upload_20110930/NBGB013726AIGR1889FLOREELE00/NBGB013726AIGR1889FLOREELE00_0002_BLANK.tif</olef:reference><olef:pages>`
`<olef:page pageType="">`
`</olef:page></olef:pages></olef:file>`

So instead of just omitting the name tag, it seems as if the pageType is broken in those cases as well.

Please fix.

**Comment by wkollernhm** [comment]
Just to clarify: all information except ID and SEQUENCE in the filename are optional.

**Comment by mindcatch-com** [comment]
fixed. 

this was a bug in error tolerance routines, now they are disabled an at least ID and SEQUENCE have to be present

please consider handling of this for pdfs !!!

the solution now is to gather sequence number from tif file generated via single page extracts and 2 step convert from pdf to ppm to tiff - sequence currently is also used for page number as you know.

@wkollernhm 
@heimor

**Comment by wkollernhm** [comment]
Parsing of filenames works now.
