### ISSUE TITLE
Certain results from TaxonFinder should be excluded

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#373]
Quote from Heimo:

SNIP
taxonfinder delivers results together with "real" scientific names that do not represent scientific names -
those can be distinguished by the existence of an identifier ( NameBankID )
all scientific names are accompanied by an identifier / non scientific names lack such an identifier

we need to exclude such non scientific names from integration into olef metadata
SNIP

See Issue #93 for the original comment

Please do not write any results from taxonfinder which do not have a NameBankID to the OLEF metadata.

**Comment by wkollernhm** [comment]
@chris-sleep 
@lobajuluwa 
@heimor

**Comment by mindcatch-com** [comment]
feature implemented.

question: is ubio sending an empty namebankid element or no namebankid 
element in this cases (implemented now for second case)

**Comment by wkollernhm** [comment]
No taxon-names are written to the output anymore. It seems as if all names are discarded.

E.g. Taxon-Finder returns:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;results&gt;
&lt;allNames&gt;
    &lt;entity&gt;
        &lt;nameString&gt;Hylocomium&lt;/nameString&gt;
        &lt;namebankID&gt;2642905&lt;/namebankID&gt;
    &lt;/entity&gt;
    &lt;entity&gt;
        &lt;nameString&gt;Hylocomium palustre&lt;/nameString&gt;
    &lt;/entity&gt;
    &lt;entity&gt;
        &lt;nameString&gt;Hylocomium splendens&lt;/nameString&gt;
        &lt;namebankID&gt;3872670&lt;/namebankID&gt;
    &lt;/entity&gt;
&lt;/allNames&gt;
&lt;/results&gt;

for page 83 of NBGB013726AIGR1889FLOREELE00 - however there are no taxon names in the final METS output.

**Comment by wkollernhm** [comment]
Works with the latest fix
