### ISSUE TITLE
pdf pagination / naming

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#376]
check pdf file for page labels and use this for  pagination information in the output TIF image file naming

pdftk - man pages -
http://www.pdflabs.com/docs/pdftk-man-page/

.....
dump_data
Reads a single, input PDF file and reports various statistics, metadata, bookmarks (a/k/a outlines), and page labels to the given output filename or (if no output is given) to stdout. Non-ASCII characters are encoded as XML numerical entities. Does not create a new PDF.
.....

file ABCDEF.pdf
-- page 14 
-- label 10

use 14 for sequence number and 10 for page
result should be

ABCDEF_00014_PAGE_00010.TIF

if pdf does not contain page label data just use the sequence of pages for Sequence and label them as PAGE

filename output pattern should always follow the file naming conventions as defined by the FSG.
(this is a mix between bug & feature, since the current situation is faulty but the label reading from the PDF is a new feature)

@lobajuluwa 
@chris-sleep 
@heimor

**Comment by mindcatch-com** [comment]
I NEED ASAP AN EXAMPLE PDF FROM HEIMO PLEASE

and i will try metadata gathering via http://linux.die.net/man/1/pdfinfo
which is already installed at the server side as part of the pdf toolset i use already

@wkollernhm 

@chris-sleep : can you please preventively install pdftk please.

@heimor: (I NEED ALSO EXAMPLES FOR SERIALS - please support my time management)

**Comment by mindcatch-com** [comment]
till now i have no example, standard naming and sorting will come to effect (pre-seq_PAGE_seq)

@heimor 
@wkollernhm

**Comment by wkollernhm** [comment]
A almost perfect example for serials can be found in isse #376 - please get the details from there.

**Comment by mindcatch-com** [comment]
why serials, this issue is for pdf pagination. i need a pdf with page labels to test this extension!

besides this is no bug this is a feature request. please remove label bug from feature requests.

**Comment by wkollernhm** [comment]
Sorry posted the example in the wrong issue, nevertheless you can use the example mentioned above for use with your serial tests.

This is a mix of a bug and a feature, that's why it has both labels.

**Comment by mindcatch-com** [comment]
so this is am mix of issues, a mix of bug and feature and a mix of pdf and serials ;O)))

can i please have a pdf pagination example i ask for that since 3 weeks.

**Comment by mindcatch-com** [comment]
A almost perfect example for serials can be found in isse #376 - please get the details from there.

--->> this is this issue here !!!!????

i am out of ideas i have no correct examples for pdf pagination and serials till now from you.

@wkollernhm
@heimor

@wolf

**Comment by mindcatch-com** [comment]
@chris-sleep 

have you installed the pdftk on the servers as i requested (i have not checked that pro-active) ?

**Comment by chris-sleep** [comment]
@mehrrath I've added via apt-get

**Comment by wkollernhm** [comment]
Sorry, I meant issue #328 - the sample upload of UBFRANKFURT

**Comment by wkollernhm** [comment]
Exact example: "BJ2248281/BJ2248281_0001_2248284"

=> /mnt/nfs-demeter/upload/providers/de-ubfrankfurt/BJ2248281

**Comment by wkollernhm** [comment]
PDFs do not work at all at the moment. The last step fails due to invalid naming of files. I tried this with be-nbgb/Upload_20110930/poeppig_1841_nova_genera/poeppig_1841_nova_genera_species.pdf

**Comment by wkollernhm** [comment]
Fixed PDF importing by overworking the PDF extraction / conversion process. Reading labels from metadata is still pending.

**Comment by wkollernhm** [comment]
Structural information is now extracted from PDF labels.
