### ISSUE TITLE
Misleading taxon-finder message

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#378]
When the taxon-finder step has finished and the user clicks on the book-icon in order to be able to reach the next step the following message is output:

For 0 text files 246 taxon files (.tax) generated and database updated successfully.

This message is misleading, as it sounds as if there are no text files present. Please change the message to output the correct number of text files (in this sample 246).

**Comment by wkollernhm** [comment]
@lobajuluwa 
@chris-sleep

**Comment by mindcatch-com** [comment]
fixed.

**Comment by wkollernhm** [comment]
Fix confirmed
