### ISSUE TITLE
IPR text is not written to mods:accessCondition

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#379]
The selected IPR license text must be written to the olef:bibliographicInformation/mods:accessCondition field.

See issue #319 for the original description.

See http://www.loc.gov/standards/mods/v3/mods-userguide-elements.html#accesscondition for a detailed description of the field.

@chris-sleep 
@lobajuluwa

**Comment by mindcatch-com** [comment]
cannot reproduce this bug have you a test file url for me?

**Comment by mindcatch-com** [comment]
have you really started a fresh olef metadata gathering followed by a fresh mets generation ???

@wkollernhm

**Comment by mindcatch-com** [comment]
have you really started a fresh olef metadata gathering followed by a fresh mets generation ???

@wkollernhm

**Comment by wkollernhm** [comment]
Tested with latest version of integration. Here is how to reproduce:

Select an arbitrary content. Add it to ingest list. Run through all steps, finally create the METS output. Open METS output and search for "accessCondition" -> nothing found.

This only happens if you do not save your ingest list at least once, which means the IPR-Statement from the users preferences are not written to the METS by default.

**Comment by mindcatch-com** [comment]
state: when you have no default and no metadata ipr   - it was empty and you got a error hint message to re-run the
last step

now: ipr handling again extended. a default default (2times right) pre-selection is now activated when preparing metadata 
without defaults so an auto default becomes default and the olef this if missing you can change it during process ....

@wkollernhm 
@heimor 

please test.

**Comment by mindcatch-com** [comment]
see config_prod.php

**Comment by wkollernhm** [comment]
Even if there is a default selection in the preference, no mods:accessCondition is written. The list has to be saved at least once.

The tool should automatically pick the default-selection from the preferences if there is no IPR-info associated to an individual item.

**Comment by mindcatch-com** [comment]
what the hell, i tested this and i write defaults and defaults to content ... hmm i will check again

**Comment by wkollernhm** [comment]
I'm currently re-verifying on bhl-int. Will post an update shortly.

**Comment by mindcatch-com** [comment]
can you post the output part please

**Comment by wkollernhm** [comment]
It seems to work now, at least I cannot reproduce the output. The last time I tested it (this morning) I received a message similar to "IPR information missing, please select it and save at least once).

Anway -> closed.

**Comment by mindcatch-com** [comment]
i deployed last night at 2:00 am 
i think the jenkins job has a problem? database deploy fails sometimes?

**Comment by wkollernhm** [comment]
The PI-tool is a parametrized job, which means it needs to be invoked manually by supplying those parameters. I've created an issue (#381) and assigned it to Zheng in order to change / clarify this.
