### ISSUE TITLE
http://bhl-int.nhm.ac.uk/preingest/

### ISSUE THREAD

**Issue by mindcatch-com** [gbhl/bhl-europe#380]
http://bhl-int.nhm.ac.uk/preingest/

not working since yesterday i need it to test
and when it works it kills my testdata....

can you disable auto deploy for this server?

@heimor
@wkollernhm

**Comment by wkollernhm** [comment]
Integration is used for continuous integration. Therefor auto-deployment will take place there.

**Comment by mindcatch-com** [comment]
i wrote you a mail

@wkollernhm
@heimor

**Comment by mindcatch-com** [comment]
can i help to avoid these problems by modifing the database create script ???
or 
only using the update (alter) database script for jenkins?

@wkollernhm
@heimor

**Comment by mindcatch-com** [comment]
@wkollernhm
@heimor

again the database problem occurs, int is not useable !!!!
i have not changed anything on git and server. where is my
alternative test environment?

**Comment by mindcatch-com** [comment]
http://bhl-int.nhm.ac.uk/preingest/

**Comment by wkollernhm** [comment]
I've created a separate issue in order to fix this. See #381
