### ISSUE TITLE
Change Jenkins PI-tool Job to run automatically

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#381]
The current pi-tool job in jenkins is a parametrized job which means it needs to be invoked by hand (at least it seems so).

Can you please change the job so that it automatically runs without manual intervention?

**Comment by zhengl** [comment]
Jobs with parameters can be invoked automatically because they have default values.

Now the preingest job detects changes in ~/dev/pre-ingest/ingest folder (except queuing), and triggers itself. Please see [FSTrigger] - Monitor folder.

**Comment by wkollernhm** [comment]
Well. for whatever reason it doesn't seem to trigger itself even thought we monitor the correct folder. Maybe that is a problem with the FSTrigger? Can you please investigate what the problem is.

All builds so far were manually triggered by me!

**Comment by zhengl** [comment]
OK, let me check it tomorrow (Need to get some sleep now) :)
I will get back to you asap.

**Comment by wkollernhm** [comment]
Any update on this issue?

@ZhengLIAtos

**Comment by zhengl** [comment]
github-master is back to normal again (change 'Polling SCM' to 'Build when a change is pushed to GitHub')
And all the other jobs should behave.

@akohlbecker 
@chris-sleep

**Comment by wkollernhm** [comment]
I will keep this issue open until the next push, so that we can see if it really works.

**Comment by wkollernhm** [comment]
@ZhengLIAtos unfortunately the automatic triggering of the pi job still does not work. Can you please further investigate on this and fix this immediately. Thanks.

EDIT: I've now manually triggered a build - so don't be confused.

**Comment by akohlbecker** [comment]
@wkollernhm @ZhengLIAtos the last run of the pre-ingest job has been triggered automatically : http://bhle-dev-1.nhm.ac.uk/job/pre-ingest/75/, the pre-ingest-tool job is disabled. I  am unsure which job we are actually talking about since the ticket subject is on the pre-ingest-tool  job but the last comment mentions the pre-ingest job

**Comment by zhengl** [comment]
@akohlbecker 
@wkollernhm 

The pre-ingest-tool job is from AIT I think, so I disabled it.

Hmm...I have spent an hour on this annoying stuff, I just cannot understand why Jenkins triggers this job even there is NO change happened in this folder. It seems the trigger and build step are bundled together, the trigger detects the file modification during the build step, then it starts again and again. I am afraid it would be really a headache for Wolfgang and Andy if the database is re-dump every minute. (Crying for help)

**Comment by akohlbecker** [comment]
Hmm, the only cause i can imagine is that the running application is modifying files. lets's see:

```
bhladmin@bhl-int1:/mnt/nfs-demeter/dev/opt/pre-ingest/ingest$ find -mmin -10
./log
./queuing/running
```

I geuss excluding these files from the FS_trigger should cure these symptoms.
BTW we have the same problem in portal-master it is also triggered every 3 minutes the suspect files are 

```
bhladmin@bhl-int1:/mnt/nfs-demeter/dev/opt/portal$ find -mmin -10
./drupal/www/sites/default/files/languages
./drupal/www/sites/default/files/languages/fr_C9qXMasTx6OkciQh_bg9PG-kn25AhTNmR8luQoPsRjQ_192.js
./drupal/www/sites/default/files/languages/fr_C9qXMasTx6OkciQh_bg9PG-kn25AhTNmR8luQoPsRjQ_193.js
./drupal/www/sites/default/files/languages/nl_xwguQ-eXuXUQQQ9Hw7aOcc5tJ472EXTtN4GTCv89mps_186.js
./drupal/www/sites/default/files/languages/sv_U2uQPRlfCYYIhEBTK0I4eNST1rw49YTNGX1hJbrJKQs_194.js
```

**Comment by wkollernhm** [comment]
We are talking about the job "pre-ingest". How about changing the dependencies to always build whenever the main github job builds?

**Comment by akohlbecker** [comment]
this would trigger the "pre-ingest" even if only the portal is changed. 
Excluding *_/sites/default/files/languages/_.js    from the FS_trigger actually cured the  portal-master job. So we can fix the probelms in "pre-ingest" in thy same way.
Unfortunately the FS_trigger settings for "pre-ingest" are lost due to disabling the trigger, but we can use portal-master  as a template.

**Comment by akohlbecker** [comment]
I set up the FS trigger for "pre-ingest" accordingly, lets see if it is behaving now

**Comment by wkollernhm** [comment]
Thanks a lot, I will close this issue once I confirmed that it is working now.

**Comment by wkollernhm** [comment]
I've added ignores for temp and config as well, the job now seems to behave fine.
