### ISSUE TITLE
mods:genre should be a top-level element

### ISSUE THREAD

**Issue by zhengl** [gbhl/bhl-europe#382]
According to MODS schema, mods:genre should be place at top level. 
http://www.loc.gov/standards/mods/v3/mods-3-0.xsd

This causes XML validation errors during derivative generation (OLEF->MODS).

**Comment by wkollernhm** [comment]
What exactly are we talking about. Do you have any example, listing, etc.?

**Comment by zhengl** [comment]
Sorry for not having provided examples.
Please take a look at /mnt/nfs/upload/providers/testdata/spices_prepared/thirtyeightpl00mart/.aip/olef.xml
In short, mods:genre should not be placed under mods:subject.

**Comment by wkollernhm** [comment]
genre is a sub-element of subject as well. Please see: http://www.loc.gov/standards/mods/v3/mods-userguide-elements.html#genre_subject

We are using the official MarcXML to MODS conversion sheet provided by loc: http://www.loc.gov/standards/mods/v3/MARC21slim2MODS3-4.xsl

You are also refering to the wrong MODS version. The most current version is http://www.loc.gov/standards/mods/v3/mods-3-4.xsd
