### ISSUE TITLE
Maintain relations between serial levels

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#385]
Relations between each serial level should be maintained using the parentGUID within the OLEF data as well as the RELS-EXT definition in the final METS output.

OLEF see: http://www.bhl-europe.eu/bhl-schema/v0.3/
RELS-EXT see: http://groups.google.com/group/bhle-tech/browse_thread/thread/39c896271f0cbef4/cd4bb048a0950bc1?hl=de&lnk=gst&q=rels

@ZhengLIAtos Please verify RELS-EXT examples for serials

@chris-sleep 
@lobajuluwa

**Comment by zhengl** [comment]
@wkollernhm 

https://github.com/bhle/bhle/tree/master/test/content-model/bhle-cmodel
(List of Content Models)

There is no example for Serial Content Model, I was presuming from the point of hierarchy, monograph and serial are the same, so each serial object just needs to indicate that it is related to bhle-cmodel:serialCModel. Please correct if I am wrong. Then I will add serialCModel to github and Fedora

**Comment by wkollernhm** [comment]
Please add a own model for serials. This is a significant difference and we should clearly indicate this.

**Comment by mindcatch-com** [comment]
tests of zheng seem to be ok, no negative feedback given

**Comment by wkollernhm** [comment]
RELS-EXT relations now seem to be written correctly. This issue can be closed.
