### ISSUE TITLE
Sorting of files incorrect

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#387]
Sorting of files still does not work correctly.

To clarify: ONLY the sequence should be used for sorting the files. No other criteria is required. See Issue #341 for an example of incorrectly sorted files which contain a valid sequence (and are valid named).

**Comment by mindcatch-com** [comment]
the sorting is correct but only affects olef where is the problem?

do you need the same sorting and page labels in mets also i think it is so but i can check that again?

i found no example please provide one and i can fix this immediately 
my tests are ok and only the sequence counts in the sort routine if it exists !!

**Comment by mindcatch-com** [comment]
send me the link to the exact example where it fails please.

**Comment by wkollernhm** [comment]
Log into the pre-ingest tool instance on bhl-test (http://bhl-test.nhm.ac.uk/preingest/) and login as admin (usual credentials). There review the "/VOC/VoC_namefixes" example. It is already fully processed, but when viewing the final output METS / OLEF it contains the file names in invalid order.

**Comment by wkollernhm** [comment]
sorting now works for the above example. Assuming this to be fixed.
