### ISSUE TITLE
OLEF datastream in METS is mal-formed

### ISSUE THREAD

**Issue by zhengl** [gbhl/bhl-europe#388]
In METS of 'book' objects, OLEF metadata is enclosed by a redundant <olef> tag, e.g.

< olef>
< olef:olef xmlns:olef="http://www.bhl-europe.eu/bhl-schema/v0.3/">
< olef:element>
......
< /olef:olef>
< /olef>

**Comment by mindcatch-com** [comment]
right.
this is a re-generating bug and is now fixed.

**Comment by wkollernhm** [comment]
Confirmed - this seems to be fixed now.
