### ISSUE TITLE
Storing GUID in metadata

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#389]
The minted GUID should be stored in metadata as well.

Place it in olef/element/guid (see http://www.bhl-europe.eu/bhl-schema/v0.3/#Link10)
For serials, parent-guids should be recorded as well (see http://www.bhl-europe.eu/bhl-schema/v0.3/#Link12)

EDIT: Prefix the GUID with "bhle:" for storing, so e.g. bhle:10706/a0qnk9cc

**Comment by wkollernhm** [comment]
@ZhengLIAtos 
@chris-sleep 
@lobajuluwa

**Comment by mindcatch-com** [comment]
fixed.

**Comment by zhengl** [comment]
Please re-confirm this update, I can see all messages from Preingest don't start with bhle prefix.
http://bhl-int.nhm.ac.uk/ingest/jobs/batchIngestJob

**Comment by mindcatch-com** [comment]
we can add this prefix if you want i have no problem with that !

do you/we need it there?

@heimor 
@wkollernhm

**Comment by wkollernhm** [comment]
GUID are correctly stored in metadata now.

@ZhengLIAtos what is the format of the bhle-guid you need for your ingest to process correctly?

**Comment by zhengl** [comment]
Yes

**Comment by wkollernhm** [comment]
@ZhengLIAtos thats not a yes/no questions. Are the guid now correctly reported to the ingest so that it works?

**Comment by zhengl** [comment]
Actually we are talking about two different topics.
1. I can see in OLEF olef:guid is written correctly, and there is no problem during the transformation in Access.
2. For ingest side, it is not about the GUID stored in OLEF, it is about the message sent from Preingest. It works fine.

**Comment by wkollernhm** [comment]
I was aware of that - but thanks for clarifying.
