### ISSUE TITLE
guids for serials not working

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#394]
guids of parent / own level are not written to OLEF output for serials.

See issue #389 for feature request.

**Comment by wkollernhm** [comment]
still not working as of version 1.71!

guid / parentGUID elements for top-level entry (so the serial entry) are written, but not for all other elements.

In addition the top-level entry (serial-level) has not parentGUID, therefor writing the element there makes no sense.

**Comment by wkollernhm** [comment]
this almost works now. The parentGUID element is also omitted if the section above is empty.

So if there is an empty section folder (as it is required by the PI tool) it should write the parentGUID of the serial-level folder, which is not done at the moment (no parentGUID is written at all).

Please fix.

**Comment by mindcatch-com** [comment]
fixed.

**Comment by wkollernhm** [comment]
GUID / ParentGUID are now written correctly.
