### ISSUE TITLE
taxon-finder process marked as done

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#399]
After finishing ocr-reading the taxon-finding process is marked as done immediately. By clicking on the icon taxon-finding can be queued properly and the taxon-finding process runs just fine.

However the feedback to the user is wrong, and moreover it is now possible to mark the item as read for ingest despite the fact that faxon-finding did not take place yet.

**Comment by mindcatch-com** [comment]
investigating in this ...

**Comment by mindcatch-com** [comment]
serial or monograph?

@wkollernhm

**Comment by wkollernhm** [comment]
referring to serials - monographs are working as expected.

**Comment by mindcatch-com** [comment]
thanks i have found the "problem" in between 

but i must note that each step in serials will now become successfull only if any (ALL) media parts in each level of
that serial were successfull in this step, is this ok?

@wkollernhm
@heimor

**Comment by wkollernhm** [comment]
so you mean the step has to finish successfully on all levels of the serial? If so then yes it is fine.

**Comment by mindcatch-com** [comment]
yes all levels expect these who are completely empty - these i exclude when processing for any step 
the only help as hierarchy information token

**Comment by mindcatch-com** [comment]
besides, have you still problems in sorting?

@wkollernhm

**Comment by wkollernhm** [comment]
issue resolved.

@mehrrath sorting of what?
