### ISSUE TITLE
fix nfs sharing problem

### ISSUE THREAD

**Issue by leenamba** [gbhl/bhl-europe#4]
need rwx privileges for www user. becauseep apache runs php script

**Comment by chris-sleep** [comment]
a couple questions to find a solution to this:

First of all - which location in the filesystem does the www user need to write into?
Secondly, presuming the apache is running as www-data user, is it viable to run it as bhladmin?
Thirdly - which php script (so I can take a look and confirm when the write is behaving?

thanks!

**Comment by leenamba** [comment]
@sprogerb Bernd can you respond to Chris' question?

**Comment by sprogerb** [comment]
@leenamba We don't have anything to do with this issue.

**Comment by leenamba** [comment]
OK will close issue
