### ISSUE TITLE
RELS-EXT not correctly written

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#400]
RELS-EXT content is not correctly written for serial content.

No relations to upper-level items is written and furthermore all items are marked as "monographCModel".

**Comment by wkollernhm** [comment]
See issue #385 for reference

**Comment by mindcatch-com** [comment]
this should be solved since 2 weeks +

**Comment by wkollernhm** [comment]
Models are now correctly written, including relations to  upper levels.
