### ISSUE TITLE
Bug summary of the 30 monographs as testdata

### ISSUE THREAD

**Issue by zhengl** [gbhl/bhl-europe#409]
25 monographs completed
5 failed

Bugs:
1. be-nbgb/Upload_20110930/poeppig_1841_nova_genera/.aip/bhle_10706_a08w9gk7-00002.xml
    the file field is empty, xlink:href="file://"
2. be-rmca/Monographs/Lemaire_Disricts/.aip
    No such directory
3. be-rmca//Monographs/Eberstaller_Stirnhirn/.aip/bhle_10706_a080gb6v.xml
    illegal characters in XML, mods:subTitle<<ein>> Beitrag zur Anatomie der OberflÃ¤che des Grosshirns/mods:subTitle
4. be-nbgb/Upload_20120330/NBGB095606DETO1857FLOREFUR00/.aip/bhle_10706_a0wpzgqv-00071.xml
    the file field is empty, xlink:href="file://"
5. be-nbgb/Upload_20120330/NBGB095453DEVO1885FLORECOM00/.aip/bhle_10706_a0rxwdfg.xml
    illegal characters in XML, Line 1383 </results>g>Rhodora canadensis

@wkollernhm 
@mehrrath 
@chris-sleep

**Comment by wkollernhm** [comment]
3 & 5 should be fixed, the PI tool now uses the DOMDocument extension of PHP to handle the OLEF import (which automatically escapes all entities).

**Comment by wkollernhm** [comment]
ad 2.: the be-rmca/Monographs/Lemaire_Disricts/.aip directory exists. May you check this again please?

**Comment by wkollernhm** [comment]
ad 1.: PDFs do not fully work yet. This seems to be a xml file from a previous version which is not valid anymore.

**Comment by wkollernhm** [comment]
ad 4.: this upload contains a invalid file numbering scheme, most probably that is causing the error. The tool now warns the user when such errors occurs.

**Comment by zhengl** [comment]
OK, it works. Thank you Chris.

2012/4/27 Chris Sleep <
reply@reply.github.com
