### ISSUE TITLE
Bad resolution in book viewer

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#411]
The maximum resolution in the book viewer must be the same as provided by the CPs.

Example: http://bhl-int.nhm.ac.uk/portal/bhle-read/bhle%3A10706-a00gb5n4

@chris-sleep 
@lobajuluwa

**Comment by zhengl** [comment]
Yes, the current resolution is not so readable.

Actually, the resolution is reduced twice during the procedure in Access. The first time is from TIFF to JP2000, the maximum I set is 1920 \* 1920. The second time is by Djatoka, dynamically. So I think, I can raise the resolution by changing the parameters in djatoka for a better display. However, making the booreader have the same maximum resolution as the content provided by CPs is a new requirement indeed.

Here is a example to show the result of improving resoliution:
the current resolution:
http://bhl-int.nhm.ac.uk/adore-djatoka/resolver?url_ver=Z39.88-2004&rft_id=http://bhl-int.nhm.ac.uk/static/a00gb5n4/jp2/a00gb5n4_00036.jp2&svc_id=info:lanl-repo/svc/getRegion&svc.format=image/jpeg&svc_val_fmt=info:ofi/fmt:kev:mtx:jpeg2000&svc.level=3

the improved one:
http://bhl-int.nhm.ac.uk/adore-djatoka/resolver?url_ver=Z39.88-2004&rft_id=http://bhl-int.nhm.ac.uk/static/a00gb5n4/jp2/a00gb5n4_00036.jp2&svc_id=info:lanl-repo/svc/getRegion&svc.format=image/jpeg&svc_val_fmt=info:ofi/fmt:kev:mtx:jpeg2000&svc.level=5

Please comment.

**Comment by wkollernhm** [comment]
When was it decided to downsize the images for the bookviewer? To my understanding it is the job of djatoka to dynamically create tiles / images in the correct resolution (thats after all the job of an image server)?

**Comment by zhengl** [comment]
Although in my opinion reducing the resolution of TIFF to JP2000 can benefit the storage space and performance, if it is agreed to keep the original size, I can fix it. For the Djatoka side, I had some tests before and I could see it is better to have a higher resolution by default, then zooming out is actually displaying the same image, rather than generating a new image by the image server.

Well, in short, dynamic resolution is possible, but at the cost of user experience.

@ZhaoyuLIAtos

**Comment by wkollernhm** [comment]
I'm still not sure that I understand you correctly. My impression is, that djatoka should do the job of handling the different resolutions / zoom levels. Maybe chris / heimo can provide input here?

@chris-sleep 
@heimor

**Comment by chris-sleep** [comment]
Aren't you both saying the same thing?

http://bhl-int.nhm.ac.uk/adore-djatoka/resolver?url_ver=Z39.88-2004&rft_id=http://bhl-int.nhm.ac.uk/static/a00gb5n4/jp2/a00gb5n4_00036.jp2&svc_id=info:lanl-repo/svc/getRegion&svc.format=image/jpeg&svc_val_fmt=info:ofi/fmt:kev:mtx:jpeg2000&svc.level=3

the improved one:
http://bhl-int.nhm.ac.uk/adore-djatoka/resolver?url_ver=Z39.88-2004&rft_id=http://bhl-int.nhm.ac.uk/static/a00gb5n4/jp2/a00gb5n4_00036.jp2&svc_id=info:lanl-repo/svc/getRegion&svc.format=image/jpeg&svc_val_fmt=info:ofi/fmt:kev:mtx:jpeg2000&svc.level=5

both use the same base image: http://bhl-int.nhm.ac.uk/static/a00gb5n4/jp2/a00gb5n4_00036.jp2

where the zoom/resolution factor can be changed by amending svc.level value.

although - I think a maximum resolution on the .jp2 does make sense; as the image still needs to be scaled up and down, and I'm not sure having 100+Mb tiffs converted to similar sized .jp2 will be the best user experience.  I'll need to check the details to see if we agree to serve out the original maximum scan resolution images. 

@ZhengLIAtos 
@wkollernhm

**Comment by wkollernhm** [comment]
Well then there was a misunderstanding from my side. I thought that the BookViewer automatically requests new scaled images from djatoka when the user zooms in. If we have to stick to once fixed, pre-defined resolution then we should use something higher but of course not the max resolution.
Am I right with this?

**Comment by chris-sleep** [comment]
I believe you're right; but I'll offer Zheng the last word in case I'm wrong.

looking at the viewer as it stands at the moment, I think we would want svc.level=5 as a default, so that the pages served are readable; svc.level=3 doesn't reach that standard I think

**Comment by wkollernhm** [comment]
Actually I was under the impression that djatoka is used for exactly that. So zooming in / out should be handled by the djatoka image server. But it seems as it the IA-BookViewer doesn't support this. Lets stick to src.level=5 as chris suggested.

**Comment by wkollernhm** [comment]
What's the status on this issue?

A recently ingested item ( http://bhl-int.nhm.ac.uk/portal/bhle-read/bhle%3A10706-a0xwdbw2 ) still has the bad resolution.

**Comment by zhengl** [comment]
It's updated to a higher level in Djatoka.

I can see the original copies in fedora have very bad resolution. (e.g. http://bhl-int.nhm.ac.uk/fedora/objects/bhle%3A10706-a0xwdbw2-00002/datastreams/TIFF/content)

**Comment by wkollernhm** [comment]
You are right, we are now using the PDFs directly to extract the images from there. They provide way better resolution and high quality images.
