### ISSUE TITLE
facet for Material type errors

### ISSUE THREAD

**Issue by chris-sleep** [gbhl/bhl-europe#413]
If I choose to search for title: \* then pick a material type facet; using the serial type as an example,  I see
- (53) Title + Author + Year AND
  serial (3) OntentType

OntentType appears to be missing a C..  I can then not remove this facet nor add any others, and if I expand edit search, I see this field marked as Title..

**Comment by akohlbecker** [comment]
i fixed these issues, changes will be committed today

**Comment by akohlbecker** [comment]
fixed
