### ISSUE TITLE
1.1.11 - Search for ID / URL of document (now Advanced Search 1.2.17)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#43]
Search by URL, ID.

Precondition: stable URL/ID

**Comment by zhengl** [comment]
Need more specification. 
For all digital objects in Fedora, the URLs and IDs (GUID) are stable. If we want to search for ID/URL, they should be indexed by Solr in the Portal part after the ingest process is finish.

Since this is a functionality of search, in my opinion, should we take this?

**Comment by lobajuluwa** [comment]
this will be a solr implementation, but depends on fedora side before it can be implemented

**Comment by janahoffmann** [comment]
@ZhengLiAtos I think this sounds like the way to go, but will be applied for the advanced search then. If we predefine the search categories in simple search to author, title, year and taxon, we have to move this to the advanced search (see description). It should be possible that the user just copy/pastes a string with the BHL-Europe URL (from a different source for example) and finds the content directly. This needs to be either an additional metadata field or a separate search box in advanced search .

**Comment by akohlbecker** [comment]
Depends also on the pre-ingest, since the GUIDs will be added to the metadata during this step. 
So this feature will most probably not be finished  for the November sub release.

**Comment by JiriFrank** [comment]
Implemented but not functional.

**Comment by akohlbecker** [comment]
Search for ID fixed with 8015511 AND forking of new ticket for "Search for URL of document" since document URLs are not yet available in metadata : #407
