### ISSUE TITLE
Newly ingested content doesn't have derivates

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#439]
I've just test-ingested a single content from LANDOOE. The PI-process went fine, the Ingest process finished successfully. The re-indexing worked and the item appeared on the portal.

However all derivates are missing and trying to open the book in the bookviewer results in an error.

The example I used is http://bhl-int.nhm.ac.uk/portal/bhle-view/bhle%3A10706-a02ngf2n

The fully automated ingest process is supposed to work, what's missing here?

**Comment by zhengl** [comment]
Well, the same old reason.

http://bhl-int.nhm.ac.uk/static/a02ngf2n/a02ngf2n_olef.xml
Namespace prefix xsi for schemaLocation on olef is not defined

**Comment by wkollernhm** [comment]
Well that's a problem of the extraction process. Since the complete METS file contains the correct XSI declaration, which is sent to access. However it seems as if the extraction process messes up the namespaces (by fedora). If you look at the complete ObjectXML it is valid inside fedora (http://bhl-int.nhm.ac.uk/fedora/objects/bhle%3A10706-a02ngf2n/objectXML), but it seems to mess up the namespace prefixes for the extracted datastream: http://bhl-int.nhm.ac.uk/fedora/objects/bhle%3A10706-a02ngf2n/datastreams/OLEF/content

See the METS file at /mnt/nfs/upload/providers/at-landoe/9/93/.aip/bhle_10706_a02ngf2n.xml - it contains the valid XSI namespace-prefix declaration, but it is moved up the DOM-tree to avoid declaring the same prefix twice (which would be valid, but isn't done for optimization).
You can see the original OLEF file at /mnt/nfs/upload/providers/at-landoe/9/93/.aip/olef.xml (which contains the complete valid OLEF).

So this is actually a fedora problem when extracting the datastreams - not sure what we can do about it? The only possibility I see right now is to force redeclaring the same namespace with the same prefix (so avoid optimization of duplicate namespace prefixes).
Any other ideas?

**Comment by wkollernhm** [comment]
Okay I've updated the PI-tool to include the xsi namespace declaration no matter what the actual content says. This is the only reliable way I can think of to avoid this problem.

I've done so and did another ingest with some new content, still the item appears but the book-reader doesn't show up. And the OLEF is now valid.

Find it here: http://bhl-int.nhm.ac.uk/fedora/objects/bhle%3A10706-a0xwdbw2/datastreams/OLEF/content
And here the reader: http://bhl-int.nhm.ac.uk/portal/bhle-read/bhle%3A10706-a0xwdbw2

**Comment by ZhaoyuLI** [comment]
Thank you for you work, I will check what happens with this book

2012/5/3 wkollernhm <
reply@reply.github.com

> Okay I've updated the PI-tool to include the xsi namespace declaration no
> matter what the actual content says. This is the only reliable way I can
> think of to avoid this problem.
> 
> I've done so and did another ingest with some new content, still the item
> appears but the book-reader doesn't show up. And the OLEF is now valid.
> 
> Find it here:
> http://bhl-int.nhm.ac.uk/fedora/objects/bhle%3A10706-a0xwdbw2/datastreams/OLEF/content
> And here the reader:
> http://bhl-int.nhm.ac.uk/portal/bhle-read/bhle%3A10706-a0xwdbw2
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bhle/bhle/issues/439#issuecomment-5485228

## 

Bien cordialement,

Zhaoyu LI¡¶lizhaoyu86@gmail.com¡·
Contact£º (0)641799337

**Comment by ZhaoyuLI** [comment]
The server crash, so the generation didn't finish. I restart tomcat and restart the job, now the book is available on book reader

**Comment by wkollernhm** [comment]
Can we add some kind of watchdog script for this? or is it somewhere documented how to find out if a service has crashed and how to restart it?
