### ISSUE TITLE
Common name

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#450]
Common name search is not working

on int even on test.

Try as test term - Alder

related feature #256 #74

**Comment by JiriFrank** [comment]
@chris-sleep 
@wkollernhm 

Chris add please closer description what did you find. 
Wolfgang can you have a look on it please?

**Comment by wkollernhm** [comment]
The reason for this is quite simple - andreas removed the appropriate field from the solr config in this commit:

https://github.com/bhle/bhle/commit/eee975e621dbcae82b315bcc022673839a074972

I'm going to re-add the correct field and commit it in a few minutes...

**Comment by wkollernhm** [comment]
I've re-added the index field, please check if it works.

**Comment by chris-sleep** [comment]
confirmed now back to expected function, thanks
