### ISSUE TITLE
First page is not correctly ingested

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#472]
For serial content, the first page of a volume is not correctly ingested (the METS file is not generated).

See S7391 of at-landooe for an example.

**Comment by wkollernhm** [comment]
@chris-sleep 
This should now be fixed.

**Comment by chris-sleep** [comment]
great - testing now with S1243 on integration, thanks

**Comment by wkollernhm** [comment]
doing the same with S4.

**Comment by chris-sleep** [comment]
S1243 complete and ingested to integration: confirmed mets for first page now generated and page appearing correctly, with thumbnail.

related issue #474 is that for this content both the thumbnail and placeholder icons are being rendered,
