### ISSUE TITLE
1.2.7 - Search for journal acronyms (Advanced Search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#50]
Search for acronym of journal title, e.g. Organisms Diversity and Evolution = ODE. There are various acronyms for journals. Using a webservice for search term amplification...

Precondition: 
Index of journal titles (including acronyms and various spellings), see: http://www.mainlib.uwi.tt/divisions/eps/guides/epsjournalabbguide.pdf
http://www.bioscience.org/atlases/jourabbr/list.htm

**Comment by janahoffmann** [comment]
Please, explain why you closed this issue. It is not functional in the BHL-Europe portal.
It requires integration of web services or other resources.

**Comment by lobajuluwa** [comment]
Thanks for re-opening this issue Jana. We moved it to the Nov sub Release and must've closed it by mistake!

**Comment by lobajuluwa** [comment]
Further investigation is required - NHMW

**Comment by heimor** [comment]
@lobajuluwa
ZDB has been contacted and is open to provide their webservices for use in BHL-E

next step after return from Wolfgang include their webservices as a DM (#rupal-#odule)   =))

apart from the core of this feature: 
further discussion needed with respect to possible deduplication issues and mappings to GRIB records to enable display of one journal title [incl. abbreviation(s)] in the portal and all scanned material ( vols., articles, etc.) under one single heading

ZDB could be utilized for they provide manual editorial working power for deduplicating journal titles

**Comment by heimor** [comment]
@wkollernhm
more reference lists would be out there

e.g. BPH for botanical journal titles - BHL US never got hands on their services - they were not willing to help / collaborate

more investigation needed here !

**Comment by janahoffmann** [comment]
This refers also to my comment in #49. Is there any progress?
@wkollernhm

**Comment by wkollernhm** [comment]
Not yet, as we did not research on reliable external services which provide journal acronyms list so far. At the moment simple & advanced search is focused on - however this feature can be easily integrated later on.

**Comment by janahoffmann** [comment]
@wkollernhm
Good. I am looking forward to it...
What about the ZDB, they do provide acronyms, don't they?

**Comment by wkollernhm** [comment]
After some communication with the ZDB I can confirm that they offer both abbreviated titles and codes for journals.
Details on this can be found here (WARNING: German content ahead):

http://www.zeitschriftendatenbank.de/erschliessung/arbeitsunterlagen/zeta/2200/
http://www.zeitschriftendatenbank.de/erschliessung/arbeitsunterlagen/zeta/3232/

Our service module will query for both and return any found titles.

**Comment by wkollernhm** [comment]
This is now implemented.
