### ISSUE TITLE
1.2.9 - Search within previous search results (Advanced Search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#52]
Search within previous results with new/ different parameters, not ‘filter search results’

**Comment by lobajuluwa** [comment]
Update from Portal Review workshop, The Hague: previously on AIT to-do list. Now reassigned to CS.
Moved to next Milestone Release - Nov. (tbc).

**Comment by janahoffmann** [comment]
In case we still plan to implement this we need a check box 'search in serach results' or similar. 
@jirifrank

**Comment by JiriFrank** [comment]
@janahoffmann
@lobajuluwa
I not fully understand what this option means. I see the solution with combination of my query which is actually my saved previous search result. I can load it and modify the search by new/different parameters. This is one of the reasons why we have save query option.

**Comment by lobajuluwa** [comment]
Recent modifications made to search facilities: header/nav will shrink for adv search; result list will appear under search (which will be collapsed to link where step back button sits. )

**Comment by JiriFrank** [comment]
Yes, this task will be solved by integration of result list in to Advanced search (same for Browse), so the user can easily change his search parameters, search terms or use previously sets parameters for new search. In browse integration can user switch between all browse parameters and not leave for that the result list. In combination with facet list we will have amazing search functionality =)

**Comment by JiriFrank** [comment]
Done and ready for testing.

**Comment by JiriFrank** [comment]
1.2.9 - Search within previous search results (Advanced Search)

COR number: 1.2.9
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Browse

Description:

Search within previous results with new/ different parameters, not ‘filter search results’
Edit search function in result list.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
1.2.9 - Search within previous search results (Advanced Search)

COR number: 1.2.9
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Browse

Description:

Search within previous results with new/ different parameters, not ‘filter search results’
Edit search function in result list.

---

@GregKenicer
@GeoffHarper
@KasiaGoral
@MartinaMetzger
@DanielFisher
@NeilWoodcock
@SaraPerzley
@SaraCarlton
@HannaKoivula
@PaiviLipsanen

**Comment by JiriFrank** [comment]
1.2.9 - Search within previous search results (Advanced Search)

COR number: 1.2.9
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Browse

Description:

Search within previous results with new/ different parameters, not ‘filter search results’
Edit search function in result list.

---

@PaiviJaakkola
@SiniKarki
@TiinaOnttonen

**Comment by HenningScholz** [comment]
This is a bit difficult to understand, what should be tested, but the way I understand it works fine...next one.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Do 12.04.2012 17:40
An: Scholz, Henning
Betreff: Re: [bhle] 1.2.9 - Search within previous search results (Advanced Search) (#52)

1.2.9 - Search within previous search results (Advanced Search)

COR number: 1.2.9
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Browse

Description:

Search within previous results with new/ different parameters, not 'filter search results'
Edit search function in result list.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by LarissaS** [comment]
It works but I find interface of advanced search not really user-friendly!

-----Original Message-----

**Comment by RalfH** [comment]
It works fine (hopefully, I have tested what you were asking for).

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Donnerstag, 12. April 2012 17:41
An: Hand, Ralf
Betreff: Re: [bhle] 1.2.9 - Search within previous search results (Advanced Search) (#52)

1.2.9 - Search within previous search results (Advanced Search)

COR number: 1.2.9
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Browse

Description:

Search within previous results with new/ different parameters, not 'filter search results'
Edit search function in result list.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by KasiaGoral** [comment]
No too sure what you mean by 'different parameters' - should I change my
search settings from e.g. 'scientific name' to 'author'?

If yes, search works fine. Noticed that scientific name searched with
parameter 'common name' still works.

**Comment by AnneSch** [comment]
Works fine. 

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Do 12.04.2012 17:40
An: Scholz, Annemarie
Betreff: Re: [bhle] 1.2.9 - Search within previous search results (Advanced Search) (#52)

1.2.9 - Search within previous search results (Advanced Search)

COR number: 1.2.9
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Browse

Description:

Search within previous results with new/ different parameters, not 'filter search results'
Edit search function in result list.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
Ready for close.
