### ISSUE TITLE
1.2.11 - Search for words/ names in document

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#54]
Live search in OCR document in content viewer. 

Precondition: OCR of documents, performance?

**Comment by leenamba** [comment]
Two options:
1. Search for a character string and then it is highlighted in an overlay of the OCR on the image of the book.  For this the coordinates of the OCR text as well as the OCR text must be provided to the Book Viewer.  The OCR text and coordinates should be provided by the same OCR process, either by the Content Providers, Pre-ingest, or Ingest.
2. Search for a character string and then the page numbers where that character string was found is returned.  For this only the OCR text is required for the Book Viewer.

**Comment by zhengl** [comment]
Option 2 is done.

A live example:
http://bhle-dev-1.nhm.ac.uk/fedora/objects/demo%3Adarwin/methods/demo%3AbookSdef/bookreader?ui=#page/1/mode/1up

You can search multiple words separated by SPACE

**Comment by leenamba** [comment]
@jirifrank

**Comment by lobajuluwa** [comment]
Can only do option 2 for Nov Release, Option 1 has preconditions on OCR(.There has been no discussion about performance so far?)

**Comment by janahoffmann** [comment]
Option 1 should be the one to go until the end of the project. Should we then really close this issue? Or do we wait for the feedback of the testers and leave it in the testing milestone?

**Comment by lobajuluwa** [comment]
I agree, I think we should keep it open. Let me confirm with Mr Namba!
@Leenamba
@janahoffmann

**Comment by JiriFrank** [comment]
1.2.11 - Search for words/ names in document

COR number: 1.2.11
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Live search in OCR document in content viewer, “Search inside”.

You can reach the content viewer by click on Read book in result list.
The Content viewer is connected with the portal but net yet integrated on the portal. This task is under developing and is related also with taxon finder uBio and table of content. The result will be similar as it is on BHL US portal. e.g. http://www.biodiversitylibrary.org/item/49078#page/8/mode/2up

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by grahamhrbge1670** [comment]
This is working.  Have run a few search inside tests for botanical genera, eg Neottia, Cistus, and the results retrieved from a search inside are as I'd expect, checking each of the monographs retrieved.

**Comment by RalfH** [comment]
So, there is no real possibility to test at the moment. There is already a possibility to display OCR of a page but I do not understand where the "Search inside" functionality is/will to be found.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 14:04
An: Hand, Ralf
Betreff: Re: [bhle] 1.2.11 - Search for words/ names in document (#54)

1.2.11 - Search for words/ names in document

COR number: 1.2.11
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Live search in OCR document in content viewer, "Search inside".

You can reach the content viewer by click on Read book in result list.
The Content viewer is connected with the portal but net yet integrated on the portal. This task is under developing and is related also with taxon finder uBio and table of content. The result will be similar as it is on BHL US portal. e.g. http://www.biodiversitylibrary.org/item/49078#page/8/mode/2up

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
I'm not sure if I was looking at what was to be tested here.  The workflow I followed for this was: 1. Open Advanced Search: 2. Check "expand search" 3. Select Scientific Name as search parameter 4. Input name eg Neottia 5. Execute search.
In this example 3 items were retrieved.  6. Opened each of the items retrieved, one by one, using Read Book button, then in the Book viewer run a search for the search term "Neottia" using the Search inside box.  

In the completed portal am I correct to think that the second stage where you have to re-key your search term into the book viewer will not need to be done, because the "expand search" will create a listing of pages containing the scientific name searched, similar to the current workflow in BHL(US)

**Comment by JiriFrank** [comment]
1.2.11 - Search for words/ names in document

COR number: 1.2.11
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Live search in OCR document in content viewer, “Search inside”.

You can reach the content viewer by click on Read book in result list.
The Content viewer is connected with the portal but net yet integrated on the portal. This task is under developing and is related also with taxon finder uBio and table of content. The result will be similar as it is on BHL US portal. e.g. http://www.biodiversitylibrary.org/item/49078#page/8/mode/2up

@AntonioGVH
@fwelter
@LarissaS

**Comment by LarissaS** [comment]
It works, but not highlighted in the document. 
For scientific name: if I look for taxon name and see it on the page can I also enter it in uBio? I could not do it. 

-----Original Message-----

**Comment by HenningScholz** [comment]
This is a nice feature and works fine.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 14:04
An: Scholz, Henning
Betreff: Re: [bhle] 1.2.11 - Search for words/ names in document (#54)

1.2.11 - Search for words/ names in document

COR number: 1.2.11
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Live search in OCR document in content viewer, "Search inside".

You can reach the content viewer by click on Read book in result list.
The Content viewer is connected with the portal but net yet integrated on the portal. This task is under developing and is related also with taxon finder uBio and table of content. The result will be similar as it is on BHL US portal. e.g. http://www.biodiversitylibrary.org/item/49078#page/8/mode/2up

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AnneSch** [comment]
Works, but the words are not highlighted in the text. 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 14:04
An: Scholz, Annemarie
Betreff: Re: [bhle] 1.2.11 - Search for words/ names in document (#54)

1.2.11 - Search for words/ names in document

COR number: 1.2.11
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Live search in OCR document in content viewer, "Search inside".

You can reach the content viewer by click on Read book in result list.
The Content viewer is connected with the portal but net yet integrated on the portal. This task is under developing and is related also with taxon finder uBio and table of content. The result will be similar as it is on BHL US portal. e.g. http://www.biodiversitylibrary.org/item/49078#page/8/mode/2up

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AntonioGVH** [comment]
This function works very well.

The set out is brilliant.

I was searching Flora de Catalunya.

Ido not know why -at the bottom of the screen- where the hand is pointing, appear words referiing to other book dealing with Darwin.

I am including a photo of the screen.

Quoting JiriFrank:

**Comment by JiriFrank** [comment]
This feature is functional and ready for close.

@LarissaS 
@AnneSch 
New requirement arise -  Highlighting the searched term in text of Content viewer.
Issue #291

@RalfH 
The search box is on the right side of the book title in the book-viewer. "Search inside"
