### ISSUE TITLE
1.2.13 - Search with truncated  phrases (Advanced search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#56]
Search with truncated phrases with automatic wildcards at the beginning and the end of the search phrase, e.g. 

`*relle de mo*`

 should enable finding "Histoire natuRELLE DE MOllusques" but not "Histoire naturelle des annelides et mollusques". Like MS Word search function. 

Related issue/bug: #27

Connected issue: #39

**Comment by janahoffmann** [comment]
previous comments: @fwelter
Search page: Enable query mode for "relle des mo" search. 

This feature is based on the results of Question 6 of the BHL User Survey 2010
documented here: http://www.planetposter.de/bhl/wien2010.htm
"The current BHL default should be maintained as a possible option "exact letter combination in title", so that "relle des mo" could be inserted and return only extremely few results (of a title "Histoire naturelle des mollusques"). "

This issue is related to the discussion in Tervuren, 9 June 2011. In Tervuren we saw that there was no standard term used for this kind of search, and that previously used terms were misunderstood. I will adopt the term "relle des mo search" for it here.
The "relle des mo search" is the current BHL default search function and obtained a very good response in the BHL User Survey 2010, especially by frequent users, because it allows extremely efficient and quick queries. It is one of the best ways to verify in shortest time that a title is NOT contained in the dabase queried.

In Tervuren the reasonable argument arised (brought forward by AIT) that the relle des mo search function could not work parallel to other search functions in the same search box. There was a clearly pronounced "either or".

A good solution for the problem would be to offer two search boxes parallel on the same page. Something that comes close to this idea is currently shown (by coincidence, probably not deliberately) on the BHL-US search page:
http://www.biodiversitylibrary.org/
In the centre is a "long" search box, and in the upper right side there is a "short" search box (both seach boxes have exactly the same function and the same mode of search).

In OCLC designed search pages like 
http://grib.gbv.de/
(which I would recommend to use, or a portal design that comes very close to this design, see issue #24)
we have only one "long" search box, only.

BHL-Europe could provide two search boxes:
- A "long" search box at the left-side position (of the OCLC-like designed search page) with the regular default search mode (issue #25).
- A second "short search box" at the upper right side (the same position where the search box is located in the BHL-US search page) with the "relle des mo search" mode. Currently the BHL-US search page has written "Search " next to that box. This could be replaced by "Exact letter search", to show that this box offers a different mode for queries. The "short" box can be as short as in the BHL-US search page (50 % of the length of the "long" search box). More length is not needed here because the relle des mo search queries are usually shorter.

I am absolutely convinced that users would highly appreciate having two different modes of query offered at the same page. I predict that many users would use both search modes (and both modes every day), depending on the nature of their query at the time. If it would be possible to make this true, the BHL-Europe portal would provide the most efficient mode of search of all biodiversity related portals I have seen until now.

**Comment by janahoffmann** [comment]
I think we could solve this issue (in display) with different setting related to user roles. This feature could be enabled for scientific users only... (as discussed and agreed in Tervuren)

**Comment by fwelter** [comment]
1.2.13 - "urelles mot" - this is not the same requirement as "relle des mo" (to find a title containing naturelle des mollusques), as discussed in Tervuren. These are two different features.

The "relle des mo" search means that relle des mo is queried (without quotes), and only results with this exact combination of letters are returned (= the current BHL default function). A result containing a title "Histoire naturelle des annelides et mollusques" must not be found in this mode. This is the same very simple mode of search as in a MS Word file. BHL users are used to this mode.

The "urelles mot" mode as described in 1.2.13 is a different feature, it would return "naturelles mots" as well as "naturelles phrases et mots". I would consider this mode of search as of very low priority, nobody has ever asked for it.

I have the feeling that we were not talking about the same things in Tervuren.

**Comment by akohlbecker** [comment]
this issue is solved in principle by e67d46e  
The exact funtionality requested for in this issue would be to query for a whole phrase `"term1 term2 term3"` which is truncated by wildcards at the beginning and the end: `"*rm1 term2 ter*"`, but this is not possible at all in solr/lucene, however querying for `*rm1 term2 ter*` should be giving nearly the same results as expected.

So I am closing this ticket.

**Comment by chris-sleep** [comment]
for testing search with:
(where terms are term1 term2 and term3)

`*rm1 term2 ter*`

which cannot be in quotes, as wildcards inside "" are not allowed with solr/lucene

**Comment by JiriFrank** [comment]
Search with truncated phrases with automatic wildcards at the beginning and the end of the search phrase, e.g. 

`*relle de mo*`

 should enable finding "Histoire natuRELLE DE MOllusques" but not "Histoire naturelle des annelides et mollusques". Like MS Word search function. 

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment]
It works. No problems.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 14:15
An: Hand, Ralf
Betreff: Re: [bhle] 1.2.13 - Search with truncated phrases (Advanced search) (#56)

Search with truncated phrases with automatic wildcards at the beginning and the end of the search phrase, e.g. 

`*relle de mo*`

 should enable finding "Histoire natuRELLE DE MOllusques" but not "Histoire naturelle des annelides et mollusques". Like MS Word search function. 

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
Search with truncated phrases with automatic wildcards at the beginning and the end of the search phrase, e.g.

`*relle de mo*`

should enable finding "Histoire natuRELLE DE MOllusques" but not "Histoire naturelle des annelides et mollusques". Like MS Word search function.

@AntonioGVH
@fwelter
@LarissaS

**Comment by HenningScholz** [comment]
This works fine.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 14:14
An: Scholz, Henning
Betreff: Re: [bhle] 1.2.13 - Search with truncated phrases (Advanced search) (#56)

Search with truncated phrases with automatic wildcards at the beginning and the end of the search phrase, e.g.

`*relle de mo*`

 should enable finding "Histoire natuRELLE DE MOllusques" but not "Histoire naturelle des annelides et mollusques". Like MS Word search function.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AnneSch** [comment]
Works. 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 14:15
An: Scholz, Annemarie
Betreff: Re: [bhle] 1.2.13 - Search with truncated phrases (Advanced search) (#56)

Search with truncated phrases with automatic wildcards at the beginning and the end of the search phrase, e.g. 

`*relle de mo*`

 should enable finding "Histoire natuRELLE DE MOllusques" but not "Histoire naturelle des annelides et mollusques". Like MS Word search function. 

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AntonioGVH** [comment]
This feature seems very robust.

I have been searching for _numeració y descripció_ ;\* numeraciò y descripció\* [diacritic different in numeracio]; _ó y des_ and I have always found the correct answer.

Quoting JiriFrank:

**Comment by JiriFrank** [comment]
Works!
