### ISSUE TITLE
1.4.1a - Metadata fields displayed in result lists (renamed, Result list)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#61]
Updated description:
Include information on the following metadata per item in the result list:
(1) Journals (single volumes): title of journal, (title of volume), publisher, place of publication, publishing date (start year) 
(2)Journal article: article title, author, year, journal title/ volume/ page range, (content provider?)
(3)Monograph: title,  author, year, content provider

General requirements:
List sorted by title (automatically)
Numeration of results
Hyperlink (title) links to metadata view

Precondition:
Annotation of content type

Connected issues: #239, #240, #241

Related bugs: #190

Previous description::
List results of search: 
- one link per item for direct download or redirection to content viewer (e.g. like in Wiki: thumbnail for pdf + link to book viewer) 
- indicate different types of resource items (image: journal, volume, monograph) or
- status (digitized and not digitized)
- reduced number of lines per item (various options)
- no thumbnails views required
- show information on contributor (optional)

Preconditions:
integration of GRIB (scan status), content viewer, annotation of content type, linked information about content provider

**Comment by janahoffmann** [comment]
previous comment:
fwelter
Long titles should be cut if they contain text that covers more than 2 lines space in the list of results. 
Cut the length of the title to a standard value of maximum 200 characters.

**Comment by janahoffmann** [comment]
previous comment:
fwelter
In the BHL User Survey the participants gave relatively clear guidelines for designing the list of results (search results, query results). I think it will be useful to do it as the frequent users like/need to have the results presented.

I give a summary for this big issue here. I do not know if it might be better to open an independent issue for every single step?

In the list of results: the author should appear above the title. After the author should appear the year (separated by space).
Below should appear the title of the work. After the title a full stop should be added if a full stop or question mark is not contained in the original data.
The last line should be the contributor (provider of the digitised files). Full stop is not needed here.

Journal articles (see issue 5 for the icon issue)
If the result shows a journal article, the name of the journal/serial/periodical should appear in an extra line below the title and above the contributor. 
The number of the journal volume should be set behind the name of the journal (separated by a space). The pages (first page hyphen last page) should appear after the journal volume (separated by doppelpunkt and space). (doppelpunkt is this :)

Example how to do it:
http://test111.ait.co.at/?q=advanced_search_view/%7B%21lucene%7DInsecta%20Suecica&language=en
Sort by title and take hit No. 3

Currently it is shown in this form (I just copied and pasted the result, SumatraZoologische in the current version is truely spelled as one word without return or space, presumably a bug):
- A "new" Nitidulid Beetle from SumatraZoologische Mededelingen
- Jong, de C.
  *
- NCB Naturalis
  It should be shown in the following form:

Jong, de C. 1953
A "new" Nitidulid Beetle from Sumatra
Zoologische Mededelingen 32: 43-47
NCB Naturalis

Example for monographs (Hit No. 1 in the query above):

Currently shown:
- 2nd meeting of the European stag beetle group
- Smit J.T.
  *
- NCB Naturalis
  Should be in this form:

Smit J.T. 2009
2nd meeting of the European stag beetle group
NCB Naturalis

This will be quite exactly the form bioscientists are used to read, understand and cite publications. If we can show the hits cited in this form, we will have gone a great step beyond, towards a really professional bioscientific web service.

**Comment by fwelter** [comment]
See #65 for display of scan quality and metadata quality in list of search results.

**Comment by lobajuluwa** [comment]
Developer yet to be assigned for Portal work required for GRIB Integration. Boris will create separate Project task Issues i.e Preconditions and link them to relevant features in GitHub. Nov Release timeline for GRIB Integration is dependent on GRIB being successfully tested by October 14th (deadline given by Boris Jacob).

**Comment by janahoffmann** [comment]
@lobajuluwa:
This issue needs to be assigned to a developer.
Please remove the GRIB label.
@chris-sleep - nd to discuss with Chris before assigning to developer.

**Comment by janahoffmann** [comment]
@jirifrank
How do we deal with very long titles, authors lists, etc. ? Is there a treshold for the title or any other category...? e.g. only 100 letters..

**Comment by JiriFrank** [comment]
@janahoffmann
For the titles I will keep in the list view the whole title.  You can see it here http://design.mydev.cz/UIbhleDev/search_result1.html

Longer title in table view and others metadata fields could be hidden when they cross two lines.
http://design.mydev.cz/UIbhleDev/search_result2.html
It is a mouse over option and will expand the original length.

**Comment by akohlbecker** [comment]
Update to latest decisions:
1. Metadata fields in result list (constant 4 metadata fields) 

a. Journal (serials)
a.i. title (which is a journal title actually)
a.ii. name of publisher
a.iii. place of publication
a.iv. publishing date (start year)

b. Others/Unknown
b.i. Title 
b.ii. author/publisher
b.iii. year
b.iv. content provider 

c. Journal article
c.i. title
c.ii. author
c.iii. year
c.iv. journal title / volume / page range (multiple metadata field in one line)

d. monograph (book)
d.i. title
d.ii. author
d.iii. year
d.iv. content provider

**Comment by JiriFrank** [comment]
1.4.1a - Metadata fields displayed in result lists (renamed, Result list)

COR number: 1.2.13
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Description:

(1) Journals (single volumes): title of journal, (title of volume), publisher, place of publication, publishing date (start year) 

(2)Journal article: article title, author, year, journal title/ volume/ page range, (content provider)

(3)Monograph: title, author, year, content provider

In the testing portal it is possible to test just the (3) Monograph at the moment. 

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment]
It works as regards point (3). But the list does show "publisher" not "content provider". Anyway, is does make more sense and it may be erroneous?

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:02
An: Hand, Ralf
Betreff: Re: [bhle] 1.4.1a - Metadata fields displayed in result lists (renamed, Result list) (#61)

1.4.1a - Metadata fields displayed in result lists (renamed, Result list)

COR number: 1.2.13
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Description:

(1) Journals (single volumes): title of journal, (title of volume), publisher, place of publication, publishing date (start year) 

(2)Journal article: article title, author, year, journal title/ volume/ page range, (content provider)

(3)Monograph: title, author, year, content provider

In the testing portal it is possible to test just the (3) Monograph at the moment. 

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
1.4.1a - Metadata fields displayed in result lists (renamed, Result list)

COR number: 1.4.1a
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Description:

(1) Journals (single volumes): title of journal, (title of volume), publisher, place of publication, publishing date (start year)

(2)Journal article: article title, author, year, journal title/ volume/ page range, (content provider)

(3)Monograph: title, author, year, content provider

In the testing portal it is possible to test just the (3) Monograph at the moment.

@AntonioGVH
@fwelter
@LarissaS

**Comment by HenningScholz** [comment]
This seams to work, but it needs to be re-tested after the first real OLEF data are ingested.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 15:02
An: Scholz, Henning
Betreff: Re: [bhle] 1.4.1a - Metadata fields displayed in result lists (renamed, Result list) (#61)

1.4.1a - Metadata fields displayed in result lists (renamed, Result list)

COR number: 1.2.13
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Description:

(1) Journals (single volumes): title of journal, (title of volume), publisher, place of publication, publishing date (start year)

(2)Journal article: article title, author, year, journal title/ volume/ page range, (content provider)

(3)Monograph: title, author, year, content provider

In the testing portal it is possible to test just the (3) Monograph at the moment.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AntonioGVH** [comment]
This feature works perfect.

I have tried it with several books from the excel list.

Quoting JiriFrank:

**Comment by AnneSch** [comment]
Works well with separate books from the list. 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:02
An: Scholz, Annemarie
Betreff: Re: [bhle] 1.4.1a - Metadata fields displayed in result lists (renamed, Result list) (#61)

1.4.1a - Metadata fields displayed in result lists (renamed, Result list)

COR number: 1.2.13
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Description:

(1) Journals (single volumes): title of journal, (title of volume), publisher, place of publication, publishing date (start year) 

(2)Journal article: article title, author, year, journal title/ volume/ page range, (content provider)

(3)Monograph: title, author, year, content provider

In the testing portal it is possible to test just the (3) Monograph at the moment. 

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
Works for content type - monograph/book

Need to be tested again with more content types.

In monograph is displayed publisher instead of content provider - open for discussion.
