### ISSUE TITLE
1.4.4. - Display results per category or facet list

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#64]
Display results per category: author, title, year, taxon

for example: Search term "mouse"

author: 0 results
title: 1456 results
year: 0 results
taxon: 50 results

Precondition: Define a list of facets/ categories

Final decission after The Hague meeting:

Criteria for facet list:
• function of sort by criteria with combination of filter results
• main heading of facet items
       o    Material type: serial (Journal), article, monograph – sort result by category
       o    Author name: sort results alphabetically
       o    Date (Publishing date): sort results numerically (date of publishing)
       o    Language: (language of the book) – sort results by category
       o    Content provider - sort results by category
• all headings will be always displayed
• under each heading will be result unknown for the case that the metadata field of the content is not specified
• all headings will be extendable, for case that there will be long list of results items

Design of the facet list is task for the portal design developmnet.

**Comment by fwelter** [comment]
"year" should only be displayed if a numeral was part of the search query. "mouse" cannot be a year, so no need to display "year: 0 results"

**Comment by janahoffmann** [comment]
@fwelter I agree for the years but what it with the author ;-) There could be an author with the name 'mouse'...This example was used to illustrate the result structure. I think all the categories should be displayed all the time...but this are just very minor changed and can be discusse while testing. It is important that the developers understand the general idea.

**Comment by fwelter** [comment]
Yes of course, I understood, no problem. Just to keep this detail in mind.

**Comment by janahoffmann** [comment]
This is now one issue together with #62. 

@lobajuluwa
Can we close this issue as it is the same as #62 now? Who will be assigned to this tasks Andreas or Atos?

#64 is assigned to the testing core release... #62 Nov sub release...should we change then the #62 to the Nov sub release?

**Comment by lobajuluwa** [comment]
Yes, #62 should be in the Nov Sub release since the revised feature needs to be picked up for testing. I will close this issue and cc Andreas. 
@akohlbecker
@janahoffmann
