### ISSUE TITLE
1.4.7 - Modify list in bibliographic basket (now 4.1.21, Community portal)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#67]
Updated description:
Modify the list of bibliographic items in bibliographic basket: 
set up different lists (name lists, e.g. 'literature on trees', 'literature of Darwin')
modification of formats (per list), e.g. Endnote, Reference Manager, library formats (Marc21, DC, maybe BibTex)

Precondition:
set up bibliographic basket
provision of metadata in Marc21, DC, etc.)
provision of metadata in Endnote, Refmanager format

Connected issue: #66

Previous description:
Modify list in bibliographic basket: modification of list formats, defined display formats, etc.

Precondition: Set up bibliographic basket

**Comment by JiriFrank** [comment]
Some parts if this task as metadata format icons will be available till the end of this week and open for testing.

**Comment by JiriFrank** [comment]
Implemented and functional.
