### ISSUE TITLE
1.4.8 - 'Batch download basket' (now 3.2.8, Content download)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#68]
Updated description:
Add items (monographs), articles, pages, ... to download basket (by click, or drag&drop)

The batch download basket shall be integrated in the content viewer to enable direct selection of the items to be downloaded. The selected items (see above) will be listed in a 'shopping basket' like environment and a batch download can be initiated any time (directly or by email or connection to ftp site...). 
By choice, the user can request to receive a compressed file (choose different compression options).
This basket only enables batch download of content, not metadata (see bibliographic basket). 
Display size of to be downloaded item. 

Under discussion: access to batch download basket from portal (not content viewer)

Precondition:
Set up batch download environment
Enable drag and drop animation if required
File size in metadata or algorithm for estimation of file size

Connected issue: #69

Previous description:
Drag&drop search results (items) to ‘batch download basket’

Precondition: Set up batch download basket

**Comment by zhengl** [comment]
I will provide the functionality of packing all requested content in a zip, but UI will also need the D&D animation.

So there must be another UI developer for this issue.

**Comment by JiriFrank** [comment]
Portal/tagging basket will include just metadata.

Content viewer basket will include various formates pdf, ocr, jpg

The content as pdf, ocr or jpg is possible download from the biblio page on the portal.
