### ISSUE TITLE
Search page - list of search results - replace thumbnails by icons

### ISSUE THREAD

**Issue by fwelter** [gbhl/bhl-europe#7]
The thumbnails at the left side of the results hits should be removed, they take too long to load in  (I experienced 10-15 sec) and contain no useful information. They should be replaced by icons, preferably in the same size and standard design as used for the GBV portals such as GVK (http://gso.gbv.de). These ions are very useful.
Icons should carry the information "monograph", "journal article", and "journal/serial".
The 3 icons corresponding to this information can be seen here:
http://gso.gbv.de/DB=2.1/SET=1/TTL=1/CMD?ACT=SRCHA&IKT=1016&SRT=YOP&TRM=insecta
Hit No. 3 ("Mit moderner Logistik die Vielfalt der Insekten erforschen") = journal article
Hit No. 4 ("Phänomen Honigbiene") = monograph
Hit No. 7 ("Latrodecta / Special") = journal/serial

**Comment by janahoffmann** [comment]
This issue is CoR feature 1.4.1. 
@fwelter

**Comment by janahoffmann** [comment]
@jirifrank Please include this in the test report for issue #61 (1.4.1).
