### ISSUE TITLE
2.1.3 - Search by author including synonyms and various spellings (Advanced search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#76]
Search by authors name (various spelling (languages), abbreviation, synonyms), 
search in authors metadata field, filter results by facet list
e.g.  Linné = Linnaeus

Precondition: Integration of VIAF web service, index of authors name in metadata and OCR text (optional)

Related issue: #185, #187

**Comment by wkollernhm** [comment]
We have now investigated the VIAF API (http://www.oclc.org/developer/services/viaf) and decided to use the OpenSearch API with XML as response format.

In order to make it more useable, we are currently implementing a drupal module which can be called by the search functions in order to expand person names.

**Comment by wkollernhm** [comment]
As of #167 the module is fully working and AIT has to integrate the function call into their search process.
Therefore this Issue is re-assigned to AIT.

**Comment by wkollernhm** [comment]
Please create a second (new) issue for integrating the viaf_lookup module into the search process.

By mentioning this issue (#76) in the description of the new issue we can keep track of the history.

**Comment by janahoffmann** [comment]
I would removed the webservice label and suggest creating a project task, we cannot close this issue before it is integrated in the system/search.

@lobajuluwa 
@wkollernhm

**Comment by lobajuluwa** [comment]
A new Issue has been created (#185) assigned to AIT for the integration of the viaf_lookup module into the search process

**Comment by janahoffmann** [comment]
We should re-open this issue, otherwise it would be ready for testing but it isn't. @lobajuluwa

**Comment by lobajuluwa** [comment]
Issue has been reopened pending completion of integration work into the search process by AIT
@janahoffmann

**Comment by lobajuluwa** [comment]
Wolfgang will now be doing the integration work rqd for VIAF_lookup modules into the overall system, upon his returns from hols.
milestone ytbd.
@wkollernhm
@janahoffmann

**Comment by lobajuluwa** [comment]
Update from Portal Review workshop, The Hague: NHMW feature is ok, needs to be hooked into drupal 7, as per above comments Wolfgang is currently working on this.

**Comment by wkollernhm** [comment]
VIAF lookup is integrated into advanced search and can be tested.

**Comment by JiriFrank** [comment]
2.1.3 - Search by author including synonyms and various spellings (Advanced search)

COR number: 2.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search by authors name (various spelling (languages), abbreviation, synonyms), 
search in authors metadata field, filter results by facet list
e.g. Linné = Linnaeus

„expand search“ function

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
2.1.3 - Search by author including synonyms and various spellings (Advanced search)

COR number: 2.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search by authors name (various spelling (languages), abbreviation, synonyms), 
search in authors metadata field, filter results by facet list
e.g. Linné = Linnaeus

„expand search“ function

@AntonioGVH
@fwelter
@LarissaS

**Comment by HenningScholz** [comment]
Although not many authors have different spellings, the one I found works fine.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 15:09
An: Scholz, Henning
Betreff: Re: [bhle] 2.1.3 - Search by author including synonyms and various spellings (Advanced search) (#76)

2.1.3 - Search by author including synonyms and various spellings (Advanced search)

COR number: 2.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search by authors name (various spelling (languages), abbreviation, synonyms),
search in authors metadata field, filter results by facet list
e.g. Linn = Linnaeus

"expand search" function

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by RalfH** [comment]
Difficult to judge because the limited selection of titles does not include tricky cases of variable authors' names. 
It would also have been useful to test such common cases such as "DC.", our botanical standard abbreviation for "de Candolle".

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:10
An: Hand, Ralf
Betreff: Re: [bhle] 2.1.3 - Search by author including synonyms and various spellings (Advanced search) (#76)

2.1.3 - Search by author including synonyms and various spellings (Advanced search)

COR number: 2.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search by authors name (various spelling (languages), abbreviation, synonyms), 
search in authors metadata field, filter results by facet list
e.g. Linné = Linnaeus

"expand search" function

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AntonioGVH** [comment]
This function seems not to work.

I asked by 'Carlos' that could be 'Carolus' or 'Charles' and didnt get any answer. Neither I get any answer with 'Linneo' that is as Linnaeus is spell in Spanish

Quoting JiriFrank:

**Comment by AntonioGVH** [comment]
Sorry for the previous email about this fuction.
I forgot to click on 'expand search'.

It works very well on proper and surnames.

Impressive!!!

Quoting JiriFrank:

**Comment by AnneSch** [comment]
Works. 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:10
An: Scholz, Annemarie
Betreff: Re: [bhle] 2.1.3 - Search by author including synonyms and various spellings (Advanced search) (#76)

2.1.3 - Search by author including synonyms and various spellings (Advanced search)

COR number: 2.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search by authors name (various spelling (languages), abbreviation, synonyms), 
search in authors metadata field, filter results by facet list
e.g. Linné = Linnaeus

"expand search" function

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AnneSch** [comment]
Works pretty well, although not many authors have different names. 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:10
An: Scholz, Annemarie
Betreff: Re: [bhle] 2.1.3 - Search by author including synonyms and various spellings (Advanced search) (#76)

2.1.3 - Search by author including synonyms and various spellings (Advanced search)

COR number: 2.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search by authors name (various spelling (languages), abbreviation, synonyms), 
search in authors metadata field, filter results by facet list
e.g. Linné = Linnaeus

"expand search" function

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by LarissaS** [comment]
It works

-----Original Message-----

**Comment by JiriFrank** [comment]
Works properly.
