### ISSUE TITLE
2.1.4 - Multilingual search for colloquial species name (Advanced search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#77]
Search by colloquial name. Extend search term in selected languages/ or other languages (available).

e.g. search for dog - indicate other languages/ all - also search for Hund, chien, etc. 
(see German prototype)

Precondition: multilingual thesauri or web services, e.g. CoL (Sp2000)

**Comment by heimor** [comment]
@lobajuluwa
no milestone set for this feature - maybe Nov Subrelease would be the right one

webservice call of Catalogue of Life and PESI sources in place -

**Comment by lobajuluwa** [comment]
@heimor
Thanks Heimo for the above info.
I've assigned this to the Nov sub release.

**Comment by lobajuluwa** [comment]
What level of translation is reqd here?

Precondition -  standard integration of web services scheduled for Nov Release.

Wolfgang has suggested this needs to be treated as 2 separate issues:-
1) Search by Colloquial name 
2) Multilingual expansion of colloquial name 

Jana pls discuss further with Wolfgang before revising Issue in CoR and updates made to Github.

@wkollernhm
@janahoffmann

**Comment by janahoffmann** [comment]
@wkollernhm
@lobalujuwa
The search by colloquial name is defined in issue #74
The search by colloquial name in various languages is this issue (multilingual expansion of colloquial names)
We already have 2 issues for this request.

**Comment by wkollernhm** [comment]
Technically searching for multilingual colloquial name and "just" colloquial name is the same process. The external webservices we use provide their common names in various languages and will always return a scientific name for them.

Therefor this issue can be closed.
