### ISSUE TITLE
Search page - list of search results - the form how to cite papers

### ISSUE THREAD

**Issue by fwelter** [gbhl/bhl-europe#8]
In the BHL User Survey the participants gave relatively clear guidelines for designing the list of results (search results, query results). I think it will be useful to do it as the frequent users like/need to have the results presented.

I give a summary for this big issue here. I do not know if it might be better to open an independent issue for every single step?

In the list of results: the author should appear above the title. After the author should appear the year (separated by space).
Below should appear the title of the work. After the title a full stop should be added if a full stop or question mark is not contained in the original data.
The last line should be the contributor (provider of the digitised files). Full stop is not needed here.

Journal articles (see issue 5 for the icon issue)
If the result shows a journal article, the name of the journal/serial/periodical should appear in an extra line below the title and above the contributor. 
The number of the journal volume should be set behind the name of the journal (separated by a space). The pages (first page hyphen last page) should appear after the journal volume (separated by doppelpunkt and space). (doppelpunkt is this :)

Example how to do it:
http://test111.ait.co.at/?q=advanced_search_view/%7B%21lucene%7DInsecta%20Suecica&language=en
Sort by title and take hit No. 3

Currently it is shown in this form (I just copied and pasted the result, SumatraZoologische in the current version is truely spelled as one word without return or space, presumably a bug):

```
* A "new" Nitidulid Beetle from SumatraZoologische Mededelingen
* Jong, de C.
*
* NCB Naturalis
```

It should be shown in the following form:

Jong, de C. 1953
A "new" Nitidulid Beetle from Sumatra
Zoologische Mededelingen 32: 43-47
NCB Naturalis

Example for monographs  (Hit No. 1 in the query above):

Currently shown:

```
* 2nd meeting of the European stag beetle group
* Smit J.T.
*
* NCB Naturalis
```

Should be in this form:

Smit J.T. 2009
2nd meeting of the European stag beetle group
NCB Naturalis

This will be quite exactly the form bioscientists are used to read, understand and cite publications. If we can show the hits cited in this form, we will have gone a great step beyond, towards a really professional bioscientific web service.

**Comment by janahoffmann** [comment]
This issue is related to CoR feature 1.4.1. Your comment will be forwarded to the test manager.
@fwelter
@jiriFrank

**Comment by janahoffmann** [comment]
now issue #61
