### ISSUE TITLE
2.1.8 - Search by geographic information, provenance (Advanced search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#81]
Search by  geographic term
e.g. Africa, Maldives, etc.

Precondition: use index of geographic information (similar to TaxonFinder for geographic names), contact P. Mergen (RMCA)/ AIT or crowd sourcing

**Comment by heimor** [comment]
too large, maybe leave out from BHL-E; too many false positives

**Comment by lobajuluwa** [comment]
Update from Portal Review Workshop_The Hague: metadata problem, same as country - March 2012 Release:- review what is available. Also need a recommendation from NHMW as to what is the sensible thing to do.
