### ISSUE TITLE
3.1.2 - View TOC of item (Content view)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#84]
Display table of contents

Precondition: Pagination (in metadata) or default pagination (pages of scanned document)

**Comment by sprogerb** [comment]
Book Viewer Issue (connected with data delivery from data providers)

**Comment by zhengl** [comment]
the prerequisite is the pagination metadata is provided in the AIP

**Comment by zhengl** [comment]
A live example is here:
http://bhle-dev-1.nhm.ac.uk/fedora/objects/demo%3Adarwin/methods/demo%3AbookSdef/bookreader?ui=#page/1/mode/1up

It is an implementation from IA Bookreader.

**Comment by leenamba** [comment]
@jirifrank

**Comment by chris-sleep** [comment]
TOC to be in frame/iframe alongside bookviewer now

**Comment by JiriFrank** [comment]
Done and ready for testing.
