### ISSUE TITLE
3.1.3 - View title of item (Content view)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#85]
Display title of item in content viewer

**Comment by lobajuluwa** [comment]
Update from Portal Review Workshop: assigned to ATOS, feature is functioning, should be tested.

**Comment by JiriFrank** [comment]
3.1.3 - View title of item (Content view)

COR number: 3.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Display title of item in content viewer

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment]
I works, but performance is perfect only using firefox. In the IE one cannot turn over the leaves of a book ...

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:17
An: Hand, Ralf
Betreff: Re: [bhle] 3.1.3 - View title of item (Content view) (#85)

3.1.3 - View title of item (Content view)

COR number: 3.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Display title of item in content viewer

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
3.1.3 - View title of item (Content view)

COR number: 3.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Display title of item in content viewer

You can reach the content viewer by click on Read book in result list.

@AntonioGVH
@fwelter
@LarissaS

**Comment by HenningScholz** [comment]
Works fine.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 15:17
An: Scholz, Henning
Betreff: Re: [bhle] 3.1.3 - View title of item (Content view) (#85)

3.1.3 - View title of item (Content view)

COR number: 3.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Display title of item in content viewer

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
Displaying title in the books I've opened using Book Reader, both in Firefox 9.0 and IE 8.0

**Comment by AntonioGVH** [comment]
Correct.

I looked for 'Flora' in simple search and all read book request gave the title in the upper left  part of the screen

Quoting JiriFrank:

**Comment by AnneSch** [comment]
Works fine in Firefox 9.0, it is not working in IE 8.0. 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:17
An: Scholz, Annemarie
Betreff: Re: [bhle] 3.1.3 - View title of item (Content view) (#85)

3.1.3 - View title of item (Content view)

COR number: 3.1.3
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Display title of item in content viewer

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
Works fine. Browsers compatibility issue will be solved in final stage of portal, because the book-viewer will be integrated to the portal.
