### ISSUE TITLE
3.1.5 - Show bibliographic information (rename, Content view)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#87]
Show bibliographic information in content viewer upon request by user
one option: refer to 'bibliographic information page' (button).

Precondition:
bibliographic information page

**Comment by lobajuluwa** [comment]
Portal Review workshop update_The Hague: BHL Australia integrated uBio more into the book viewer.

**Comment by janahoffmann** [comment]
@lobajuluwa
There must be a way to view bibliographic information from the content viewer. The simpliest solution is to refer to the bibliographic information page. Other solutions welcome...
I agree. uBio should be integrated more into the book viewer.

**Comment by JiriFrank** [comment]
@janahoffmann
@lobajuluwa
It could be displayed in the light box view. Same solution could be for the contributor. Actually these information could be displayed together.

**Comment by JiriFrank** [comment]
There will be link button to the book matadata view. Same solution will be also for the content provider information. 
Same solution is also on the Australian portal. uBio will be integrated same way as on the Australian portal.

**Comment by lobajuluwa** [comment]
Link button to book metadata view nds to be in place before Issue can be closed for testing.

**Comment by JiriFrank** [comment]
It is related to Issue #86. Is the link button also ok for CP?

**Comment by JiriFrank** [comment]
Solution could be easy, make the title of the book as a link to the book biblio. The same function is already in result list and this option is very intuitive.

**Comment by JiriFrank** [comment]
Will be done till the end of this week and updated for testing.

**Comment by JiriFrank** [comment]
Implemented and functional.
