### ISSUE TITLE
3.1.6 - Display selected page or plate listed in table of contents (Content view)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#88]
click on page, plate, etc. in TOC and display respective page - use real page numbers in document and not! number of scanned page

Precondition: Pagination of scanned item, table of contents

**Comment by JiriFrank** [comment]
In the TOC are displayed the scanned pages and not the real pages. The TOC is ready for testing.

**Comment by JiriFrank** [comment]
3.1.6 - Display selected page or plate listed in table of contents (Content view)

COR number: 3.1.6 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

click on page, plate, etc. in TOC and display respective page - use real page numbers in document and not! number of scanned page

The TOC will appear if you click on the small arrow in the middle of the left side in the content viewer. Pages in TOC are related to the scanned pages in the content viewer, but not to the real pages and illustrations in the book. We are able to display this information, but we do not have proper data at the moment. 

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
3.1.6 - Display selected page or plate listed in table of contents (Content view)

COR number: 3.1.6 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

click on page, plate, etc. in TOC and display respective page - use real page numbers in document and not! number of scanned page

The TOC will appear if you click on the small arrow in the middle of the left side in the content viewer. Pages in TOC are related to the scanned pages in the content viewer, but not to the real pages and illustrations in the book. We are able to display this information, but we do not have proper data at the moment. 

---

@GregKenicer
@GeoffHarper
@KasiaGoral
@MartinaMetzger
@DanielFisher
@NeilWoodcock
@SaraPerzley
@SaraCarlton
@HannaKoivula
@PaiviLipsanen

**Comment by JiriFrank** [comment]
3.1.6 - Display selected page or plate listed in table of contents (Content view)

COR number: 3.1.6 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

click on page, plate, etc. in TOC and display respective page - use real page numbers in document and not! number of scanned page

The TOC will appear if you click on the small arrow in the middle of the left side in the content viewer. Pages in TOC are related to the scanned pages in the content viewer, but not to the real pages and illustrations in the book. We are able to display this information, but we do not have proper data at the moment. 

---

@PaiviJaakkola
@SiniKarki
@TiinaOnttonen

**Comment by tiinaonttonen** [comment]
Antwerpsche analytische flora inhoudende - the table of content works according to the descripition. It includes Roman and Arabic numbers.

Fauna der näheren Umgebung von Bingen   - works as described  (simple numbering)

Flore élémentaire des cryptogames  - can't read at all, "note The full stack trace of the root cause is available in the Apache Tomcat/6.0.28 logs.
"

**Comment by HenningScholz** [comment]
That was a cool discovery, I have read about the ToC but never though to look for it, but it works fine. This needs to be properly explained in the tutorial, so people find it. Maybe it should even appear by default and then the user can click it away, if the user need more room to read.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Do 12.04.2012 18:43
An: Scholz, Henning
Betreff: Re: [bhle] 3.1.6 - Display selected page or plate listed in table of contents (Content view) (#88)

3.1.6 - Display selected page or plate listed in table of contents (Content view)

COR number: 3.1.6
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

click on page, plate, etc. in TOC and display respective page - use real page numbers in document and not! number of scanned page

The TOC will appear if you click on the small arrow in the middle of the left side in the content viewer. Pages in TOC are related to the scanned pages in the content viewer, but not to the real pages and illustrations in the book. We are able to display this information, but we do not have proper data at the moment.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by LarissaS** [comment]
For some books it works for other not, depends on the data available I suppose. What would be nice to see is not only number, but "page X"
"Contents", "blank page", "plate X", "index".

-----Original Message-----

**Comment by RalfH** [comment]
I works but there is a certain diversity which could confuse users.

Antwerpsche analytische flora: page numbers in panel identical to the "true" ones.

Kvetena ceskeho ...: numbers of scanned and true pages differ considerably. No indication of not paginated plates.

Obviously really a question of proper data available.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Donnerstag, 12. April 2012 18:43
An: Hand, Ralf
Betreff: Re: [bhle] 3.1.6 - Display selected page or plate listed in table of contents (Content view) (#88)

3.1.6 - Display selected page or plate listed in table of contents (Content view)

COR number: 3.1.6 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

click on page, plate, etc. in TOC and display respective page - use real page numbers in document and not! number of scanned page

The TOC will appear if you click on the small arrow in the middle of the left side in the content viewer. Pages in TOC are related to the scanned pages in the content viewer, but not to the real pages and illustrations in the book. We are able to display this information, but we do not have proper data at the moment. 

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamtestrbge** [comment]
Like Henning, I found the TOC a bit too hidden and just chanced on it - However it works, and I've noted a problem in the one RBGE book in the test, and need to follow it up, this must have to do with pagination sequencing   Checked 5 other titles:

Museo Nacional de Ciencias Naturales, page sequence does not correlate with ToC
Traite de graminees cereales - page sequence correlates with ToC
Flore elementaire des cryptogames - page sequence correlates with ToC
Les oiseaux utiles - page sequence does not correlate.  However, this is a work with coloured plates and a numbering sequence.
Vier landw. Studiengange durch... page sequence does not correlate with ToC

**Comment by KasiaGoral** [comment]
I was hard to find ToC. I checked 2 books:

The vegetation of Caithness considered in relation to the geology - page
sequence correlates with ToC, but some pages missing at the end of the book.

Vier landw. Studiengänge durch die Gemarkung Niederlahnstein und ihre
Flurdistrikte - page sequence does not correlate with ToC

**Comment by SiniKarki** [comment]
Flore élémentaire des cryptogames - ToC works. It would be useful if the ToC-box were easier to find.

(With correct page numbers can even use  the Alphabetical table of species names on page 231)

**Comment by AnneSch** [comment]
Works, after I had found the TOC... really hard to find without any hints. 

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Do 12.04.2012 18:43
An: Scholz, Annemarie
Betreff: Re: [bhle] 3.1.6 - Display selected page or plate listed in table of contents (Content view) (#88)

3.1.6 - Display selected page or plate listed in table of contents (Content view)

COR number: 3.1.6
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

click on page, plate, etc. in TOC and display respective page - use real page numbers in document and not! number of scanned page

The TOC will appear if you click on the small arrow in the middle of the left side in the content viewer. Pages in TOC are related to the scanned pages in the content viewer, but not to the real pages and illustrations in the book. We are able to display this information, but we do not have proper data at the moment.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
The TOC column will be displayed as default.

The function is working properly, depending on the data.

Ready for close.
