### ISSUE TITLE
3.1.7 - Navigate in document in content viewer (Content view)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#89]
Implement user friendly buttons:
up, down, select page, forward, backward, go back to first page, go to end of document, etc.

**Comment by fwelter** [comment]
See #83 (3.1.1) for important priority one feature: display page-level metadata scrollbox.

**Comment by JiriFrank** [comment]
See the comment in #83.

**Comment by janahoffmann** [comment]
not implemented - issues needs to be reopened

**Comment by lobajuluwa** [comment]
Update from Portal Review Workshop: page turning is implemented – should be tested.

**Comment by janahoffmann** [comment]
@lobajuluwa
The page level scollbox is implemented as suggested by Francisco? Is there a way to see this somewhere. Who to ask? Otherwise I would add this as a new feature/ feature request. see comment #83

**Comment by JiriFrank** [comment]
@lobajuluwa
@leenamba
@janahoffmann
Do we have the platform where is possible to test the book viewer or it is in the process of integration to the portal? We will need also the URL of the working bookwier for setting up the design and consult the integration. The last link is not working in last weeks. e.g. http://bhle-dev-1.nhm.ac.uk/fedora/objects/demo%3Adarwin/methods/demo%3AbookSdef/bookreader?ui=#page/1/mode/1up

**Comment by JiriFrank** [comment]
3.1.7 - Navigate in document in content viewer (Content view)

COR number: 3.1.7
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Implement user friendly buttons:
up, down, select page, forward, backward, go back to first page, go to end of document, etc.

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
3.1.7 - Navigate in document in content viewer (Content view)

COR number: 3.1.7
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Implement user friendly buttons:
up, down, select page, forward, backward, go back to first page, go to end of document, etc.

You can reach the content viewer by click on Read book in result list.

@AntonioGVH
@fwelter
@LarissaS

**Comment by LarissaS** [comment]
Works good

-----Original Message-----

**Comment by HenningScholz** [comment]
The slider at the base is not perfect. I can not move it with the mouse. The scroll bar at the right is a bit hidden, difficult to work with. Otherwise, navigation works good. I can see no big difference in performance compared to the original IA content viewer.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 15:18
An: Scholz, Henning
Betreff: Re: [bhle] 3.1.7 - Navigate in document in content viewer (Content view) (#89)

3.1.7 - Navigate in document in content viewer (Content view)

COR number: 3.1.7
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Implement user friendly buttons:
up, down, select page, forward, backward, go back to first page, go to end of document, etc.

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by RalfH** [comment]
The icons, buttons, bars and whatever are mostly selfexplanatory. I guess that newcomers need less than 1 min. to understand the basic features.

It may take a few more seconds to understand "download this book", the basket thing and its connection.

To sum up: much more userfriendlier than the BHL portal.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:18
An: Hand, Ralf
Betreff: Re: [bhle] 3.1.7 - Navigate in document in content viewer (Content view) (#89)

3.1.7 - Navigate in document in content viewer (Content view)

COR number: 3.1.7
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Implement user friendly buttons:
up, down, select page, forward, backward, go back to first page, go to end of document, etc.

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
There is an odd problem with the slider.  It already has six black arrows appearing against it, which refer to pages in a book about Darwin.  However this does not interfere with content searches, for example a search for "orang utan" in Selenka's "Menschenaffen" retrieves many references both to "orang" and "utan" in the OCR'd text: But does not combine the search term, is this something that will be possible to do doing an exact phrase search in Advanced Search when the content is linked up.  

The descriptors that appear against each function button are quite self explanatory.

Have done an internal test of share book function, and it works; but will try a test where I send a link by e-mail to a personal e-mail account, and see how that goes.

**Comment by AntonioGVH** [comment]
Navigation buttons work very well, specially search, play, pointer. 

I could not download the work I was viewing (Flora Catalunya) neither mark a page (don see any button for this in the screen)

Quoting JiriFrank:

**Comment by AntonioGVH** [comment]
Sorry for previous answer to this COR.

Mark page and download works perfectly!!

Quoting JiriFrank:

**Comment by AnneSch** [comment]
The navigation buttons are self-explanatory; this works pretty well! 

Finally, I managed to download pages! It was pretty fast, ca. 1 to 2 seconds. 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:18
An: Scholz, Annemarie
Betreff: Re: [bhle] 3.1.7 - Navigate in document in content viewer (Content view) (#89)

3.1.7 - Navigate in document in content viewer (Content view)

COR number: 3.1.7
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Implement user friendly buttons:
up, down, select page, forward, backward, go back to first page, go to end of document, etc.

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
The design will be slightly changed and it will also looks little different after implementation in to the portal. All navigation is very self-explanatory.

@HenningScholz 
@grahamhrbge1670 

The slider will be use only in full screen view mode. This function will be implemented after content viewer integration to the portal. Navigation in content viewer on portal could be manage by pagination same as on BHL US.
