### ISSUE TITLE
Search page - list of search results - cut long titles of publications

### ISSUE THREAD

**Issue by fwelter** [gbhl/bhl-europe#9]
In the list of search results/query results:
Titles should be cut if they contain text that covers more than 2 lines space in the list of results. 

Example:
http://test111.ait.co.at/?q=advanced_search_view/%7B!lucene%7DKu%CC%88sten

4 results can be seen here, sorted by date returns long titles for hits No. 1 (4 lines in my browser) and 2 (5 lines).

Hit No. 2:
# Untersuchungen über die säkulare landhebung als pflanzengeograpischer faktor  Jämtlands... kärlväxtflora  Die varietäten von Carex salina wg ssp. cuspidata wg nebst ihren hybriden an den küsten des bottnischen busens, Finnland  Die taraxacum-flora Estlands  Über den antagonismus von wasserstoffionen und metallkationen bei micrasterias  Experimentelle untersuchungen über die euanemochore verbreitung der sporenpflanzen

In my browser with hard returns inserted to show the line breaks:

Untersuchungen über die säkulare landhebung als pflanzengeograpischer faktor  
Jämtlands (...) Die varietäten von Carex salina wg ssp. cuspidata wg nebst ihren hybriden an 
den küsten des bottnischen busens, Finnland  Die taraxacum-flora Estlands  Über den 
antagonismus von wasserstoffionen und metallkationen bei micrasterias  Experimentelle 
untersuchungen über die euanemochore verbreitung der sporenpflanzen >>

Should be shown in this form:

Untersuchungen über die säkulare landhebung als pflanzengeograpischer faktor 
Jämtlands kärlväxtflora. Die varietäten von Carex salina wg ssp. cuspidata nebst ihren

If it is not possible to tell the program to understand how many lines of text are shown in the currently used browser, then cut the length of the title to a standard value of maximum 200 characters.

(for the bugs in the presentation of the same title (the kärlväxtflora case, UTF 8 problem) see the issues No. 10 and 11).

**Comment by janahoffmann** [comment]
This issue is related to CoR feature 1.4.1. Your report will be forwarded to the test manager.
@fwelter
@jirifrank

**Comment by janahoffmann** [comment]
now issue #61
