### ISSUE TITLE
3.1.10 - Change display quality (Content view)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#92]
+/- buttons for low-high display quality (different view modes) or color/ black-white in content viewer

Preconditions: decide default setting

**Comment by fwelter** [comment]
Black & white and low display quality should generally be default. Speed in the content viewer was identificed as more important than quality.

However, if the scanned item contains exclusively colour plates, it might be an option to select colour and moderately high quality as default. Precondition would be that the program recognises an item as a colour plates only book.

**Comment by JiriFrank** [comment]
Is this a valid requirement?
@chris-sleep

**Comment by chris-sleep** [comment]
at this point in time; requirement is valid, default already set in the viewer
