### ISSUE TITLE
3.1.11 - Show all recognized taxa in content viewer (per page) (content view)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#93]
List scientific names recognised by uBio in content viewer, e.g. per page as in BHLUS portal (lower left box)

Precondition: Integration of uBio (TaxonFinder), save names and coordinates in metadata (OLEF)

**Comment by heimor** [comment]
@lobajuluwa
again same question why this has been assigned to NHMW

is its intention to integrate displaying the found names in the ebook-Viewer ? 
if yes then we assume that the ebook-Viewer needs to be adopted adequately - correct ?

**Comment by lobajuluwa** [comment]
@heimor
@janahoffmann

Jana can you please clarify the exact requirements for this particular feature request. If there's still some aspects to be completed by AIT beforehand pls let me know. Thanks.

**Comment by lobajuluwa** [comment]
Portal Review Workshop update (Heimo): Taxon finder is not integrated in bookviewer. BHLUS has just the names finder at the moment, common names, scientific names will follow. What are the exact requirements? how to display it in the bookviewer. Reassigned to Jiri for Nov release.

**Comment by janahoffmann** [comment]
@lobajuluwa
@heimor
@jirifrank
I think it is helpful to see the scientific names (uBio) that are in the document (hyperlinks?). I leave it to Jiri to decide on how to do this. I think the BHLUS approach is not bad. I would not list any other 'extended search terms' in the content viewer. This feature is restricted to scientific names recognised by uBio in the literature. In the end the TaxonFinder has to be implemented in the content viwer somehow.

**Comment by JiriFrank** [comment]
I agree with the point to display in book viewer just taxon which is included in the document. The extended terms as a common names are good for the facet list with the search combination. The best solution will be to use the same system as BHLUS. I am not sure how this system works exactly in technical view. 

@janahoffmann
@lobajuluwa
@heimor
There are two different things. One is the developing and integration of the function and the second is displaying of this function. I or Atos can handle with the second part, but not with the first one.

**Comment by JiriFrank** [comment]
Adapt BHL-Australia
e.g.
http://bhl.ala.org.au/item/89647#page/48/mode/2up

**Comment by chris-sleep** [comment]
Feedback from US user survey raises that .au model does not meet user desires; display alongside the bookviewer with all recognized taxa is better fit

**Comment by lobajuluwa** [comment]
@JiriFrank
ubio data in separate frame holding taxon - Re-assigned to Jiri

**Comment by heimor** [comment]
taxonfinder delivers results together with "real" scientific names that do not represent scientific names -
those can be distinguished by the existence of an identifier ( NameBankID )
all scientific names are accompanied by an identifier / non scientific names lack such an identifier

we need to exclude such non scientific names from integration into olef metadata 

relates to Refactorisation of PI-Tool Issue #299

**Comment by JiriFrank** [comment]
Done and testable in the meaning of functionality.

**Comment by JiriFrank** [comment]
3.1.11 - Show all recognized taxa in content viewer (per page) (content view)

COR number: 3.1.11  
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

List scientific names recognised by uBio in content viewer, e.g. per page as in BHLUS portal (lower left box)

The panel with taxon blok will appear if you click on the small arrow in the middle of the left side in the content viewer. 

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
3.1.11 - Show all recognized taxa in content viewer (per page) (content view)

COR number: 3.1.11  
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

List scientific names recognised by uBio in content viewer, e.g. per page as in BHLUS portal (lower left box)

The panel with taxon blok will appear if you click on the small arrow in the middle of the left side in the content viewer. 

---

@GregKenicer
@GeoffHarper
@KasiaGoral
@MartinaMetzger
@DanielFisher
@NeilWoodcock
@SaraPerzley
@SaraCarlton
@HannaKoivula
@PaiviLipsanen

**Comment by JiriFrank** [comment]
3.1.11 - Show all recognized taxa in content viewer (per page) (content view)

COR number: 3.1.11  
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

List scientific names recognised by uBio in content viewer, e.g. per page as in BHLUS portal (lower left box)

The panel with taxon blok will appear if you click on the small arrow in the middle of the left side in the content viewer. 

---

@PaiviJaakkola
@SiniKarki
@TiinaOnttonen

**Comment by LarissaS** [comment]
Does not work.
Even if I see the taxon name written on the page, searching for the same name give one result on the first page, even if the first page is just cover!

-----Original Message-----

**Comment by HenningScholz** [comment]
Yes, this works as well, if the OCR provided good results - the usual problem...also here, the window should be open by default and the user can click it away.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Do 12.04.2012 18:58
An: Scholz, Henning
Betreff: Re: [bhle] 3.1.11 - Show all recognized taxa in content viewer (per page) (content view) (#93)

3.1.11 - Show all recognized taxa in content viewer (per page) (content view)

COR number: 3.1.11 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

List scientific names recognised by uBio in content viewer, e.g. per page as in BHLUS portal (lower left box)

The panel with taxon blok will appear if you click on the small arrow in the middle of the left side in the content viewer.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by RalfH** [comment]
It works - more or less. Taxon names such as Calluna are found but not if they are hyphenated (as in my case: "Calluna-mats"). There seem to be problems as well if epithets' initial letters are capital letters (in some older sources; e.g. Arctostaphylos Uva-ursi). This seems to confuse the system. And the epithets are displayed as generic names.

In many cases listing of taxon names is far from complete. The lists comprise about 50 % of names. Even common names such as Salix and Potentilla are not identified.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Donnerstag, 12. April 2012 18:58
An: Hand, Ralf
Betreff: Re: [bhle] 3.1.11 - Show all recognized taxa in content viewer (per page) (content view) (#93)

3.1.11 - Show all recognized taxa in content viewer (per page) (content view)

COR number: 3.1.11  
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

List scientific names recognised by uBio in content viewer, e.g. per page as in BHLUS portal (lower left box)

The panel with taxon blok will appear if you click on the small arrow in the middle of the left side in the content viewer. 

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by RalfH** [comment]
PS: The panel is really difficult to be found for a new user.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Donnerstag, 12. April 2012 18:58
An: Hand, Ralf
Betreff: Re: [bhle] 3.1.11 - Show all recognized taxa in content viewer (per page) (content view) (#93)

3.1.11 - Show all recognized taxa in content viewer (per page) (content view)

COR number: 3.1.11  
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

List scientific names recognised by uBio in content viewer, e.g. per page as in BHLUS portal (lower left box)

The panel with taxon blok will appear if you click on the small arrow in the middle of the left side in the content viewer. 

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamtestrbge** [comment]
I agree with Ralf's observation regarding the missing names, checking Vegetation of Caithness, Salix and Potentilla  are missing. However it is good that the facility has been put in place. 

Quality of OCR is difficult to assess.  Looking at 1 page in Flore elementaire des cryptogames (page 32) it contains 9 genus names in a key (all in bold non-italicised)  11 species names (non-italicised, but in different font from main text) and the Taxon Finder has recognised: 3 species and 4 genera.

**Comment by AntonioGVH** [comment]
Not all taxa in page recognized by uBio. 

I include a screen shot of a page of 'Los coleopteros de Marruecos' and the taxonomic name in page are many more than those listed in the left.

Antonio

-----Mensaje original-----
De: JiriFrank [mailto:reply@reply.github.com] 
Enviado el: jueves, 12 de abril de 2012 18:58
Para: AntonioGVH
Asunto: Re: [bhle] 3.1.11 - Show all recognized taxa in content viewer (per page) (content view) (#93)

3.1.11 - Show all recognized taxa in content viewer (per page) (content view)

COR number: 3.1.11  
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

List scientific names recognised by uBio in content viewer, e.g. per page as in BHLUS portal (lower left box)

The panel with taxon blok will appear if you click on the small arrow in the middle of the left side in the content viewer. 

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by KasiaGoral** [comment]
Searched for *Ajuga repens. *No taxa shown in the contet viewer of 'The
vegetation of Caithness considered in relation to the geology'.

**Comment by JiriFrank** [comment]
The function is implemented and functional. The taxa are displayed depending on the quality of OCR. 
Ready for close.
