### ISSUE TITLE
3.1.13 - Copy text directly from content viewer (Content view)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#95]
mark text in document in content viewer, copy/paste

Precondition: OCR of item

**Comment by fwelter** [comment]
OCR must eventually be checked for correct character encoding, so that the copied text arrives correctly.

**Comment by janahoffmann** [comment]
@fwelter well, that's the future ;-) but we won't be able to provide this service for our users....crowdsourcing was discussed as an option to improve OCR quality...

**Comment by fwelter** [comment]
Probably misunderstood. Character encoding. This is not correctness of text, only correctness of diacritics etc.
This does not have to do with community actions. It would only be necessary to recognise which character encoding had been used by the instoitution that provided the OCR document, and either indicate which one it was, or convert it automatically into UTF-8. For the developers this should be a relatively easy task.

**Comment by leenamba** [comment]
Two options: 
- Select text in an overlay of the OCR on the images of the book.  For this the coordinates of the OCR text as well as the OCR text must be provided to the Book Viewer.  The OCR text and coordinates should be provided by the same OCR process, either by the Content Providers, Pre-ingest, or Ingest.
- Select text in a separate window with just the OCR text.  For this only the OCR text is required for the Book Viewer.

**Comment by zhengl** [comment]
Option 2 is done.

A live example:
http://bhle-dev-1.nhm.ac.uk/fedora/objects/demo%3Adarwin/methods/demo%3AbookSdef/bookreader?ui=#page/1/mode/1up

OCR can be selected in a Textarea, and that's the first level of "select directly".

Also, the "Correct it!" is just a demo, wait for the authorization mechanism (LDAP) to be realized.

**Comment by leenamba** [comment]
@jirifrank

**Comment by JiriFrank** [comment]
3.1.13 - Copy text directly from content viewer (Content view)

COR number: 3.1.13
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

mark text in document in content viewer, copy/paste

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
3.1.13 - Copy text directly from content viewer (Content view)

COR number: 3.1.13
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

mark text in document in content viewer, copy/paste

You can reach the content viewer by click on Read book in result list.

@AntonioGVH
@fwelter
@LarissaS

**Comment by LarissaS** [comment]
Did not find how to mark it! 

-----Original Message-----

**Comment by HenningScholz** [comment]
The only way I could get content out is via the OCR pop-up: show OCR, mark text and copy-paste to Word.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 15:20
An: Scholz, Henning
Betreff: Re: [bhle] 3.1.13 - Copy text directly from content viewer (Content view) (#95)

3.1.13 - Copy text directly from content viewer (Content view)

COR number: 3.1.13
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

mark text in document in content viewer, copy/paste

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
I did the same as Henning, it works.

**Comment by RalfH** [comment]
If that means: copy and paste a complete page (e.g. in a word document), then it works.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:21
An: Hand, Ralf
Betreff: Re: [bhle] 3.1.13 - Copy text directly from content viewer (Content view) (#95)

3.1.13 - Copy text directly from content viewer (Content view)

COR number: 3.1.13
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

mark text in document in content viewer, copy/paste

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AntonioGVH** [comment]
I couldn't do it.
When I click on a page to begin marking, it moves to the next page.
I can ask for the OCR and then copy/paste, but I suppose that this is not what you  are asking here.

Quoting JiriFrank:

**Comment by AnneSch** [comment]
Same problem as by other testers: Couldn't manage to mark pages, I only could mark the text by the OCR reader. But this method cannot be used for pictures...

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:21
An: Scholz, Annemarie
Betreff: Re: [bhle] 3.1.13 - Copy text directly from content viewer (Content view) (#95)

3.1.13 - Copy text directly from content viewer (Content view)

COR number: 3.1.13
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

mark text in document in content viewer, copy/paste

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AnneSch** [comment]
Same problem as by other testers: Couldn't manage to mark pages, I only could mark the text by the OCR reader. But this method cannot be used for pictures...

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Dienstag, 17. Januar 2012 15:21
An: Scholz, Annemarie
Betreff: Re: [bhle] 3.1.13 - Copy text directly from content viewer (Content view) (#95)

3.1.13 - Copy text directly from content viewer (Content view)

COR number: 3.1.13
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

mark text in document in content viewer, copy/paste

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by zhengl** [comment]
Really challenging to copy text directly in images. The basic technical solution is to provide an extra invisible layer on images filled with OCR'ed text and their coordinates. OCR engine Tesseract can only produce pure OCR'ed text or coordinates for each character. Therefore the first obstacle to how to restore all the text and coordinates back to paragraphs, the second one is how to update this layer when OCR is improved by the end users.

**Comment by JiriFrank** [comment]
The only way I could get content out is via the OCR pop-up: show OCR, mark text and copy-paste to Word.

Yes this is the only option now. If the user do not lake the OCR, he can help us to correct it after we will implement this function. Still working on that. Complications with copy paste the text directly from the picture, because book-viewer is showing pictures not pdf, please see in Zheng comment https://github.com/bhle/bhle/issues/95#issuecomment-3647535.

@HenningScholz 
@grahamhrbge1670 
@RalfH 
@AntonioGVH 
@LarissaS 

You can download the picture by right click on it with the whole page of course. Again it is displayed as a picture and not interactive pdf. If you want a picture from page which is in combination with text. Download the picture and cut it from the page. The pictures are part of the page also with the same quality as the page. Suitable are the whole page illustrations.

@AnneSch

**Comment by HenningScholz** [comment]
I'm happy to copy text out of the OCR. It is not to much of an extra effort for the user. It would also show the real quality of the text, as it would be confusing for the user to copy text and not getting the correct text, if the OCR is not 100% correct. So copy out of OCR is fine, I think.

Henning

---

Dr. Henning Scholz 
Museum für Naturkunde | Leibniz Institute for Research on Evolution and Biodiversity at the Humboldt University Berlin
Invalidenstraße 43 | D-10115 Berlin | Germany 
Tel.: +49-30-2093-8864 | Fax: +49-30-2093-8868 
Email: henning.scholz@mfn-berlin.de
http://www.naturkundemuseum-berlin.de/ / http://www.bivalve.de 
http://www.bhl-europe.eu / http://www.biodiversitylibrary.org/
BHL-Europe in Europeana:  bit.ly/BHLE-Europeana
-----Ursprüngliche Nachricht-----
Von: LI Zheng [mailto:reply@reply.github.com] 
Gesendet: Mittwoch, 25. Januar 2012 09:51
An: Scholz, Henning
Betreff: Re: [bhle] 3.1.13 - Copy text directly from content viewer (Content view) (#95)

Really challenging to copy text directly in images. The basic technical solution is to provide an extra invisible layer on images filled with OCR'ed text and their coordinates. OCR engine Tesseract can only produce pure OCR'ed text or coordinates for each character. Therefore the first obstacle to how to restore all the text and coordinates back to paragraphs, the second one is how to update this layer when OCR is improved by the end users.

---
