### ISSUE TITLE
3.1.16 - Distance Measuring of Depictions in Units (scaling page?)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#98]
Calibrate the distance using a ruler, apply calibrated ruler to depiction, scale page to appropriate size of window

**Comment by janahoffmann** [comment]
Please provide a better description. What is this about? This feature was added to the list by someone else...Who? Please clarify!

**Comment by lobajuluwa** [comment]
need to define meaning and relevance.
